// Code generated by ent, DO NOT EDIT.

package modelchannel

import (
	"bridal/backend/db/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldName, v))
}

// APIBaseURL applies equality check predicate on the "api_base_url" field. It's identical to APIBaseURLEQ.
func APIBaseURL(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldAPIBaseURL, v))
}

// APIKey applies equality check predicate on the "api_key" field. It's identical to APIKeyEQ.
func APIKey(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldAPIKey, v))
}

// Protocol applies equality check predicate on the "protocol" field. It's identical to ProtocolEQ.
func Protocol(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldProtocol, v))
}

// ModelID applies equality check predicate on the "model_id" field. It's identical to ModelIDEQ.
func ModelID(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldModelID, v))
}

// DefaultQuality applies equality check predicate on the "default_quality" field. It's identical to DefaultQualityEQ.
func DefaultQuality(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldDefaultQuality, v))
}

// IsEnabled applies equality check predicate on the "is_enabled" field. It's identical to IsEnabledEQ.
func IsEnabled(v bool) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldIsEnabled, v))
}

// IsDefault applies equality check predicate on the "is_default" field. It's identical to IsDefaultEQ.
func IsDefault(v bool) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldIsDefault, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldSortOrder, v))
}

// MaxConcurrency applies equality check predicate on the "max_concurrency" field. It's identical to MaxConcurrencyEQ.
func MaxConcurrency(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldMaxConcurrency, v))
}

// TotalRequests applies equality check predicate on the "total_requests" field. It's identical to TotalRequestsEQ.
func TotalRequests(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldTotalRequests, v))
}

// SuccessRequests applies equality check predicate on the "success_requests" field. It's identical to SuccessRequestsEQ.
func SuccessRequests(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldSuccessRequests, v))
}

// FailedRequests applies equality check predicate on the "failed_requests" field. It's identical to FailedRequestsEQ.
func FailedRequests(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldFailedRequests, v))
}

// TotalLatencyMs applies equality check predicate on the "total_latency_ms" field. It's identical to TotalLatencyMsEQ.
func TotalLatencyMs(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldTotalLatencyMs, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldContainsFold(FieldName, v))
}

// APIBaseURLEQ applies the EQ predicate on the "api_base_url" field.
func APIBaseURLEQ(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldAPIBaseURL, v))
}

// APIBaseURLNEQ applies the NEQ predicate on the "api_base_url" field.
func APIBaseURLNEQ(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNEQ(FieldAPIBaseURL, v))
}

// APIBaseURLIn applies the In predicate on the "api_base_url" field.
func APIBaseURLIn(vs ...string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldIn(FieldAPIBaseURL, vs...))
}

// APIBaseURLNotIn applies the NotIn predicate on the "api_base_url" field.
func APIBaseURLNotIn(vs ...string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNotIn(FieldAPIBaseURL, vs...))
}

// APIBaseURLGT applies the GT predicate on the "api_base_url" field.
func APIBaseURLGT(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGT(FieldAPIBaseURL, v))
}

// APIBaseURLGTE applies the GTE predicate on the "api_base_url" field.
func APIBaseURLGTE(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGTE(FieldAPIBaseURL, v))
}

// APIBaseURLLT applies the LT predicate on the "api_base_url" field.
func APIBaseURLLT(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLT(FieldAPIBaseURL, v))
}

// APIBaseURLLTE applies the LTE predicate on the "api_base_url" field.
func APIBaseURLLTE(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLTE(FieldAPIBaseURL, v))
}

// APIBaseURLContains applies the Contains predicate on the "api_base_url" field.
func APIBaseURLContains(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldContains(FieldAPIBaseURL, v))
}

// APIBaseURLHasPrefix applies the HasPrefix predicate on the "api_base_url" field.
func APIBaseURLHasPrefix(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldHasPrefix(FieldAPIBaseURL, v))
}

// APIBaseURLHasSuffix applies the HasSuffix predicate on the "api_base_url" field.
func APIBaseURLHasSuffix(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldHasSuffix(FieldAPIBaseURL, v))
}

// APIBaseURLEqualFold applies the EqualFold predicate on the "api_base_url" field.
func APIBaseURLEqualFold(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEqualFold(FieldAPIBaseURL, v))
}

// APIBaseURLContainsFold applies the ContainsFold predicate on the "api_base_url" field.
func APIBaseURLContainsFold(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldContainsFold(FieldAPIBaseURL, v))
}

// APIKeyEQ applies the EQ predicate on the "api_key" field.
func APIKeyEQ(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldAPIKey, v))
}

// APIKeyNEQ applies the NEQ predicate on the "api_key" field.
func APIKeyNEQ(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNEQ(FieldAPIKey, v))
}

// APIKeyIn applies the In predicate on the "api_key" field.
func APIKeyIn(vs ...string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldIn(FieldAPIKey, vs...))
}

// APIKeyNotIn applies the NotIn predicate on the "api_key" field.
func APIKeyNotIn(vs ...string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNotIn(FieldAPIKey, vs...))
}

// APIKeyGT applies the GT predicate on the "api_key" field.
func APIKeyGT(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGT(FieldAPIKey, v))
}

// APIKeyGTE applies the GTE predicate on the "api_key" field.
func APIKeyGTE(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGTE(FieldAPIKey, v))
}

// APIKeyLT applies the LT predicate on the "api_key" field.
func APIKeyLT(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLT(FieldAPIKey, v))
}

// APIKeyLTE applies the LTE predicate on the "api_key" field.
func APIKeyLTE(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLTE(FieldAPIKey, v))
}

// APIKeyContains applies the Contains predicate on the "api_key" field.
func APIKeyContains(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldContains(FieldAPIKey, v))
}

// APIKeyHasPrefix applies the HasPrefix predicate on the "api_key" field.
func APIKeyHasPrefix(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldHasPrefix(FieldAPIKey, v))
}

// APIKeyHasSuffix applies the HasSuffix predicate on the "api_key" field.
func APIKeyHasSuffix(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldHasSuffix(FieldAPIKey, v))
}

// APIKeyEqualFold applies the EqualFold predicate on the "api_key" field.
func APIKeyEqualFold(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEqualFold(FieldAPIKey, v))
}

// APIKeyContainsFold applies the ContainsFold predicate on the "api_key" field.
func APIKeyContainsFold(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldContainsFold(FieldAPIKey, v))
}

// ProtocolEQ applies the EQ predicate on the "protocol" field.
func ProtocolEQ(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldProtocol, v))
}

// ProtocolNEQ applies the NEQ predicate on the "protocol" field.
func ProtocolNEQ(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNEQ(FieldProtocol, v))
}

// ProtocolIn applies the In predicate on the "protocol" field.
func ProtocolIn(vs ...string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldIn(FieldProtocol, vs...))
}

// ProtocolNotIn applies the NotIn predicate on the "protocol" field.
func ProtocolNotIn(vs ...string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNotIn(FieldProtocol, vs...))
}

// ProtocolGT applies the GT predicate on the "protocol" field.
func ProtocolGT(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGT(FieldProtocol, v))
}

// ProtocolGTE applies the GTE predicate on the "protocol" field.
func ProtocolGTE(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGTE(FieldProtocol, v))
}

// ProtocolLT applies the LT predicate on the "protocol" field.
func ProtocolLT(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLT(FieldProtocol, v))
}

// ProtocolLTE applies the LTE predicate on the "protocol" field.
func ProtocolLTE(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLTE(FieldProtocol, v))
}

// ProtocolContains applies the Contains predicate on the "protocol" field.
func ProtocolContains(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldContains(FieldProtocol, v))
}

// ProtocolHasPrefix applies the HasPrefix predicate on the "protocol" field.
func ProtocolHasPrefix(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldHasPrefix(FieldProtocol, v))
}

// ProtocolHasSuffix applies the HasSuffix predicate on the "protocol" field.
func ProtocolHasSuffix(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldHasSuffix(FieldProtocol, v))
}

// ProtocolEqualFold applies the EqualFold predicate on the "protocol" field.
func ProtocolEqualFold(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEqualFold(FieldProtocol, v))
}

// ProtocolContainsFold applies the ContainsFold predicate on the "protocol" field.
func ProtocolContainsFold(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldContainsFold(FieldProtocol, v))
}

// ModelIDEQ applies the EQ predicate on the "model_id" field.
func ModelIDEQ(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldModelID, v))
}

// ModelIDNEQ applies the NEQ predicate on the "model_id" field.
func ModelIDNEQ(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNEQ(FieldModelID, v))
}

// ModelIDIn applies the In predicate on the "model_id" field.
func ModelIDIn(vs ...string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldIn(FieldModelID, vs...))
}

// ModelIDNotIn applies the NotIn predicate on the "model_id" field.
func ModelIDNotIn(vs ...string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNotIn(FieldModelID, vs...))
}

// ModelIDGT applies the GT predicate on the "model_id" field.
func ModelIDGT(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGT(FieldModelID, v))
}

// ModelIDGTE applies the GTE predicate on the "model_id" field.
func ModelIDGTE(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGTE(FieldModelID, v))
}

// ModelIDLT applies the LT predicate on the "model_id" field.
func ModelIDLT(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLT(FieldModelID, v))
}

// ModelIDLTE applies the LTE predicate on the "model_id" field.
func ModelIDLTE(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLTE(FieldModelID, v))
}

// ModelIDContains applies the Contains predicate on the "model_id" field.
func ModelIDContains(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldContains(FieldModelID, v))
}

// ModelIDHasPrefix applies the HasPrefix predicate on the "model_id" field.
func ModelIDHasPrefix(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldHasPrefix(FieldModelID, v))
}

// ModelIDHasSuffix applies the HasSuffix predicate on the "model_id" field.
func ModelIDHasSuffix(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldHasSuffix(FieldModelID, v))
}

// ModelIDEqualFold applies the EqualFold predicate on the "model_id" field.
func ModelIDEqualFold(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEqualFold(FieldModelID, v))
}

// ModelIDContainsFold applies the ContainsFold predicate on the "model_id" field.
func ModelIDContainsFold(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldContainsFold(FieldModelID, v))
}

// DefaultQualityEQ applies the EQ predicate on the "default_quality" field.
func DefaultQualityEQ(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldDefaultQuality, v))
}

// DefaultQualityNEQ applies the NEQ predicate on the "default_quality" field.
func DefaultQualityNEQ(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNEQ(FieldDefaultQuality, v))
}

// DefaultQualityIn applies the In predicate on the "default_quality" field.
func DefaultQualityIn(vs ...string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldIn(FieldDefaultQuality, vs...))
}

// DefaultQualityNotIn applies the NotIn predicate on the "default_quality" field.
func DefaultQualityNotIn(vs ...string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNotIn(FieldDefaultQuality, vs...))
}

// DefaultQualityGT applies the GT predicate on the "default_quality" field.
func DefaultQualityGT(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGT(FieldDefaultQuality, v))
}

// DefaultQualityGTE applies the GTE predicate on the "default_quality" field.
func DefaultQualityGTE(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGTE(FieldDefaultQuality, v))
}

// DefaultQualityLT applies the LT predicate on the "default_quality" field.
func DefaultQualityLT(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLT(FieldDefaultQuality, v))
}

// DefaultQualityLTE applies the LTE predicate on the "default_quality" field.
func DefaultQualityLTE(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLTE(FieldDefaultQuality, v))
}

// DefaultQualityContains applies the Contains predicate on the "default_quality" field.
func DefaultQualityContains(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldContains(FieldDefaultQuality, v))
}

// DefaultQualityHasPrefix applies the HasPrefix predicate on the "default_quality" field.
func DefaultQualityHasPrefix(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldHasPrefix(FieldDefaultQuality, v))
}

// DefaultQualityHasSuffix applies the HasSuffix predicate on the "default_quality" field.
func DefaultQualityHasSuffix(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldHasSuffix(FieldDefaultQuality, v))
}

// DefaultQualityEqualFold applies the EqualFold predicate on the "default_quality" field.
func DefaultQualityEqualFold(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEqualFold(FieldDefaultQuality, v))
}

// DefaultQualityContainsFold applies the ContainsFold predicate on the "default_quality" field.
func DefaultQualityContainsFold(v string) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldContainsFold(FieldDefaultQuality, v))
}

// IsEnabledEQ applies the EQ predicate on the "is_enabled" field.
func IsEnabledEQ(v bool) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldIsEnabled, v))
}

// IsEnabledNEQ applies the NEQ predicate on the "is_enabled" field.
func IsEnabledNEQ(v bool) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNEQ(FieldIsEnabled, v))
}

// IsDefaultEQ applies the EQ predicate on the "is_default" field.
func IsDefaultEQ(v bool) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldIsDefault, v))
}

// IsDefaultNEQ applies the NEQ predicate on the "is_default" field.
func IsDefaultNEQ(v bool) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNEQ(FieldIsDefault, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLTE(FieldSortOrder, v))
}

// MaxConcurrencyEQ applies the EQ predicate on the "max_concurrency" field.
func MaxConcurrencyEQ(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldMaxConcurrency, v))
}

// MaxConcurrencyNEQ applies the NEQ predicate on the "max_concurrency" field.
func MaxConcurrencyNEQ(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNEQ(FieldMaxConcurrency, v))
}

// MaxConcurrencyIn applies the In predicate on the "max_concurrency" field.
func MaxConcurrencyIn(vs ...int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldIn(FieldMaxConcurrency, vs...))
}

// MaxConcurrencyNotIn applies the NotIn predicate on the "max_concurrency" field.
func MaxConcurrencyNotIn(vs ...int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNotIn(FieldMaxConcurrency, vs...))
}

// MaxConcurrencyGT applies the GT predicate on the "max_concurrency" field.
func MaxConcurrencyGT(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGT(FieldMaxConcurrency, v))
}

// MaxConcurrencyGTE applies the GTE predicate on the "max_concurrency" field.
func MaxConcurrencyGTE(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGTE(FieldMaxConcurrency, v))
}

// MaxConcurrencyLT applies the LT predicate on the "max_concurrency" field.
func MaxConcurrencyLT(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLT(FieldMaxConcurrency, v))
}

// MaxConcurrencyLTE applies the LTE predicate on the "max_concurrency" field.
func MaxConcurrencyLTE(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLTE(FieldMaxConcurrency, v))
}

// TotalRequestsEQ applies the EQ predicate on the "total_requests" field.
func TotalRequestsEQ(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldTotalRequests, v))
}

// TotalRequestsNEQ applies the NEQ predicate on the "total_requests" field.
func TotalRequestsNEQ(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNEQ(FieldTotalRequests, v))
}

// TotalRequestsIn applies the In predicate on the "total_requests" field.
func TotalRequestsIn(vs ...int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldIn(FieldTotalRequests, vs...))
}

// TotalRequestsNotIn applies the NotIn predicate on the "total_requests" field.
func TotalRequestsNotIn(vs ...int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNotIn(FieldTotalRequests, vs...))
}

// TotalRequestsGT applies the GT predicate on the "total_requests" field.
func TotalRequestsGT(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGT(FieldTotalRequests, v))
}

// TotalRequestsGTE applies the GTE predicate on the "total_requests" field.
func TotalRequestsGTE(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGTE(FieldTotalRequests, v))
}

// TotalRequestsLT applies the LT predicate on the "total_requests" field.
func TotalRequestsLT(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLT(FieldTotalRequests, v))
}

// TotalRequestsLTE applies the LTE predicate on the "total_requests" field.
func TotalRequestsLTE(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLTE(FieldTotalRequests, v))
}

// SuccessRequestsEQ applies the EQ predicate on the "success_requests" field.
func SuccessRequestsEQ(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldSuccessRequests, v))
}

// SuccessRequestsNEQ applies the NEQ predicate on the "success_requests" field.
func SuccessRequestsNEQ(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNEQ(FieldSuccessRequests, v))
}

// SuccessRequestsIn applies the In predicate on the "success_requests" field.
func SuccessRequestsIn(vs ...int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldIn(FieldSuccessRequests, vs...))
}

// SuccessRequestsNotIn applies the NotIn predicate on the "success_requests" field.
func SuccessRequestsNotIn(vs ...int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNotIn(FieldSuccessRequests, vs...))
}

// SuccessRequestsGT applies the GT predicate on the "success_requests" field.
func SuccessRequestsGT(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGT(FieldSuccessRequests, v))
}

// SuccessRequestsGTE applies the GTE predicate on the "success_requests" field.
func SuccessRequestsGTE(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGTE(FieldSuccessRequests, v))
}

// SuccessRequestsLT applies the LT predicate on the "success_requests" field.
func SuccessRequestsLT(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLT(FieldSuccessRequests, v))
}

// SuccessRequestsLTE applies the LTE predicate on the "success_requests" field.
func SuccessRequestsLTE(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLTE(FieldSuccessRequests, v))
}

// FailedRequestsEQ applies the EQ predicate on the "failed_requests" field.
func FailedRequestsEQ(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldFailedRequests, v))
}

// FailedRequestsNEQ applies the NEQ predicate on the "failed_requests" field.
func FailedRequestsNEQ(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNEQ(FieldFailedRequests, v))
}

// FailedRequestsIn applies the In predicate on the "failed_requests" field.
func FailedRequestsIn(vs ...int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldIn(FieldFailedRequests, vs...))
}

// FailedRequestsNotIn applies the NotIn predicate on the "failed_requests" field.
func FailedRequestsNotIn(vs ...int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNotIn(FieldFailedRequests, vs...))
}

// FailedRequestsGT applies the GT predicate on the "failed_requests" field.
func FailedRequestsGT(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGT(FieldFailedRequests, v))
}

// FailedRequestsGTE applies the GTE predicate on the "failed_requests" field.
func FailedRequestsGTE(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGTE(FieldFailedRequests, v))
}

// FailedRequestsLT applies the LT predicate on the "failed_requests" field.
func FailedRequestsLT(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLT(FieldFailedRequests, v))
}

// FailedRequestsLTE applies the LTE predicate on the "failed_requests" field.
func FailedRequestsLTE(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLTE(FieldFailedRequests, v))
}

// TotalLatencyMsEQ applies the EQ predicate on the "total_latency_ms" field.
func TotalLatencyMsEQ(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldTotalLatencyMs, v))
}

// TotalLatencyMsNEQ applies the NEQ predicate on the "total_latency_ms" field.
func TotalLatencyMsNEQ(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNEQ(FieldTotalLatencyMs, v))
}

// TotalLatencyMsIn applies the In predicate on the "total_latency_ms" field.
func TotalLatencyMsIn(vs ...int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldIn(FieldTotalLatencyMs, vs...))
}

// TotalLatencyMsNotIn applies the NotIn predicate on the "total_latency_ms" field.
func TotalLatencyMsNotIn(vs ...int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNotIn(FieldTotalLatencyMs, vs...))
}

// TotalLatencyMsGT applies the GT predicate on the "total_latency_ms" field.
func TotalLatencyMsGT(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGT(FieldTotalLatencyMs, v))
}

// TotalLatencyMsGTE applies the GTE predicate on the "total_latency_ms" field.
func TotalLatencyMsGTE(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGTE(FieldTotalLatencyMs, v))
}

// TotalLatencyMsLT applies the LT predicate on the "total_latency_ms" field.
func TotalLatencyMsLT(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLT(FieldTotalLatencyMs, v))
}

// TotalLatencyMsLTE applies the LTE predicate on the "total_latency_ms" field.
func TotalLatencyMsLTE(v int) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLTE(FieldTotalLatencyMs, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ModelChannel {
	return predicate.ModelChannel(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelChannel) predicate.ModelChannel {
	return predicate.ModelChannel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelChannel) predicate.ModelChannel {
	return predicate.ModelChannel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelChannel) predicate.ModelChannel {
	return predicate.ModelChannel(sql.NotPredicates(p))
}
