// Code generated by ent, DO NOT EDIT.

package db

import (
	"bridal/backend/db/contentengine"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ContentEngineCreate is the builder for creating a ContentEngine entity.
type ContentEngineCreate struct {
	config
	mutation *ContentEngineMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetKey sets the "key" field.
func (_c *ContentEngineCreate) SetKey(v string) *ContentEngineCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ContentEngineCreate) SetName(v string) *ContentEngineCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *ContentEngineCreate) SetNillableName(v *string) *ContentEngineCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *ContentEngineCreate) SetDescription(v string) *ContentEngineCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ContentEngineCreate) SetNillableDescription(v *string) *ContentEngineCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetConfig sets the "config" field.
func (_c *ContentEngineCreate) SetConfig(v map[string]interface{}) *ContentEngineCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetIsEnabled sets the "is_enabled" field.
func (_c *ContentEngineCreate) SetIsEnabled(v bool) *ContentEngineCreate {
	_c.mutation.SetIsEnabled(v)
	return _c
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_c *ContentEngineCreate) SetNillableIsEnabled(v *bool) *ContentEngineCreate {
	if v != nil {
		_c.SetIsEnabled(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *ContentEngineCreate) SetSortOrder(v int) *ContentEngineCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *ContentEngineCreate) SetNillableSortOrder(v *int) *ContentEngineCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ContentEngineCreate) SetCreatedAt(v time.Time) *ContentEngineCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ContentEngineCreate) SetNillableCreatedAt(v *time.Time) *ContentEngineCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ContentEngineCreate) SetUpdatedAt(v time.Time) *ContentEngineCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ContentEngineCreate) SetNillableUpdatedAt(v *time.Time) *ContentEngineCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ContentEngineCreate) SetID(v uuid.UUID) *ContentEngineCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ContentEngineCreate) SetNillableID(v *uuid.UUID) *ContentEngineCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ContentEngineMutation object of the builder.
func (_c *ContentEngineCreate) Mutation() *ContentEngineMutation {
	return _c.mutation
}

// Save creates the ContentEngine in the database.
func (_c *ContentEngineCreate) Save(ctx context.Context) (*ContentEngine, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ContentEngineCreate) SaveX(ctx context.Context) *ContentEngine {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContentEngineCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContentEngineCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ContentEngineCreate) defaults() {
	if _, ok := _c.mutation.Name(); !ok {
		v := contentengine.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := contentengine.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Config(); !ok {
		v := contentengine.DefaultConfig
		_c.mutation.SetConfig(v)
	}
	if _, ok := _c.mutation.IsEnabled(); !ok {
		v := contentengine.DefaultIsEnabled
		_c.mutation.SetIsEnabled(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := contentengine.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := contentengine.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := contentengine.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := contentengine.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ContentEngineCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`db: missing required field "ContentEngine.key"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`db: missing required field "ContentEngine.name"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`db: missing required field "ContentEngine.description"`)}
	}
	if _, ok := _c.mutation.Config(); !ok {
		return &ValidationError{Name: "config", err: errors.New(`db: missing required field "ContentEngine.config"`)}
	}
	if _, ok := _c.mutation.IsEnabled(); !ok {
		return &ValidationError{Name: "is_enabled", err: errors.New(`db: missing required field "ContentEngine.is_enabled"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`db: missing required field "ContentEngine.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`db: missing required field "ContentEngine.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`db: missing required field "ContentEngine.updated_at"`)}
	}
	return nil
}

func (_c *ContentEngineCreate) sqlSave(ctx context.Context) (*ContentEngine, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ContentEngineCreate) createSpec() (*ContentEngine, *sqlgraph.CreateSpec) {
	var (
		_node = &ContentEngine{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(contentengine.Table, sqlgraph.NewFieldSpec(contentengine.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(contentengine.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(contentengine.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(contentengine.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(contentengine.FieldConfig, field.TypeJSON, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.IsEnabled(); ok {
		_spec.SetField(contentengine.FieldIsEnabled, field.TypeBool, value)
		_node.IsEnabled = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(contentengine.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(contentengine.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(contentengine.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ContentEngine.Create().
//		SetKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ContentEngineUpsert) {
//			SetKey(v+v).
//		}).
//		Exec(ctx)
func (_c *ContentEngineCreate) OnConflict(opts ...sql.ConflictOption) *ContentEngineUpsertOne {
	_c.conflict = opts
	return &ContentEngineUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ContentEngine.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ContentEngineCreate) OnConflictColumns(columns ...string) *ContentEngineUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ContentEngineUpsertOne{
		create: _c,
	}
}

type (
	// ContentEngineUpsertOne is the builder for "upsert"-ing
	//  one ContentEngine node.
	ContentEngineUpsertOne struct {
		create *ContentEngineCreate
	}

	// ContentEngineUpsert is the "OnConflict" setter.
	ContentEngineUpsert struct {
		*sql.UpdateSet
	}
)

// SetKey sets the "key" field.
func (u *ContentEngineUpsert) SetKey(v string) *ContentEngineUpsert {
	u.Set(contentengine.FieldKey, v)
	return u
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *ContentEngineUpsert) UpdateKey() *ContentEngineUpsert {
	u.SetExcluded(contentengine.FieldKey)
	return u
}

// SetName sets the "name" field.
func (u *ContentEngineUpsert) SetName(v string) *ContentEngineUpsert {
	u.Set(contentengine.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ContentEngineUpsert) UpdateName() *ContentEngineUpsert {
	u.SetExcluded(contentengine.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *ContentEngineUpsert) SetDescription(v string) *ContentEngineUpsert {
	u.Set(contentengine.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ContentEngineUpsert) UpdateDescription() *ContentEngineUpsert {
	u.SetExcluded(contentengine.FieldDescription)
	return u
}

// SetConfig sets the "config" field.
func (u *ContentEngineUpsert) SetConfig(v map[string]interface{}) *ContentEngineUpsert {
	u.Set(contentengine.FieldConfig, v)
	return u
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *ContentEngineUpsert) UpdateConfig() *ContentEngineUpsert {
	u.SetExcluded(contentengine.FieldConfig)
	return u
}

// SetIsEnabled sets the "is_enabled" field.
func (u *ContentEngineUpsert) SetIsEnabled(v bool) *ContentEngineUpsert {
	u.Set(contentengine.FieldIsEnabled, v)
	return u
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *ContentEngineUpsert) UpdateIsEnabled() *ContentEngineUpsert {
	u.SetExcluded(contentengine.FieldIsEnabled)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *ContentEngineUpsert) SetSortOrder(v int) *ContentEngineUpsert {
	u.Set(contentengine.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ContentEngineUpsert) UpdateSortOrder() *ContentEngineUpsert {
	u.SetExcluded(contentengine.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ContentEngineUpsert) AddSortOrder(v int) *ContentEngineUpsert {
	u.Add(contentengine.FieldSortOrder, v)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *ContentEngineUpsert) SetCreatedAt(v time.Time) *ContentEngineUpsert {
	u.Set(contentengine.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ContentEngineUpsert) UpdateCreatedAt() *ContentEngineUpsert {
	u.SetExcluded(contentengine.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ContentEngineUpsert) SetUpdatedAt(v time.Time) *ContentEngineUpsert {
	u.Set(contentengine.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ContentEngineUpsert) UpdateUpdatedAt() *ContentEngineUpsert {
	u.SetExcluded(contentengine.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ContentEngine.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(contentengine.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ContentEngineUpsertOne) UpdateNewValues() *ContentEngineUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(contentengine.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ContentEngine.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ContentEngineUpsertOne) Ignore() *ContentEngineUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ContentEngineUpsertOne) DoNothing() *ContentEngineUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ContentEngineCreate.OnConflict
// documentation for more info.
func (u *ContentEngineUpsertOne) Update(set func(*ContentEngineUpsert)) *ContentEngineUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ContentEngineUpsert{UpdateSet: update})
	}))
	return u
}

// SetKey sets the "key" field.
func (u *ContentEngineUpsertOne) SetKey(v string) *ContentEngineUpsertOne {
	return u.Update(func(s *ContentEngineUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *ContentEngineUpsertOne) UpdateKey() *ContentEngineUpsertOne {
	return u.Update(func(s *ContentEngineUpsert) {
		s.UpdateKey()
	})
}

// SetName sets the "name" field.
func (u *ContentEngineUpsertOne) SetName(v string) *ContentEngineUpsertOne {
	return u.Update(func(s *ContentEngineUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ContentEngineUpsertOne) UpdateName() *ContentEngineUpsertOne {
	return u.Update(func(s *ContentEngineUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *ContentEngineUpsertOne) SetDescription(v string) *ContentEngineUpsertOne {
	return u.Update(func(s *ContentEngineUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ContentEngineUpsertOne) UpdateDescription() *ContentEngineUpsertOne {
	return u.Update(func(s *ContentEngineUpsert) {
		s.UpdateDescription()
	})
}

// SetConfig sets the "config" field.
func (u *ContentEngineUpsertOne) SetConfig(v map[string]interface{}) *ContentEngineUpsertOne {
	return u.Update(func(s *ContentEngineUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *ContentEngineUpsertOne) UpdateConfig() *ContentEngineUpsertOne {
	return u.Update(func(s *ContentEngineUpsert) {
		s.UpdateConfig()
	})
}

// SetIsEnabled sets the "is_enabled" field.
func (u *ContentEngineUpsertOne) SetIsEnabled(v bool) *ContentEngineUpsertOne {
	return u.Update(func(s *ContentEngineUpsert) {
		s.SetIsEnabled(v)
	})
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *ContentEngineUpsertOne) UpdateIsEnabled() *ContentEngineUpsertOne {
	return u.Update(func(s *ContentEngineUpsert) {
		s.UpdateIsEnabled()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *ContentEngineUpsertOne) SetSortOrder(v int) *ContentEngineUpsertOne {
	return u.Update(func(s *ContentEngineUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ContentEngineUpsertOne) AddSortOrder(v int) *ContentEngineUpsertOne {
	return u.Update(func(s *ContentEngineUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ContentEngineUpsertOne) UpdateSortOrder() *ContentEngineUpsertOne {
	return u.Update(func(s *ContentEngineUpsert) {
		s.UpdateSortOrder()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ContentEngineUpsertOne) SetCreatedAt(v time.Time) *ContentEngineUpsertOne {
	return u.Update(func(s *ContentEngineUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ContentEngineUpsertOne) UpdateCreatedAt() *ContentEngineUpsertOne {
	return u.Update(func(s *ContentEngineUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ContentEngineUpsertOne) SetUpdatedAt(v time.Time) *ContentEngineUpsertOne {
	return u.Update(func(s *ContentEngineUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ContentEngineUpsertOne) UpdateUpdatedAt() *ContentEngineUpsertOne {
	return u.Update(func(s *ContentEngineUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ContentEngineUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for ContentEngineCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ContentEngineUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ContentEngineUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("db: ContentEngineUpsertOne.ID is not supported by MySQL driver. Use ContentEngineUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ContentEngineUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ContentEngineCreateBulk is the builder for creating many ContentEngine entities in bulk.
type ContentEngineCreateBulk struct {
	config
	err      error
	builders []*ContentEngineCreate
	conflict []sql.ConflictOption
}

// Save creates the ContentEngine entities in the database.
func (_c *ContentEngineCreateBulk) Save(ctx context.Context) ([]*ContentEngine, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ContentEngine, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ContentEngineMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ContentEngineCreateBulk) SaveX(ctx context.Context) []*ContentEngine {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContentEngineCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContentEngineCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ContentEngine.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ContentEngineUpsert) {
//			SetKey(v+v).
//		}).
//		Exec(ctx)
func (_c *ContentEngineCreateBulk) OnConflict(opts ...sql.ConflictOption) *ContentEngineUpsertBulk {
	_c.conflict = opts
	return &ContentEngineUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ContentEngine.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ContentEngineCreateBulk) OnConflictColumns(columns ...string) *ContentEngineUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ContentEngineUpsertBulk{
		create: _c,
	}
}

// ContentEngineUpsertBulk is the builder for "upsert"-ing
// a bulk of ContentEngine nodes.
type ContentEngineUpsertBulk struct {
	create *ContentEngineCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ContentEngine.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(contentengine.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ContentEngineUpsertBulk) UpdateNewValues() *ContentEngineUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(contentengine.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ContentEngine.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ContentEngineUpsertBulk) Ignore() *ContentEngineUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ContentEngineUpsertBulk) DoNothing() *ContentEngineUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ContentEngineCreateBulk.OnConflict
// documentation for more info.
func (u *ContentEngineUpsertBulk) Update(set func(*ContentEngineUpsert)) *ContentEngineUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ContentEngineUpsert{UpdateSet: update})
	}))
	return u
}

// SetKey sets the "key" field.
func (u *ContentEngineUpsertBulk) SetKey(v string) *ContentEngineUpsertBulk {
	return u.Update(func(s *ContentEngineUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *ContentEngineUpsertBulk) UpdateKey() *ContentEngineUpsertBulk {
	return u.Update(func(s *ContentEngineUpsert) {
		s.UpdateKey()
	})
}

// SetName sets the "name" field.
func (u *ContentEngineUpsertBulk) SetName(v string) *ContentEngineUpsertBulk {
	return u.Update(func(s *ContentEngineUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ContentEngineUpsertBulk) UpdateName() *ContentEngineUpsertBulk {
	return u.Update(func(s *ContentEngineUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *ContentEngineUpsertBulk) SetDescription(v string) *ContentEngineUpsertBulk {
	return u.Update(func(s *ContentEngineUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ContentEngineUpsertBulk) UpdateDescription() *ContentEngineUpsertBulk {
	return u.Update(func(s *ContentEngineUpsert) {
		s.UpdateDescription()
	})
}

// SetConfig sets the "config" field.
func (u *ContentEngineUpsertBulk) SetConfig(v map[string]interface{}) *ContentEngineUpsertBulk {
	return u.Update(func(s *ContentEngineUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *ContentEngineUpsertBulk) UpdateConfig() *ContentEngineUpsertBulk {
	return u.Update(func(s *ContentEngineUpsert) {
		s.UpdateConfig()
	})
}

// SetIsEnabled sets the "is_enabled" field.
func (u *ContentEngineUpsertBulk) SetIsEnabled(v bool) *ContentEngineUpsertBulk {
	return u.Update(func(s *ContentEngineUpsert) {
		s.SetIsEnabled(v)
	})
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *ContentEngineUpsertBulk) UpdateIsEnabled() *ContentEngineUpsertBulk {
	return u.Update(func(s *ContentEngineUpsert) {
		s.UpdateIsEnabled()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *ContentEngineUpsertBulk) SetSortOrder(v int) *ContentEngineUpsertBulk {
	return u.Update(func(s *ContentEngineUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ContentEngineUpsertBulk) AddSortOrder(v int) *ContentEngineUpsertBulk {
	return u.Update(func(s *ContentEngineUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ContentEngineUpsertBulk) UpdateSortOrder() *ContentEngineUpsertBulk {
	return u.Update(func(s *ContentEngineUpsert) {
		s.UpdateSortOrder()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ContentEngineUpsertBulk) SetCreatedAt(v time.Time) *ContentEngineUpsertBulk {
	return u.Update(func(s *ContentEngineUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ContentEngineUpsertBulk) UpdateCreatedAt() *ContentEngineUpsertBulk {
	return u.Update(func(s *ContentEngineUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ContentEngineUpsertBulk) SetUpdatedAt(v time.Time) *ContentEngineUpsertBulk {
	return u.Update(func(s *ContentEngineUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ContentEngineUpsertBulk) UpdateUpdatedAt() *ContentEngineUpsertBulk {
	return u.Update(func(s *ContentEngineUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ContentEngineUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("db: OnConflict was set for builder %d. Set it on the ContentEngineCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for ContentEngineCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ContentEngineUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
