// Code generated by ent, DO NOT EDIT.

package db

import (
	"bridal/backend/db/generationmodelinvocation"
	"bridal/backend/ent/types"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// GenerationModelInvocation is the model entity for the GenerationModelInvocation schema.
type GenerationModelInvocation struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID uuid.UUID `json:"task_id,omitempty"`
	// GenerationImageID holds the value of the "generation_image_id" field.
	GenerationImageID string `json:"generation_image_id,omitempty"`
	// ImageNumber holds the value of the "image_number" field.
	ImageNumber int `json:"image_number,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// UserEmail holds the value of the "user_email" field.
	UserEmail string `json:"user_email,omitempty"`
	// UserRole holds the value of the "user_role" field.
	UserRole string `json:"user_role,omitempty"`
	// ChannelID holds the value of the "channel_id" field.
	ChannelID uuid.UUID `json:"channel_id,omitempty"`
	// ChannelName holds the value of the "channel_name" field.
	ChannelName string `json:"channel_name,omitempty"`
	// APIBaseURL holds the value of the "api_base_url" field.
	APIBaseURL string `json:"api_base_url,omitempty"`
	// Protocol holds the value of the "protocol" field.
	Protocol string `json:"protocol,omitempty"`
	// ModelID holds the value of the "model_id" field.
	ModelID string `json:"model_id,omitempty"`
	// CandidateIndex holds the value of the "candidate_index" field.
	CandidateIndex int `json:"candidate_index,omitempty"`
	// CandidateCount holds the value of the "candidate_count" field.
	CandidateCount int `json:"candidate_count,omitempty"`
	// AttemptNumber holds the value of the "attempt_number" field.
	AttemptNumber int `json:"attempt_number,omitempty"`
	// AttemptBudget holds the value of the "attempt_budget" field.
	AttemptBudget int `json:"attempt_budget,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Prompt holds the value of the "prompt" field.
	Prompt string `json:"prompt,omitempty"`
	// PromptHash holds the value of the "prompt_hash" field.
	PromptHash string `json:"prompt_hash,omitempty"`
	// ReferenceImages holds the value of the "reference_images" field.
	ReferenceImages []types.ModelInvocationReference `json:"reference_images,omitempty"`
	// Size holds the value of the "size" field.
	Size string `json:"size,omitempty"`
	// Quality holds the value of the "quality" field.
	Quality string `json:"quality,omitempty"`
	// HTTPStatus holds the value of the "http_status" field.
	HTTPStatus int `json:"http_status,omitempty"`
	// LatencyMs holds the value of the "latency_ms" field.
	LatencyMs int `json:"latency_ms,omitempty"`
	// ResponseImageCount holds the value of the "response_image_count" field.
	ResponseImageCount int `json:"response_image_count,omitempty"`
	// Error holds the value of the "error" field.
	Error string `json:"error,omitempty"`
	// RequestedAt holds the value of the "requested_at" field.
	RequestedAt time.Time `json:"requested_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt  time.Time `json:"completed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GenerationModelInvocation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case generationmodelinvocation.FieldReferenceImages:
			values[i] = new([]byte)
		case generationmodelinvocation.FieldImageNumber, generationmodelinvocation.FieldCandidateIndex, generationmodelinvocation.FieldCandidateCount, generationmodelinvocation.FieldAttemptNumber, generationmodelinvocation.FieldAttemptBudget, generationmodelinvocation.FieldHTTPStatus, generationmodelinvocation.FieldLatencyMs, generationmodelinvocation.FieldResponseImageCount:
			values[i] = new(sql.NullInt64)
		case generationmodelinvocation.FieldGenerationImageID, generationmodelinvocation.FieldUsername, generationmodelinvocation.FieldUserEmail, generationmodelinvocation.FieldUserRole, generationmodelinvocation.FieldChannelName, generationmodelinvocation.FieldAPIBaseURL, generationmodelinvocation.FieldProtocol, generationmodelinvocation.FieldModelID, generationmodelinvocation.FieldStatus, generationmodelinvocation.FieldPrompt, generationmodelinvocation.FieldPromptHash, generationmodelinvocation.FieldSize, generationmodelinvocation.FieldQuality, generationmodelinvocation.FieldError:
			values[i] = new(sql.NullString)
		case generationmodelinvocation.FieldRequestedAt, generationmodelinvocation.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		case generationmodelinvocation.FieldID, generationmodelinvocation.FieldTaskID, generationmodelinvocation.FieldUserID, generationmodelinvocation.FieldChannelID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GenerationModelInvocation fields.
func (_m *GenerationModelInvocation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case generationmodelinvocation.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case generationmodelinvocation.FieldTaskID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value != nil {
				_m.TaskID = *value
			}
		case generationmodelinvocation.FieldGenerationImageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field generation_image_id", values[i])
			} else if value.Valid {
				_m.GenerationImageID = value.String
			}
		case generationmodelinvocation.FieldImageNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field image_number", values[i])
			} else if value.Valid {
				_m.ImageNumber = int(value.Int64)
			}
		case generationmodelinvocation.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case generationmodelinvocation.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case generationmodelinvocation.FieldUserEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_email", values[i])
			} else if value.Valid {
				_m.UserEmail = value.String
			}
		case generationmodelinvocation.FieldUserRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_role", values[i])
			} else if value.Valid {
				_m.UserRole = value.String
			}
		case generationmodelinvocation.FieldChannelID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value != nil {
				_m.ChannelID = *value
			}
		case generationmodelinvocation.FieldChannelName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel_name", values[i])
			} else if value.Valid {
				_m.ChannelName = value.String
			}
		case generationmodelinvocation.FieldAPIBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_base_url", values[i])
			} else if value.Valid {
				_m.APIBaseURL = value.String
			}
		case generationmodelinvocation.FieldProtocol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field protocol", values[i])
			} else if value.Valid {
				_m.Protocol = value.String
			}
		case generationmodelinvocation.FieldModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = value.String
			}
		case generationmodelinvocation.FieldCandidateIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field candidate_index", values[i])
			} else if value.Valid {
				_m.CandidateIndex = int(value.Int64)
			}
		case generationmodelinvocation.FieldCandidateCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field candidate_count", values[i])
			} else if value.Valid {
				_m.CandidateCount = int(value.Int64)
			}
		case generationmodelinvocation.FieldAttemptNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_number", values[i])
			} else if value.Valid {
				_m.AttemptNumber = int(value.Int64)
			}
		case generationmodelinvocation.FieldAttemptBudget:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_budget", values[i])
			} else if value.Valid {
				_m.AttemptBudget = int(value.Int64)
			}
		case generationmodelinvocation.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case generationmodelinvocation.FieldPrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt", values[i])
			} else if value.Valid {
				_m.Prompt = value.String
			}
		case generationmodelinvocation.FieldPromptHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_hash", values[i])
			} else if value.Valid {
				_m.PromptHash = value.String
			}
		case generationmodelinvocation.FieldReferenceImages:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field reference_images", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ReferenceImages); err != nil {
					return fmt.Errorf("unmarshal field reference_images: %w", err)
				}
			}
		case generationmodelinvocation.FieldSize:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				_m.Size = value.String
			}
		case generationmodelinvocation.FieldQuality:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quality", values[i])
			} else if value.Valid {
				_m.Quality = value.String
			}
		case generationmodelinvocation.FieldHTTPStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field http_status", values[i])
			} else if value.Valid {
				_m.HTTPStatus = int(value.Int64)
			}
		case generationmodelinvocation.FieldLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field latency_ms", values[i])
			} else if value.Valid {
				_m.LatencyMs = int(value.Int64)
			}
		case generationmodelinvocation.FieldResponseImageCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field response_image_count", values[i])
			} else if value.Valid {
				_m.ResponseImageCount = int(value.Int64)
			}
		case generationmodelinvocation.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = value.String
			}
		case generationmodelinvocation.FieldRequestedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field requested_at", values[i])
			} else if value.Valid {
				_m.RequestedAt = value.Time
			}
		case generationmodelinvocation.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GenerationModelInvocation.
// This includes values selected through modifiers, order, etc.
func (_m *GenerationModelInvocation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GenerationModelInvocation.
// Note that you need to call GenerationModelInvocation.Unwrap() before calling this method if this GenerationModelInvocation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GenerationModelInvocation) Update() *GenerationModelInvocationUpdateOne {
	return NewGenerationModelInvocationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GenerationModelInvocation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GenerationModelInvocation) Unwrap() *GenerationModelInvocation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("db: GenerationModelInvocation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GenerationModelInvocation) String() string {
	var builder strings.Builder
	builder.WriteString("GenerationModelInvocation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("task_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaskID))
	builder.WriteString(", ")
	builder.WriteString("generation_image_id=")
	builder.WriteString(_m.GenerationImageID)
	builder.WriteString(", ")
	builder.WriteString("image_number=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImageNumber))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("user_email=")
	builder.WriteString(_m.UserEmail)
	builder.WriteString(", ")
	builder.WriteString("user_role=")
	builder.WriteString(_m.UserRole)
	builder.WriteString(", ")
	builder.WriteString("channel_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChannelID))
	builder.WriteString(", ")
	builder.WriteString("channel_name=")
	builder.WriteString(_m.ChannelName)
	builder.WriteString(", ")
	builder.WriteString("api_base_url=")
	builder.WriteString(_m.APIBaseURL)
	builder.WriteString(", ")
	builder.WriteString("protocol=")
	builder.WriteString(_m.Protocol)
	builder.WriteString(", ")
	builder.WriteString("model_id=")
	builder.WriteString(_m.ModelID)
	builder.WriteString(", ")
	builder.WriteString("candidate_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.CandidateIndex))
	builder.WriteString(", ")
	builder.WriteString("candidate_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.CandidateCount))
	builder.WriteString(", ")
	builder.WriteString("attempt_number=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptNumber))
	builder.WriteString(", ")
	builder.WriteString("attempt_budget=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptBudget))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("prompt=")
	builder.WriteString(_m.Prompt)
	builder.WriteString(", ")
	builder.WriteString("prompt_hash=")
	builder.WriteString(_m.PromptHash)
	builder.WriteString(", ")
	builder.WriteString("reference_images=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReferenceImages))
	builder.WriteString(", ")
	builder.WriteString("size=")
	builder.WriteString(_m.Size)
	builder.WriteString(", ")
	builder.WriteString("quality=")
	builder.WriteString(_m.Quality)
	builder.WriteString(", ")
	builder.WriteString("http_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.HTTPStatus))
	builder.WriteString(", ")
	builder.WriteString("latency_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.LatencyMs))
	builder.WriteString(", ")
	builder.WriteString("response_image_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseImageCount))
	builder.WriteString(", ")
	builder.WriteString("error=")
	builder.WriteString(_m.Error)
	builder.WriteString(", ")
	builder.WriteString("requested_at=")
	builder.WriteString(_m.RequestedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("completed_at=")
	builder.WriteString(_m.CompletedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GenerationModelInvocations is a parsable slice of GenerationModelInvocation.
type GenerationModelInvocations []*GenerationModelInvocation
