// Code generated by ent, DO NOT EDIT.

package db

import (
	"bridal/backend/db/generationimage"
	"bridal/backend/db/generationtask"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// GenerationImageCreate is the builder for creating a GenerationImage entity.
type GenerationImageCreate struct {
	config
	mutation *GenerationImageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTaskID sets the "task_id" field.
func (_c *GenerationImageCreate) SetTaskID(v uuid.UUID) *GenerationImageCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *GenerationImageCreate) SetName(v string) *GenerationImageCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *GenerationImageCreate) SetNillableName(v *string) *GenerationImageCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *GenerationImageCreate) SetURL(v string) *GenerationImageCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_c *GenerationImageCreate) SetNillableURL(v *string) *GenerationImageCreate {
	if v != nil {
		_c.SetURL(*v)
	}
	return _c
}

// SetDownloadURL sets the "download_url" field.
func (_c *GenerationImageCreate) SetDownloadURL(v string) *GenerationImageCreate {
	_c.mutation.SetDownloadURL(v)
	return _c
}

// SetNillableDownloadURL sets the "download_url" field if the given value is not nil.
func (_c *GenerationImageCreate) SetNillableDownloadURL(v *string) *GenerationImageCreate {
	if v != nil {
		_c.SetDownloadURL(*v)
	}
	return _c
}

// SetThumbURL sets the "thumb_url" field.
func (_c *GenerationImageCreate) SetThumbURL(v string) *GenerationImageCreate {
	_c.mutation.SetThumbURL(v)
	return _c
}

// SetNillableThumbURL sets the "thumb_url" field if the given value is not nil.
func (_c *GenerationImageCreate) SetNillableThumbURL(v *string) *GenerationImageCreate {
	if v != nil {
		_c.SetThumbURL(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *GenerationImageCreate) SetSource(v string) *GenerationImageCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *GenerationImageCreate) SetNillableSource(v *string) *GenerationImageCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetImageNumber sets the "image_number" field.
func (_c *GenerationImageCreate) SetImageNumber(v int) *GenerationImageCreate {
	_c.mutation.SetImageNumber(v)
	return _c
}

// SetNillableImageNumber sets the "image_number" field if the given value is not nil.
func (_c *GenerationImageCreate) SetNillableImageNumber(v *int) *GenerationImageCreate {
	if v != nil {
		_c.SetImageNumber(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *GenerationImageCreate) SetStatus(v string) *GenerationImageCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *GenerationImageCreate) SetNillableStatus(v *string) *GenerationImageCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *GenerationImageCreate) SetError(v string) *GenerationImageCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *GenerationImageCreate) SetNillableError(v *string) *GenerationImageCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetLatencyMs sets the "latency_ms" field.
func (_c *GenerationImageCreate) SetLatencyMs(v int) *GenerationImageCreate {
	_c.mutation.SetLatencyMs(v)
	return _c
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_c *GenerationImageCreate) SetNillableLatencyMs(v *int) *GenerationImageCreate {
	if v != nil {
		_c.SetLatencyMs(*v)
	}
	return _c
}

// SetDeleted sets the "deleted" field.
func (_c *GenerationImageCreate) SetDeleted(v bool) *GenerationImageCreate {
	_c.mutation.SetDeleted(v)
	return _c
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (_c *GenerationImageCreate) SetNillableDeleted(v *bool) *GenerationImageCreate {
	if v != nil {
		_c.SetDeleted(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *GenerationImageCreate) SetDeletedAt(v time.Time) *GenerationImageCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *GenerationImageCreate) SetNillableDeletedAt(v *time.Time) *GenerationImageCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GenerationImageCreate) SetCreatedAt(v time.Time) *GenerationImageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GenerationImageCreate) SetNillableCreatedAt(v *time.Time) *GenerationImageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GenerationImageCreate) SetID(v string) *GenerationImageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTask sets the "task" edge to the GenerationTask entity.
func (_c *GenerationImageCreate) SetTask(v *GenerationTask) *GenerationImageCreate {
	return _c.SetTaskID(v.ID)
}

// Mutation returns the GenerationImageMutation object of the builder.
func (_c *GenerationImageCreate) Mutation() *GenerationImageMutation {
	return _c.mutation
}

// Save creates the GenerationImage in the database.
func (_c *GenerationImageCreate) Save(ctx context.Context) (*GenerationImage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GenerationImageCreate) SaveX(ctx context.Context) *GenerationImage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GenerationImageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GenerationImageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GenerationImageCreate) defaults() {
	if _, ok := _c.mutation.Name(); !ok {
		v := generationimage.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.URL(); !ok {
		v := generationimage.DefaultURL
		_c.mutation.SetURL(v)
	}
	if _, ok := _c.mutation.DownloadURL(); !ok {
		v := generationimage.DefaultDownloadURL
		_c.mutation.SetDownloadURL(v)
	}
	if _, ok := _c.mutation.ThumbURL(); !ok {
		v := generationimage.DefaultThumbURL
		_c.mutation.SetThumbURL(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := generationimage.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.ImageNumber(); !ok {
		v := generationimage.DefaultImageNumber
		_c.mutation.SetImageNumber(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := generationimage.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Error(); !ok {
		v := generationimage.DefaultError
		_c.mutation.SetError(v)
	}
	if _, ok := _c.mutation.LatencyMs(); !ok {
		v := generationimage.DefaultLatencyMs
		_c.mutation.SetLatencyMs(v)
	}
	if _, ok := _c.mutation.Deleted(); !ok {
		v := generationimage.DefaultDeleted
		_c.mutation.SetDeleted(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := generationimage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GenerationImageCreate) check() error {
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`db: missing required field "GenerationImage.task_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`db: missing required field "GenerationImage.name"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`db: missing required field "GenerationImage.url"`)}
	}
	if _, ok := _c.mutation.DownloadURL(); !ok {
		return &ValidationError{Name: "download_url", err: errors.New(`db: missing required field "GenerationImage.download_url"`)}
	}
	if _, ok := _c.mutation.ThumbURL(); !ok {
		return &ValidationError{Name: "thumb_url", err: errors.New(`db: missing required field "GenerationImage.thumb_url"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`db: missing required field "GenerationImage.source"`)}
	}
	if _, ok := _c.mutation.ImageNumber(); !ok {
		return &ValidationError{Name: "image_number", err: errors.New(`db: missing required field "GenerationImage.image_number"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`db: missing required field "GenerationImage.status"`)}
	}
	if _, ok := _c.mutation.Error(); !ok {
		return &ValidationError{Name: "error", err: errors.New(`db: missing required field "GenerationImage.error"`)}
	}
	if _, ok := _c.mutation.LatencyMs(); !ok {
		return &ValidationError{Name: "latency_ms", err: errors.New(`db: missing required field "GenerationImage.latency_ms"`)}
	}
	if _, ok := _c.mutation.Deleted(); !ok {
		return &ValidationError{Name: "deleted", err: errors.New(`db: missing required field "GenerationImage.deleted"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`db: missing required field "GenerationImage.created_at"`)}
	}
	if len(_c.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`db: missing required edge "GenerationImage.task"`)}
	}
	return nil
}

func (_c *GenerationImageCreate) sqlSave(ctx context.Context) (*GenerationImage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected GenerationImage.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GenerationImageCreate) createSpec() (*GenerationImage, *sqlgraph.CreateSpec) {
	var (
		_node = &GenerationImage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(generationimage.Table, sqlgraph.NewFieldSpec(generationimage.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(generationimage.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(generationimage.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.DownloadURL(); ok {
		_spec.SetField(generationimage.FieldDownloadURL, field.TypeString, value)
		_node.DownloadURL = value
	}
	if value, ok := _c.mutation.ThumbURL(); ok {
		_spec.SetField(generationimage.FieldThumbURL, field.TypeString, value)
		_node.ThumbURL = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(generationimage.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.ImageNumber(); ok {
		_spec.SetField(generationimage.FieldImageNumber, field.TypeInt, value)
		_node.ImageNumber = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(generationimage.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(generationimage.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := _c.mutation.LatencyMs(); ok {
		_spec.SetField(generationimage.FieldLatencyMs, field.TypeInt, value)
		_node.LatencyMs = value
	}
	if value, ok := _c.mutation.Deleted(); ok {
		_spec.SetField(generationimage.FieldDeleted, field.TypeBool, value)
		_node.Deleted = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(generationimage.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(generationimage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   generationimage.TaskTable,
			Columns: []string{generationimage.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(generationtask.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GenerationImage.Create().
//		SetTaskID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GenerationImageUpsert) {
//			SetTaskID(v+v).
//		}).
//		Exec(ctx)
func (_c *GenerationImageCreate) OnConflict(opts ...sql.ConflictOption) *GenerationImageUpsertOne {
	_c.conflict = opts
	return &GenerationImageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GenerationImage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GenerationImageCreate) OnConflictColumns(columns ...string) *GenerationImageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GenerationImageUpsertOne{
		create: _c,
	}
}

type (
	// GenerationImageUpsertOne is the builder for "upsert"-ing
	//  one GenerationImage node.
	GenerationImageUpsertOne struct {
		create *GenerationImageCreate
	}

	// GenerationImageUpsert is the "OnConflict" setter.
	GenerationImageUpsert struct {
		*sql.UpdateSet
	}
)

// SetTaskID sets the "task_id" field.
func (u *GenerationImageUpsert) SetTaskID(v uuid.UUID) *GenerationImageUpsert {
	u.Set(generationimage.FieldTaskID, v)
	return u
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *GenerationImageUpsert) UpdateTaskID() *GenerationImageUpsert {
	u.SetExcluded(generationimage.FieldTaskID)
	return u
}

// SetName sets the "name" field.
func (u *GenerationImageUpsert) SetName(v string) *GenerationImageUpsert {
	u.Set(generationimage.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *GenerationImageUpsert) UpdateName() *GenerationImageUpsert {
	u.SetExcluded(generationimage.FieldName)
	return u
}

// SetURL sets the "url" field.
func (u *GenerationImageUpsert) SetURL(v string) *GenerationImageUpsert {
	u.Set(generationimage.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *GenerationImageUpsert) UpdateURL() *GenerationImageUpsert {
	u.SetExcluded(generationimage.FieldURL)
	return u
}

// SetDownloadURL sets the "download_url" field.
func (u *GenerationImageUpsert) SetDownloadURL(v string) *GenerationImageUpsert {
	u.Set(generationimage.FieldDownloadURL, v)
	return u
}

// UpdateDownloadURL sets the "download_url" field to the value that was provided on create.
func (u *GenerationImageUpsert) UpdateDownloadURL() *GenerationImageUpsert {
	u.SetExcluded(generationimage.FieldDownloadURL)
	return u
}

// SetThumbURL sets the "thumb_url" field.
func (u *GenerationImageUpsert) SetThumbURL(v string) *GenerationImageUpsert {
	u.Set(generationimage.FieldThumbURL, v)
	return u
}

// UpdateThumbURL sets the "thumb_url" field to the value that was provided on create.
func (u *GenerationImageUpsert) UpdateThumbURL() *GenerationImageUpsert {
	u.SetExcluded(generationimage.FieldThumbURL)
	return u
}

// SetSource sets the "source" field.
func (u *GenerationImageUpsert) SetSource(v string) *GenerationImageUpsert {
	u.Set(generationimage.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *GenerationImageUpsert) UpdateSource() *GenerationImageUpsert {
	u.SetExcluded(generationimage.FieldSource)
	return u
}

// SetImageNumber sets the "image_number" field.
func (u *GenerationImageUpsert) SetImageNumber(v int) *GenerationImageUpsert {
	u.Set(generationimage.FieldImageNumber, v)
	return u
}

// UpdateImageNumber sets the "image_number" field to the value that was provided on create.
func (u *GenerationImageUpsert) UpdateImageNumber() *GenerationImageUpsert {
	u.SetExcluded(generationimage.FieldImageNumber)
	return u
}

// AddImageNumber adds v to the "image_number" field.
func (u *GenerationImageUpsert) AddImageNumber(v int) *GenerationImageUpsert {
	u.Add(generationimage.FieldImageNumber, v)
	return u
}

// SetStatus sets the "status" field.
func (u *GenerationImageUpsert) SetStatus(v string) *GenerationImageUpsert {
	u.Set(generationimage.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GenerationImageUpsert) UpdateStatus() *GenerationImageUpsert {
	u.SetExcluded(generationimage.FieldStatus)
	return u
}

// SetError sets the "error" field.
func (u *GenerationImageUpsert) SetError(v string) *GenerationImageUpsert {
	u.Set(generationimage.FieldError, v)
	return u
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *GenerationImageUpsert) UpdateError() *GenerationImageUpsert {
	u.SetExcluded(generationimage.FieldError)
	return u
}

// SetLatencyMs sets the "latency_ms" field.
func (u *GenerationImageUpsert) SetLatencyMs(v int) *GenerationImageUpsert {
	u.Set(generationimage.FieldLatencyMs, v)
	return u
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *GenerationImageUpsert) UpdateLatencyMs() *GenerationImageUpsert {
	u.SetExcluded(generationimage.FieldLatencyMs)
	return u
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *GenerationImageUpsert) AddLatencyMs(v int) *GenerationImageUpsert {
	u.Add(generationimage.FieldLatencyMs, v)
	return u
}

// SetDeleted sets the "deleted" field.
func (u *GenerationImageUpsert) SetDeleted(v bool) *GenerationImageUpsert {
	u.Set(generationimage.FieldDeleted, v)
	return u
}

// UpdateDeleted sets the "deleted" field to the value that was provided on create.
func (u *GenerationImageUpsert) UpdateDeleted() *GenerationImageUpsert {
	u.SetExcluded(generationimage.FieldDeleted)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *GenerationImageUpsert) SetDeletedAt(v time.Time) *GenerationImageUpsert {
	u.Set(generationimage.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *GenerationImageUpsert) UpdateDeletedAt() *GenerationImageUpsert {
	u.SetExcluded(generationimage.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *GenerationImageUpsert) ClearDeletedAt() *GenerationImageUpsert {
	u.SetNull(generationimage.FieldDeletedAt)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *GenerationImageUpsert) SetCreatedAt(v time.Time) *GenerationImageUpsert {
	u.Set(generationimage.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *GenerationImageUpsert) UpdateCreatedAt() *GenerationImageUpsert {
	u.SetExcluded(generationimage.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.GenerationImage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(generationimage.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GenerationImageUpsertOne) UpdateNewValues() *GenerationImageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(generationimage.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GenerationImage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GenerationImageUpsertOne) Ignore() *GenerationImageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GenerationImageUpsertOne) DoNothing() *GenerationImageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GenerationImageCreate.OnConflict
// documentation for more info.
func (u *GenerationImageUpsertOne) Update(set func(*GenerationImageUpsert)) *GenerationImageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GenerationImageUpsert{UpdateSet: update})
	}))
	return u
}

// SetTaskID sets the "task_id" field.
func (u *GenerationImageUpsertOne) SetTaskID(v uuid.UUID) *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *GenerationImageUpsertOne) UpdateTaskID() *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateTaskID()
	})
}

// SetName sets the "name" field.
func (u *GenerationImageUpsertOne) SetName(v string) *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *GenerationImageUpsertOne) UpdateName() *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateName()
	})
}

// SetURL sets the "url" field.
func (u *GenerationImageUpsertOne) SetURL(v string) *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *GenerationImageUpsertOne) UpdateURL() *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateURL()
	})
}

// SetDownloadURL sets the "download_url" field.
func (u *GenerationImageUpsertOne) SetDownloadURL(v string) *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetDownloadURL(v)
	})
}

// UpdateDownloadURL sets the "download_url" field to the value that was provided on create.
func (u *GenerationImageUpsertOne) UpdateDownloadURL() *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateDownloadURL()
	})
}

// SetThumbURL sets the "thumb_url" field.
func (u *GenerationImageUpsertOne) SetThumbURL(v string) *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetThumbURL(v)
	})
}

// UpdateThumbURL sets the "thumb_url" field to the value that was provided on create.
func (u *GenerationImageUpsertOne) UpdateThumbURL() *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateThumbURL()
	})
}

// SetSource sets the "source" field.
func (u *GenerationImageUpsertOne) SetSource(v string) *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *GenerationImageUpsertOne) UpdateSource() *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateSource()
	})
}

// SetImageNumber sets the "image_number" field.
func (u *GenerationImageUpsertOne) SetImageNumber(v int) *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetImageNumber(v)
	})
}

// AddImageNumber adds v to the "image_number" field.
func (u *GenerationImageUpsertOne) AddImageNumber(v int) *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.AddImageNumber(v)
	})
}

// UpdateImageNumber sets the "image_number" field to the value that was provided on create.
func (u *GenerationImageUpsertOne) UpdateImageNumber() *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateImageNumber()
	})
}

// SetStatus sets the "status" field.
func (u *GenerationImageUpsertOne) SetStatus(v string) *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GenerationImageUpsertOne) UpdateStatus() *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateStatus()
	})
}

// SetError sets the "error" field.
func (u *GenerationImageUpsertOne) SetError(v string) *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *GenerationImageUpsertOne) UpdateError() *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateError()
	})
}

// SetLatencyMs sets the "latency_ms" field.
func (u *GenerationImageUpsertOne) SetLatencyMs(v int) *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetLatencyMs(v)
	})
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *GenerationImageUpsertOne) AddLatencyMs(v int) *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.AddLatencyMs(v)
	})
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *GenerationImageUpsertOne) UpdateLatencyMs() *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateLatencyMs()
	})
}

// SetDeleted sets the "deleted" field.
func (u *GenerationImageUpsertOne) SetDeleted(v bool) *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetDeleted(v)
	})
}

// UpdateDeleted sets the "deleted" field to the value that was provided on create.
func (u *GenerationImageUpsertOne) UpdateDeleted() *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateDeleted()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *GenerationImageUpsertOne) SetDeletedAt(v time.Time) *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *GenerationImageUpsertOne) UpdateDeletedAt() *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *GenerationImageUpsertOne) ClearDeletedAt() *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *GenerationImageUpsertOne) SetCreatedAt(v time.Time) *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *GenerationImageUpsertOne) UpdateCreatedAt() *GenerationImageUpsertOne {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *GenerationImageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for GenerationImageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GenerationImageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GenerationImageUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("db: GenerationImageUpsertOne.ID is not supported by MySQL driver. Use GenerationImageUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GenerationImageUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GenerationImageCreateBulk is the builder for creating many GenerationImage entities in bulk.
type GenerationImageCreateBulk struct {
	config
	err      error
	builders []*GenerationImageCreate
	conflict []sql.ConflictOption
}

// Save creates the GenerationImage entities in the database.
func (_c *GenerationImageCreateBulk) Save(ctx context.Context) ([]*GenerationImage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GenerationImage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GenerationImageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GenerationImageCreateBulk) SaveX(ctx context.Context) []*GenerationImage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GenerationImageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GenerationImageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GenerationImage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GenerationImageUpsert) {
//			SetTaskID(v+v).
//		}).
//		Exec(ctx)
func (_c *GenerationImageCreateBulk) OnConflict(opts ...sql.ConflictOption) *GenerationImageUpsertBulk {
	_c.conflict = opts
	return &GenerationImageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GenerationImage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GenerationImageCreateBulk) OnConflictColumns(columns ...string) *GenerationImageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GenerationImageUpsertBulk{
		create: _c,
	}
}

// GenerationImageUpsertBulk is the builder for "upsert"-ing
// a bulk of GenerationImage nodes.
type GenerationImageUpsertBulk struct {
	create *GenerationImageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GenerationImage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(generationimage.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GenerationImageUpsertBulk) UpdateNewValues() *GenerationImageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(generationimage.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GenerationImage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GenerationImageUpsertBulk) Ignore() *GenerationImageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GenerationImageUpsertBulk) DoNothing() *GenerationImageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GenerationImageCreateBulk.OnConflict
// documentation for more info.
func (u *GenerationImageUpsertBulk) Update(set func(*GenerationImageUpsert)) *GenerationImageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GenerationImageUpsert{UpdateSet: update})
	}))
	return u
}

// SetTaskID sets the "task_id" field.
func (u *GenerationImageUpsertBulk) SetTaskID(v uuid.UUID) *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *GenerationImageUpsertBulk) UpdateTaskID() *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateTaskID()
	})
}

// SetName sets the "name" field.
func (u *GenerationImageUpsertBulk) SetName(v string) *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *GenerationImageUpsertBulk) UpdateName() *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateName()
	})
}

// SetURL sets the "url" field.
func (u *GenerationImageUpsertBulk) SetURL(v string) *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *GenerationImageUpsertBulk) UpdateURL() *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateURL()
	})
}

// SetDownloadURL sets the "download_url" field.
func (u *GenerationImageUpsertBulk) SetDownloadURL(v string) *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetDownloadURL(v)
	})
}

// UpdateDownloadURL sets the "download_url" field to the value that was provided on create.
func (u *GenerationImageUpsertBulk) UpdateDownloadURL() *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateDownloadURL()
	})
}

// SetThumbURL sets the "thumb_url" field.
func (u *GenerationImageUpsertBulk) SetThumbURL(v string) *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetThumbURL(v)
	})
}

// UpdateThumbURL sets the "thumb_url" field to the value that was provided on create.
func (u *GenerationImageUpsertBulk) UpdateThumbURL() *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateThumbURL()
	})
}

// SetSource sets the "source" field.
func (u *GenerationImageUpsertBulk) SetSource(v string) *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *GenerationImageUpsertBulk) UpdateSource() *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateSource()
	})
}

// SetImageNumber sets the "image_number" field.
func (u *GenerationImageUpsertBulk) SetImageNumber(v int) *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetImageNumber(v)
	})
}

// AddImageNumber adds v to the "image_number" field.
func (u *GenerationImageUpsertBulk) AddImageNumber(v int) *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.AddImageNumber(v)
	})
}

// UpdateImageNumber sets the "image_number" field to the value that was provided on create.
func (u *GenerationImageUpsertBulk) UpdateImageNumber() *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateImageNumber()
	})
}

// SetStatus sets the "status" field.
func (u *GenerationImageUpsertBulk) SetStatus(v string) *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GenerationImageUpsertBulk) UpdateStatus() *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateStatus()
	})
}

// SetError sets the "error" field.
func (u *GenerationImageUpsertBulk) SetError(v string) *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *GenerationImageUpsertBulk) UpdateError() *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateError()
	})
}

// SetLatencyMs sets the "latency_ms" field.
func (u *GenerationImageUpsertBulk) SetLatencyMs(v int) *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetLatencyMs(v)
	})
}

// AddLatencyMs adds v to the "latency_ms" field.
func (u *GenerationImageUpsertBulk) AddLatencyMs(v int) *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.AddLatencyMs(v)
	})
}

// UpdateLatencyMs sets the "latency_ms" field to the value that was provided on create.
func (u *GenerationImageUpsertBulk) UpdateLatencyMs() *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateLatencyMs()
	})
}

// SetDeleted sets the "deleted" field.
func (u *GenerationImageUpsertBulk) SetDeleted(v bool) *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetDeleted(v)
	})
}

// UpdateDeleted sets the "deleted" field to the value that was provided on create.
func (u *GenerationImageUpsertBulk) UpdateDeleted() *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateDeleted()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *GenerationImageUpsertBulk) SetDeletedAt(v time.Time) *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *GenerationImageUpsertBulk) UpdateDeletedAt() *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *GenerationImageUpsertBulk) ClearDeletedAt() *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *GenerationImageUpsertBulk) SetCreatedAt(v time.Time) *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *GenerationImageUpsertBulk) UpdateCreatedAt() *GenerationImageUpsertBulk {
	return u.Update(func(s *GenerationImageUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *GenerationImageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("db: OnConflict was set for builder %d. Set it on the GenerationImageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for GenerationImageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GenerationImageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
