// Code generated by ent, DO NOT EDIT.

package db

import (
	"bridal/backend/db/generationimage"
	"bridal/backend/db/generationtask"
	"bridal/backend/db/predicate"
	"bridal/backend/ent/types"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// GenerationTaskUpdate is the builder for updating GenerationTask entities.
type GenerationTaskUpdate struct {
	config
	hooks     []Hook
	mutation  *GenerationTaskMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the GenerationTaskUpdate builder.
func (_u *GenerationTaskUpdate) Where(ps ...predicate.GenerationTask) *GenerationTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *GenerationTaskUpdate) SetUserID(v uuid.UUID) *GenerationTaskUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableUserID(v *uuid.UUID) *GenerationTaskUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *GenerationTaskUpdate) SetUsername(v string) *GenerationTaskUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableUsername(v *string) *GenerationTaskUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *GenerationTaskUpdate) SetStatus(v string) *GenerationTaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableStatus(v *string) *GenerationTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *GenerationTaskUpdate) SetModel(v string) *GenerationTaskUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableModel(v *string) *GenerationTaskUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *GenerationTaskUpdate) SetMode(v string) *GenerationTaskUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableMode(v *string) *GenerationTaskUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *GenerationTaskUpdate) SetTitle(v string) *GenerationTaskUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableTitle(v *string) *GenerationTaskUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *GenerationTaskUpdate) SetBody(v string) *GenerationTaskUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableBody(v *string) *GenerationTaskUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *GenerationTaskUpdate) SetTags(v []string) *GenerationTaskUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *GenerationTaskUpdate) AppendTags(v []string) *GenerationTaskUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// SetTopic sets the "topic" field.
func (_u *GenerationTaskUpdate) SetTopic(v string) *GenerationTaskUpdate {
	_u.mutation.SetTopic(v)
	return _u
}

// SetNillableTopic sets the "topic" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableTopic(v *string) *GenerationTaskUpdate {
	if v != nil {
		_u.SetTopic(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *GenerationTaskUpdate) SetError(v string) *GenerationTaskUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableError(v *string) *GenerationTaskUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetPromptHash sets the "prompt_hash" field.
func (_u *GenerationTaskUpdate) SetPromptHash(v string) *GenerationTaskUpdate {
	_u.mutation.SetPromptHash(v)
	return _u
}

// SetNillablePromptHash sets the "prompt_hash" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillablePromptHash(v *string) *GenerationTaskUpdate {
	if v != nil {
		_u.SetPromptHash(*v)
	}
	return _u
}

// SetUploadedImageCount sets the "uploaded_image_count" field.
func (_u *GenerationTaskUpdate) SetUploadedImageCount(v int) *GenerationTaskUpdate {
	_u.mutation.ResetUploadedImageCount()
	_u.mutation.SetUploadedImageCount(v)
	return _u
}

// SetNillableUploadedImageCount sets the "uploaded_image_count" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableUploadedImageCount(v *int) *GenerationTaskUpdate {
	if v != nil {
		_u.SetUploadedImageCount(*v)
	}
	return _u
}

// AddUploadedImageCount adds value to the "uploaded_image_count" field.
func (_u *GenerationTaskUpdate) AddUploadedImageCount(v int) *GenerationTaskUpdate {
	_u.mutation.AddUploadedImageCount(v)
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *GenerationTaskUpdate) SetLatencyMs(v int) *GenerationTaskUpdate {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableLatencyMs(v *int) *GenerationTaskUpdate {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *GenerationTaskUpdate) AddLatencyMs(v int) *GenerationTaskUpdate {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// SetTotalCount sets the "total_count" field.
func (_u *GenerationTaskUpdate) SetTotalCount(v int) *GenerationTaskUpdate {
	_u.mutation.ResetTotalCount()
	_u.mutation.SetTotalCount(v)
	return _u
}

// SetNillableTotalCount sets the "total_count" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableTotalCount(v *int) *GenerationTaskUpdate {
	if v != nil {
		_u.SetTotalCount(*v)
	}
	return _u
}

// AddTotalCount adds value to the "total_count" field.
func (_u *GenerationTaskUpdate) AddTotalCount(v int) *GenerationTaskUpdate {
	_u.mutation.AddTotalCount(v)
	return _u
}

// SetCompletedCount sets the "completed_count" field.
func (_u *GenerationTaskUpdate) SetCompletedCount(v int) *GenerationTaskUpdate {
	_u.mutation.ResetCompletedCount()
	_u.mutation.SetCompletedCount(v)
	return _u
}

// SetNillableCompletedCount sets the "completed_count" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableCompletedCount(v *int) *GenerationTaskUpdate {
	if v != nil {
		_u.SetCompletedCount(*v)
	}
	return _u
}

// AddCompletedCount adds value to the "completed_count" field.
func (_u *GenerationTaskUpdate) AddCompletedCount(v int) *GenerationTaskUpdate {
	_u.mutation.AddCompletedCount(v)
	return _u
}

// SetEstimatedSeconds sets the "estimated_seconds" field.
func (_u *GenerationTaskUpdate) SetEstimatedSeconds(v int) *GenerationTaskUpdate {
	_u.mutation.ResetEstimatedSeconds()
	_u.mutation.SetEstimatedSeconds(v)
	return _u
}

// SetNillableEstimatedSeconds sets the "estimated_seconds" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableEstimatedSeconds(v *int) *GenerationTaskUpdate {
	if v != nil {
		_u.SetEstimatedSeconds(*v)
	}
	return _u
}

// AddEstimatedSeconds adds value to the "estimated_seconds" field.
func (_u *GenerationTaskUpdate) AddEstimatedSeconds(v int) *GenerationTaskUpdate {
	_u.mutation.AddEstimatedSeconds(v)
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *GenerationTaskUpdate) SetCategoryID(v uuid.UUID) *GenerationTaskUpdate {
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableCategoryID(v *uuid.UUID) *GenerationTaskUpdate {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// ClearCategoryID clears the value of the "category_id" field.
func (_u *GenerationTaskUpdate) ClearCategoryID() *GenerationTaskUpdate {
	_u.mutation.ClearCategoryID()
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *GenerationTaskUpdate) SetChannelID(v uuid.UUID) *GenerationTaskUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableChannelID(v *uuid.UUID) *GenerationTaskUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// ClearChannelID clears the value of the "channel_id" field.
func (_u *GenerationTaskUpdate) ClearChannelID() *GenerationTaskUpdate {
	_u.mutation.ClearChannelID()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *GenerationTaskUpdate) SetStartedAt(v time.Time) *GenerationTaskUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableStartedAt(v *time.Time) *GenerationTaskUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *GenerationTaskUpdate) ClearStartedAt() *GenerationTaskUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *GenerationTaskUpdate) SetCompletedAt(v time.Time) *GenerationTaskUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableCompletedAt(v *time.Time) *GenerationTaskUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *GenerationTaskUpdate) ClearCompletedAt() *GenerationTaskUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetReferenceImages sets the "reference_images" field.
func (_u *GenerationTaskUpdate) SetReferenceImages(v []types.ReferenceImage) *GenerationTaskUpdate {
	_u.mutation.SetReferenceImages(v)
	return _u
}

// AppendReferenceImages appends value to the "reference_images" field.
func (_u *GenerationTaskUpdate) AppendReferenceImages(v []types.ReferenceImage) *GenerationTaskUpdate {
	_u.mutation.AppendReferenceImages(v)
	return _u
}

// ClearReferenceImages clears the value of the "reference_images" field.
func (_u *GenerationTaskUpdate) ClearReferenceImages() *GenerationTaskUpdate {
	_u.mutation.ClearReferenceImages()
	return _u
}

// SetPrompts sets the "prompts" field.
func (_u *GenerationTaskUpdate) SetPrompts(v []string) *GenerationTaskUpdate {
	_u.mutation.SetPrompts(v)
	return _u
}

// AppendPrompts appends value to the "prompts" field.
func (_u *GenerationTaskUpdate) AppendPrompts(v []string) *GenerationTaskUpdate {
	_u.mutation.AppendPrompts(v)
	return _u
}

// ClearPrompts clears the value of the "prompts" field.
func (_u *GenerationTaskUpdate) ClearPrompts() *GenerationTaskUpdate {
	_u.mutation.ClearPrompts()
	return _u
}

// SetImageSize sets the "image_size" field.
func (_u *GenerationTaskUpdate) SetImageSize(v string) *GenerationTaskUpdate {
	_u.mutation.SetImageSize(v)
	return _u
}

// SetNillableImageSize sets the "image_size" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableImageSize(v *string) *GenerationTaskUpdate {
	if v != nil {
		_u.SetImageSize(*v)
	}
	return _u
}

// SetImageQuality sets the "image_quality" field.
func (_u *GenerationTaskUpdate) SetImageQuality(v string) *GenerationTaskUpdate {
	_u.mutation.SetImageQuality(v)
	return _u
}

// SetNillableImageQuality sets the "image_quality" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableImageQuality(v *string) *GenerationTaskUpdate {
	if v != nil {
		_u.SetImageQuality(*v)
	}
	return _u
}

// SetFeedback sets the "feedback" field.
func (_u *GenerationTaskUpdate) SetFeedback(v types.TaskFeedback) *GenerationTaskUpdate {
	_u.mutation.SetFeedback(v)
	return _u
}

// SetNillableFeedback sets the "feedback" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableFeedback(v *types.TaskFeedback) *GenerationTaskUpdate {
	if v != nil {
		_u.SetFeedback(*v)
	}
	return _u
}

// ClearFeedback clears the value of the "feedback" field.
func (_u *GenerationTaskUpdate) ClearFeedback() *GenerationTaskUpdate {
	_u.mutation.ClearFeedback()
	return _u
}

// SetDeleted sets the "deleted" field.
func (_u *GenerationTaskUpdate) SetDeleted(v bool) *GenerationTaskUpdate {
	_u.mutation.SetDeleted(v)
	return _u
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableDeleted(v *bool) *GenerationTaskUpdate {
	if v != nil {
		_u.SetDeleted(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *GenerationTaskUpdate) SetDeletedAt(v time.Time) *GenerationTaskUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableDeletedAt(v *time.Time) *GenerationTaskUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *GenerationTaskUpdate) ClearDeletedAt() *GenerationTaskUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GenerationTaskUpdate) SetCreatedAt(v time.Time) *GenerationTaskUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GenerationTaskUpdate) SetNillableCreatedAt(v *time.Time) *GenerationTaskUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddImageIDs adds the "images" edge to the GenerationImage entity by IDs.
func (_u *GenerationTaskUpdate) AddImageIDs(ids ...string) *GenerationTaskUpdate {
	_u.mutation.AddImageIDs(ids...)
	return _u
}

// AddImages adds the "images" edges to the GenerationImage entity.
func (_u *GenerationTaskUpdate) AddImages(v ...*GenerationImage) *GenerationTaskUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddImageIDs(ids...)
}

// Mutation returns the GenerationTaskMutation object of the builder.
func (_u *GenerationTaskUpdate) Mutation() *GenerationTaskMutation {
	return _u.mutation
}

// ClearImages clears all "images" edges to the GenerationImage entity.
func (_u *GenerationTaskUpdate) ClearImages() *GenerationTaskUpdate {
	_u.mutation.ClearImages()
	return _u
}

// RemoveImageIDs removes the "images" edge to GenerationImage entities by IDs.
func (_u *GenerationTaskUpdate) RemoveImageIDs(ids ...string) *GenerationTaskUpdate {
	_u.mutation.RemoveImageIDs(ids...)
	return _u
}

// RemoveImages removes "images" edges to GenerationImage entities.
func (_u *GenerationTaskUpdate) RemoveImages(v ...*GenerationImage) *GenerationTaskUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveImageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GenerationTaskUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GenerationTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GenerationTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GenerationTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *GenerationTaskUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *GenerationTaskUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *GenerationTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(generationtask.Table, generationtask.Columns, sqlgraph.NewFieldSpec(generationtask.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(generationtask.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(generationtask.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(generationtask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(generationtask.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(generationtask.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(generationtask.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(generationtask.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(generationtask.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, generationtask.FieldTags, value)
		})
	}
	if value, ok := _u.mutation.Topic(); ok {
		_spec.SetField(generationtask.FieldTopic, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(generationtask.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.PromptHash(); ok {
		_spec.SetField(generationtask.FieldPromptHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.UploadedImageCount(); ok {
		_spec.SetField(generationtask.FieldUploadedImageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUploadedImageCount(); ok {
		_spec.AddField(generationtask.FieldUploadedImageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(generationtask.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(generationtask.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalCount(); ok {
		_spec.SetField(generationtask.FieldTotalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalCount(); ok {
		_spec.AddField(generationtask.FieldTotalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CompletedCount(); ok {
		_spec.SetField(generationtask.FieldCompletedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCompletedCount(); ok {
		_spec.AddField(generationtask.FieldCompletedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EstimatedSeconds(); ok {
		_spec.SetField(generationtask.FieldEstimatedSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEstimatedSeconds(); ok {
		_spec.AddField(generationtask.FieldEstimatedSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CategoryID(); ok {
		_spec.SetField(generationtask.FieldCategoryID, field.TypeUUID, value)
	}
	if _u.mutation.CategoryIDCleared() {
		_spec.ClearField(generationtask.FieldCategoryID, field.TypeUUID)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(generationtask.FieldChannelID, field.TypeUUID, value)
	}
	if _u.mutation.ChannelIDCleared() {
		_spec.ClearField(generationtask.FieldChannelID, field.TypeUUID)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(generationtask.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(generationtask.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(generationtask.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(generationtask.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReferenceImages(); ok {
		_spec.SetField(generationtask.FieldReferenceImages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedReferenceImages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, generationtask.FieldReferenceImages, value)
		})
	}
	if _u.mutation.ReferenceImagesCleared() {
		_spec.ClearField(generationtask.FieldReferenceImages, field.TypeJSON)
	}
	if value, ok := _u.mutation.Prompts(); ok {
		_spec.SetField(generationtask.FieldPrompts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPrompts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, generationtask.FieldPrompts, value)
		})
	}
	if _u.mutation.PromptsCleared() {
		_spec.ClearField(generationtask.FieldPrompts, field.TypeJSON)
	}
	if value, ok := _u.mutation.ImageSize(); ok {
		_spec.SetField(generationtask.FieldImageSize, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImageQuality(); ok {
		_spec.SetField(generationtask.FieldImageQuality, field.TypeString, value)
	}
	if value, ok := _u.mutation.Feedback(); ok {
		_spec.SetField(generationtask.FieldFeedback, field.TypeJSON, value)
	}
	if _u.mutation.FeedbackCleared() {
		_spec.ClearField(generationtask.FieldFeedback, field.TypeJSON)
	}
	if value, ok := _u.mutation.Deleted(); ok {
		_spec.SetField(generationtask.FieldDeleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(generationtask.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(generationtask.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(generationtask.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ImagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   generationtask.ImagesTable,
			Columns: []string{generationtask.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(generationimage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedImagesIDs(); len(nodes) > 0 && !_u.mutation.ImagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   generationtask.ImagesTable,
			Columns: []string{generationtask.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(generationimage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ImagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   generationtask.ImagesTable,
			Columns: []string{generationtask.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(generationimage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{generationtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GenerationTaskUpdateOne is the builder for updating a single GenerationTask entity.
type GenerationTaskUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *GenerationTaskMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUserID sets the "user_id" field.
func (_u *GenerationTaskUpdateOne) SetUserID(v uuid.UUID) *GenerationTaskUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableUserID(v *uuid.UUID) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *GenerationTaskUpdateOne) SetUsername(v string) *GenerationTaskUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableUsername(v *string) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *GenerationTaskUpdateOne) SetStatus(v string) *GenerationTaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableStatus(v *string) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *GenerationTaskUpdateOne) SetModel(v string) *GenerationTaskUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableModel(v *string) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *GenerationTaskUpdateOne) SetMode(v string) *GenerationTaskUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableMode(v *string) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *GenerationTaskUpdateOne) SetTitle(v string) *GenerationTaskUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableTitle(v *string) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *GenerationTaskUpdateOne) SetBody(v string) *GenerationTaskUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableBody(v *string) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *GenerationTaskUpdateOne) SetTags(v []string) *GenerationTaskUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *GenerationTaskUpdateOne) AppendTags(v []string) *GenerationTaskUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// SetTopic sets the "topic" field.
func (_u *GenerationTaskUpdateOne) SetTopic(v string) *GenerationTaskUpdateOne {
	_u.mutation.SetTopic(v)
	return _u
}

// SetNillableTopic sets the "topic" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableTopic(v *string) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetTopic(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *GenerationTaskUpdateOne) SetError(v string) *GenerationTaskUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableError(v *string) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetPromptHash sets the "prompt_hash" field.
func (_u *GenerationTaskUpdateOne) SetPromptHash(v string) *GenerationTaskUpdateOne {
	_u.mutation.SetPromptHash(v)
	return _u
}

// SetNillablePromptHash sets the "prompt_hash" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillablePromptHash(v *string) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetPromptHash(*v)
	}
	return _u
}

// SetUploadedImageCount sets the "uploaded_image_count" field.
func (_u *GenerationTaskUpdateOne) SetUploadedImageCount(v int) *GenerationTaskUpdateOne {
	_u.mutation.ResetUploadedImageCount()
	_u.mutation.SetUploadedImageCount(v)
	return _u
}

// SetNillableUploadedImageCount sets the "uploaded_image_count" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableUploadedImageCount(v *int) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetUploadedImageCount(*v)
	}
	return _u
}

// AddUploadedImageCount adds value to the "uploaded_image_count" field.
func (_u *GenerationTaskUpdateOne) AddUploadedImageCount(v int) *GenerationTaskUpdateOne {
	_u.mutation.AddUploadedImageCount(v)
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *GenerationTaskUpdateOne) SetLatencyMs(v int) *GenerationTaskUpdateOne {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableLatencyMs(v *int) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *GenerationTaskUpdateOne) AddLatencyMs(v int) *GenerationTaskUpdateOne {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// SetTotalCount sets the "total_count" field.
func (_u *GenerationTaskUpdateOne) SetTotalCount(v int) *GenerationTaskUpdateOne {
	_u.mutation.ResetTotalCount()
	_u.mutation.SetTotalCount(v)
	return _u
}

// SetNillableTotalCount sets the "total_count" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableTotalCount(v *int) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetTotalCount(*v)
	}
	return _u
}

// AddTotalCount adds value to the "total_count" field.
func (_u *GenerationTaskUpdateOne) AddTotalCount(v int) *GenerationTaskUpdateOne {
	_u.mutation.AddTotalCount(v)
	return _u
}

// SetCompletedCount sets the "completed_count" field.
func (_u *GenerationTaskUpdateOne) SetCompletedCount(v int) *GenerationTaskUpdateOne {
	_u.mutation.ResetCompletedCount()
	_u.mutation.SetCompletedCount(v)
	return _u
}

// SetNillableCompletedCount sets the "completed_count" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableCompletedCount(v *int) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetCompletedCount(*v)
	}
	return _u
}

// AddCompletedCount adds value to the "completed_count" field.
func (_u *GenerationTaskUpdateOne) AddCompletedCount(v int) *GenerationTaskUpdateOne {
	_u.mutation.AddCompletedCount(v)
	return _u
}

// SetEstimatedSeconds sets the "estimated_seconds" field.
func (_u *GenerationTaskUpdateOne) SetEstimatedSeconds(v int) *GenerationTaskUpdateOne {
	_u.mutation.ResetEstimatedSeconds()
	_u.mutation.SetEstimatedSeconds(v)
	return _u
}

// SetNillableEstimatedSeconds sets the "estimated_seconds" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableEstimatedSeconds(v *int) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetEstimatedSeconds(*v)
	}
	return _u
}

// AddEstimatedSeconds adds value to the "estimated_seconds" field.
func (_u *GenerationTaskUpdateOne) AddEstimatedSeconds(v int) *GenerationTaskUpdateOne {
	_u.mutation.AddEstimatedSeconds(v)
	return _u
}

// SetCategoryID sets the "category_id" field.
func (_u *GenerationTaskUpdateOne) SetCategoryID(v uuid.UUID) *GenerationTaskUpdateOne {
	_u.mutation.SetCategoryID(v)
	return _u
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableCategoryID(v *uuid.UUID) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetCategoryID(*v)
	}
	return _u
}

// ClearCategoryID clears the value of the "category_id" field.
func (_u *GenerationTaskUpdateOne) ClearCategoryID() *GenerationTaskUpdateOne {
	_u.mutation.ClearCategoryID()
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *GenerationTaskUpdateOne) SetChannelID(v uuid.UUID) *GenerationTaskUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableChannelID(v *uuid.UUID) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// ClearChannelID clears the value of the "channel_id" field.
func (_u *GenerationTaskUpdateOne) ClearChannelID() *GenerationTaskUpdateOne {
	_u.mutation.ClearChannelID()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *GenerationTaskUpdateOne) SetStartedAt(v time.Time) *GenerationTaskUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableStartedAt(v *time.Time) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *GenerationTaskUpdateOne) ClearStartedAt() *GenerationTaskUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *GenerationTaskUpdateOne) SetCompletedAt(v time.Time) *GenerationTaskUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableCompletedAt(v *time.Time) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *GenerationTaskUpdateOne) ClearCompletedAt() *GenerationTaskUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetReferenceImages sets the "reference_images" field.
func (_u *GenerationTaskUpdateOne) SetReferenceImages(v []types.ReferenceImage) *GenerationTaskUpdateOne {
	_u.mutation.SetReferenceImages(v)
	return _u
}

// AppendReferenceImages appends value to the "reference_images" field.
func (_u *GenerationTaskUpdateOne) AppendReferenceImages(v []types.ReferenceImage) *GenerationTaskUpdateOne {
	_u.mutation.AppendReferenceImages(v)
	return _u
}

// ClearReferenceImages clears the value of the "reference_images" field.
func (_u *GenerationTaskUpdateOne) ClearReferenceImages() *GenerationTaskUpdateOne {
	_u.mutation.ClearReferenceImages()
	return _u
}

// SetPrompts sets the "prompts" field.
func (_u *GenerationTaskUpdateOne) SetPrompts(v []string) *GenerationTaskUpdateOne {
	_u.mutation.SetPrompts(v)
	return _u
}

// AppendPrompts appends value to the "prompts" field.
func (_u *GenerationTaskUpdateOne) AppendPrompts(v []string) *GenerationTaskUpdateOne {
	_u.mutation.AppendPrompts(v)
	return _u
}

// ClearPrompts clears the value of the "prompts" field.
func (_u *GenerationTaskUpdateOne) ClearPrompts() *GenerationTaskUpdateOne {
	_u.mutation.ClearPrompts()
	return _u
}

// SetImageSize sets the "image_size" field.
func (_u *GenerationTaskUpdateOne) SetImageSize(v string) *GenerationTaskUpdateOne {
	_u.mutation.SetImageSize(v)
	return _u
}

// SetNillableImageSize sets the "image_size" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableImageSize(v *string) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetImageSize(*v)
	}
	return _u
}

// SetImageQuality sets the "image_quality" field.
func (_u *GenerationTaskUpdateOne) SetImageQuality(v string) *GenerationTaskUpdateOne {
	_u.mutation.SetImageQuality(v)
	return _u
}

// SetNillableImageQuality sets the "image_quality" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableImageQuality(v *string) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetImageQuality(*v)
	}
	return _u
}

// SetFeedback sets the "feedback" field.
func (_u *GenerationTaskUpdateOne) SetFeedback(v types.TaskFeedback) *GenerationTaskUpdateOne {
	_u.mutation.SetFeedback(v)
	return _u
}

// SetNillableFeedback sets the "feedback" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableFeedback(v *types.TaskFeedback) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetFeedback(*v)
	}
	return _u
}

// ClearFeedback clears the value of the "feedback" field.
func (_u *GenerationTaskUpdateOne) ClearFeedback() *GenerationTaskUpdateOne {
	_u.mutation.ClearFeedback()
	return _u
}

// SetDeleted sets the "deleted" field.
func (_u *GenerationTaskUpdateOne) SetDeleted(v bool) *GenerationTaskUpdateOne {
	_u.mutation.SetDeleted(v)
	return _u
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableDeleted(v *bool) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetDeleted(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *GenerationTaskUpdateOne) SetDeletedAt(v time.Time) *GenerationTaskUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableDeletedAt(v *time.Time) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *GenerationTaskUpdateOne) ClearDeletedAt() *GenerationTaskUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GenerationTaskUpdateOne) SetCreatedAt(v time.Time) *GenerationTaskUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GenerationTaskUpdateOne) SetNillableCreatedAt(v *time.Time) *GenerationTaskUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddImageIDs adds the "images" edge to the GenerationImage entity by IDs.
func (_u *GenerationTaskUpdateOne) AddImageIDs(ids ...string) *GenerationTaskUpdateOne {
	_u.mutation.AddImageIDs(ids...)
	return _u
}

// AddImages adds the "images" edges to the GenerationImage entity.
func (_u *GenerationTaskUpdateOne) AddImages(v ...*GenerationImage) *GenerationTaskUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddImageIDs(ids...)
}

// Mutation returns the GenerationTaskMutation object of the builder.
func (_u *GenerationTaskUpdateOne) Mutation() *GenerationTaskMutation {
	return _u.mutation
}

// ClearImages clears all "images" edges to the GenerationImage entity.
func (_u *GenerationTaskUpdateOne) ClearImages() *GenerationTaskUpdateOne {
	_u.mutation.ClearImages()
	return _u
}

// RemoveImageIDs removes the "images" edge to GenerationImage entities by IDs.
func (_u *GenerationTaskUpdateOne) RemoveImageIDs(ids ...string) *GenerationTaskUpdateOne {
	_u.mutation.RemoveImageIDs(ids...)
	return _u
}

// RemoveImages removes "images" edges to GenerationImage entities.
func (_u *GenerationTaskUpdateOne) RemoveImages(v ...*GenerationImage) *GenerationTaskUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveImageIDs(ids...)
}

// Where appends a list predicates to the GenerationTaskUpdate builder.
func (_u *GenerationTaskUpdateOne) Where(ps ...predicate.GenerationTask) *GenerationTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GenerationTaskUpdateOne) Select(field string, fields ...string) *GenerationTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GenerationTask entity.
func (_u *GenerationTaskUpdateOne) Save(ctx context.Context) (*GenerationTask, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GenerationTaskUpdateOne) SaveX(ctx context.Context) *GenerationTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GenerationTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GenerationTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *GenerationTaskUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *GenerationTaskUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *GenerationTaskUpdateOne) sqlSave(ctx context.Context) (_node *GenerationTask, err error) {
	_spec := sqlgraph.NewUpdateSpec(generationtask.Table, generationtask.Columns, sqlgraph.NewFieldSpec(generationtask.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "GenerationTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, generationtask.FieldID)
		for _, f := range fields {
			if !generationtask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != generationtask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(generationtask.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(generationtask.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(generationtask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(generationtask.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(generationtask.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(generationtask.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(generationtask.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(generationtask.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, generationtask.FieldTags, value)
		})
	}
	if value, ok := _u.mutation.Topic(); ok {
		_spec.SetField(generationtask.FieldTopic, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(generationtask.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.PromptHash(); ok {
		_spec.SetField(generationtask.FieldPromptHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.UploadedImageCount(); ok {
		_spec.SetField(generationtask.FieldUploadedImageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUploadedImageCount(); ok {
		_spec.AddField(generationtask.FieldUploadedImageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(generationtask.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(generationtask.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalCount(); ok {
		_spec.SetField(generationtask.FieldTotalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalCount(); ok {
		_spec.AddField(generationtask.FieldTotalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CompletedCount(); ok {
		_spec.SetField(generationtask.FieldCompletedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCompletedCount(); ok {
		_spec.AddField(generationtask.FieldCompletedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EstimatedSeconds(); ok {
		_spec.SetField(generationtask.FieldEstimatedSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEstimatedSeconds(); ok {
		_spec.AddField(generationtask.FieldEstimatedSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CategoryID(); ok {
		_spec.SetField(generationtask.FieldCategoryID, field.TypeUUID, value)
	}
	if _u.mutation.CategoryIDCleared() {
		_spec.ClearField(generationtask.FieldCategoryID, field.TypeUUID)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(generationtask.FieldChannelID, field.TypeUUID, value)
	}
	if _u.mutation.ChannelIDCleared() {
		_spec.ClearField(generationtask.FieldChannelID, field.TypeUUID)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(generationtask.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(generationtask.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(generationtask.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(generationtask.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReferenceImages(); ok {
		_spec.SetField(generationtask.FieldReferenceImages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedReferenceImages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, generationtask.FieldReferenceImages, value)
		})
	}
	if _u.mutation.ReferenceImagesCleared() {
		_spec.ClearField(generationtask.FieldReferenceImages, field.TypeJSON)
	}
	if value, ok := _u.mutation.Prompts(); ok {
		_spec.SetField(generationtask.FieldPrompts, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPrompts(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, generationtask.FieldPrompts, value)
		})
	}
	if _u.mutation.PromptsCleared() {
		_spec.ClearField(generationtask.FieldPrompts, field.TypeJSON)
	}
	if value, ok := _u.mutation.ImageSize(); ok {
		_spec.SetField(generationtask.FieldImageSize, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImageQuality(); ok {
		_spec.SetField(generationtask.FieldImageQuality, field.TypeString, value)
	}
	if value, ok := _u.mutation.Feedback(); ok {
		_spec.SetField(generationtask.FieldFeedback, field.TypeJSON, value)
	}
	if _u.mutation.FeedbackCleared() {
		_spec.ClearField(generationtask.FieldFeedback, field.TypeJSON)
	}
	if value, ok := _u.mutation.Deleted(); ok {
		_spec.SetField(generationtask.FieldDeleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(generationtask.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(generationtask.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(generationtask.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ImagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   generationtask.ImagesTable,
			Columns: []string{generationtask.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(generationimage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedImagesIDs(); len(nodes) > 0 && !_u.mutation.ImagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   generationtask.ImagesTable,
			Columns: []string{generationtask.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(generationimage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ImagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   generationtask.ImagesTable,
			Columns: []string{generationtask.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(generationimage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &GenerationTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{generationtask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
