// Code generated by ent, DO NOT EDIT.

package db

import (
	"bridal/backend/db/generationmodelinvocation"
	"bridal/backend/db/predicate"
	"bridal/backend/ent/types"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// GenerationModelInvocationUpdate is the builder for updating GenerationModelInvocation entities.
type GenerationModelInvocationUpdate struct {
	config
	hooks     []Hook
	mutation  *GenerationModelInvocationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the GenerationModelInvocationUpdate builder.
func (_u *GenerationModelInvocationUpdate) Where(ps ...predicate.GenerationModelInvocation) *GenerationModelInvocationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *GenerationModelInvocationUpdate) SetTaskID(v uuid.UUID) *GenerationModelInvocationUpdate {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillableTaskID(v *uuid.UUID) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetGenerationImageID sets the "generation_image_id" field.
func (_u *GenerationModelInvocationUpdate) SetGenerationImageID(v string) *GenerationModelInvocationUpdate {
	_u.mutation.SetGenerationImageID(v)
	return _u
}

// SetNillableGenerationImageID sets the "generation_image_id" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillableGenerationImageID(v *string) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetGenerationImageID(*v)
	}
	return _u
}

// SetImageNumber sets the "image_number" field.
func (_u *GenerationModelInvocationUpdate) SetImageNumber(v int) *GenerationModelInvocationUpdate {
	_u.mutation.ResetImageNumber()
	_u.mutation.SetImageNumber(v)
	return _u
}

// SetNillableImageNumber sets the "image_number" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillableImageNumber(v *int) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetImageNumber(*v)
	}
	return _u
}

// AddImageNumber adds value to the "image_number" field.
func (_u *GenerationModelInvocationUpdate) AddImageNumber(v int) *GenerationModelInvocationUpdate {
	_u.mutation.AddImageNumber(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *GenerationModelInvocationUpdate) SetUserID(v uuid.UUID) *GenerationModelInvocationUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillableUserID(v *uuid.UUID) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *GenerationModelInvocationUpdate) SetUsername(v string) *GenerationModelInvocationUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillableUsername(v *string) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *GenerationModelInvocationUpdate) SetUserEmail(v string) *GenerationModelInvocationUpdate {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillableUserEmail(v *string) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// SetUserRole sets the "user_role" field.
func (_u *GenerationModelInvocationUpdate) SetUserRole(v string) *GenerationModelInvocationUpdate {
	_u.mutation.SetUserRole(v)
	return _u
}

// SetNillableUserRole sets the "user_role" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillableUserRole(v *string) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetUserRole(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *GenerationModelInvocationUpdate) SetChannelID(v uuid.UUID) *GenerationModelInvocationUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillableChannelID(v *uuid.UUID) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// ClearChannelID clears the value of the "channel_id" field.
func (_u *GenerationModelInvocationUpdate) ClearChannelID() *GenerationModelInvocationUpdate {
	_u.mutation.ClearChannelID()
	return _u
}

// SetChannelName sets the "channel_name" field.
func (_u *GenerationModelInvocationUpdate) SetChannelName(v string) *GenerationModelInvocationUpdate {
	_u.mutation.SetChannelName(v)
	return _u
}

// SetNillableChannelName sets the "channel_name" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillableChannelName(v *string) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetChannelName(*v)
	}
	return _u
}

// SetAPIBaseURL sets the "api_base_url" field.
func (_u *GenerationModelInvocationUpdate) SetAPIBaseURL(v string) *GenerationModelInvocationUpdate {
	_u.mutation.SetAPIBaseURL(v)
	return _u
}

// SetNillableAPIBaseURL sets the "api_base_url" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillableAPIBaseURL(v *string) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetAPIBaseURL(*v)
	}
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *GenerationModelInvocationUpdate) SetProtocol(v string) *GenerationModelInvocationUpdate {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillableProtocol(v *string) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *GenerationModelInvocationUpdate) SetModelID(v string) *GenerationModelInvocationUpdate {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillableModelID(v *string) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetCandidateIndex sets the "candidate_index" field.
func (_u *GenerationModelInvocationUpdate) SetCandidateIndex(v int) *GenerationModelInvocationUpdate {
	_u.mutation.ResetCandidateIndex()
	_u.mutation.SetCandidateIndex(v)
	return _u
}

// SetNillableCandidateIndex sets the "candidate_index" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillableCandidateIndex(v *int) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetCandidateIndex(*v)
	}
	return _u
}

// AddCandidateIndex adds value to the "candidate_index" field.
func (_u *GenerationModelInvocationUpdate) AddCandidateIndex(v int) *GenerationModelInvocationUpdate {
	_u.mutation.AddCandidateIndex(v)
	return _u
}

// SetCandidateCount sets the "candidate_count" field.
func (_u *GenerationModelInvocationUpdate) SetCandidateCount(v int) *GenerationModelInvocationUpdate {
	_u.mutation.ResetCandidateCount()
	_u.mutation.SetCandidateCount(v)
	return _u
}

// SetNillableCandidateCount sets the "candidate_count" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillableCandidateCount(v *int) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetCandidateCount(*v)
	}
	return _u
}

// AddCandidateCount adds value to the "candidate_count" field.
func (_u *GenerationModelInvocationUpdate) AddCandidateCount(v int) *GenerationModelInvocationUpdate {
	_u.mutation.AddCandidateCount(v)
	return _u
}

// SetAttemptNumber sets the "attempt_number" field.
func (_u *GenerationModelInvocationUpdate) SetAttemptNumber(v int) *GenerationModelInvocationUpdate {
	_u.mutation.ResetAttemptNumber()
	_u.mutation.SetAttemptNumber(v)
	return _u
}

// SetNillableAttemptNumber sets the "attempt_number" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillableAttemptNumber(v *int) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetAttemptNumber(*v)
	}
	return _u
}

// AddAttemptNumber adds value to the "attempt_number" field.
func (_u *GenerationModelInvocationUpdate) AddAttemptNumber(v int) *GenerationModelInvocationUpdate {
	_u.mutation.AddAttemptNumber(v)
	return _u
}

// SetAttemptBudget sets the "attempt_budget" field.
func (_u *GenerationModelInvocationUpdate) SetAttemptBudget(v int) *GenerationModelInvocationUpdate {
	_u.mutation.ResetAttemptBudget()
	_u.mutation.SetAttemptBudget(v)
	return _u
}

// SetNillableAttemptBudget sets the "attempt_budget" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillableAttemptBudget(v *int) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetAttemptBudget(*v)
	}
	return _u
}

// AddAttemptBudget adds value to the "attempt_budget" field.
func (_u *GenerationModelInvocationUpdate) AddAttemptBudget(v int) *GenerationModelInvocationUpdate {
	_u.mutation.AddAttemptBudget(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *GenerationModelInvocationUpdate) SetStatus(v string) *GenerationModelInvocationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillableStatus(v *string) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *GenerationModelInvocationUpdate) SetPrompt(v string) *GenerationModelInvocationUpdate {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillablePrompt(v *string) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetPromptHash sets the "prompt_hash" field.
func (_u *GenerationModelInvocationUpdate) SetPromptHash(v string) *GenerationModelInvocationUpdate {
	_u.mutation.SetPromptHash(v)
	return _u
}

// SetNillablePromptHash sets the "prompt_hash" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillablePromptHash(v *string) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetPromptHash(*v)
	}
	return _u
}

// SetReferenceImages sets the "reference_images" field.
func (_u *GenerationModelInvocationUpdate) SetReferenceImages(v []types.ModelInvocationReference) *GenerationModelInvocationUpdate {
	_u.mutation.SetReferenceImages(v)
	return _u
}

// AppendReferenceImages appends value to the "reference_images" field.
func (_u *GenerationModelInvocationUpdate) AppendReferenceImages(v []types.ModelInvocationReference) *GenerationModelInvocationUpdate {
	_u.mutation.AppendReferenceImages(v)
	return _u
}

// SetSize sets the "size" field.
func (_u *GenerationModelInvocationUpdate) SetSize(v string) *GenerationModelInvocationUpdate {
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillableSize(v *string) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// SetQuality sets the "quality" field.
func (_u *GenerationModelInvocationUpdate) SetQuality(v string) *GenerationModelInvocationUpdate {
	_u.mutation.SetQuality(v)
	return _u
}

// SetNillableQuality sets the "quality" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillableQuality(v *string) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetQuality(*v)
	}
	return _u
}

// SetHTTPStatus sets the "http_status" field.
func (_u *GenerationModelInvocationUpdate) SetHTTPStatus(v int) *GenerationModelInvocationUpdate {
	_u.mutation.ResetHTTPStatus()
	_u.mutation.SetHTTPStatus(v)
	return _u
}

// SetNillableHTTPStatus sets the "http_status" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillableHTTPStatus(v *int) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetHTTPStatus(*v)
	}
	return _u
}

// AddHTTPStatus adds value to the "http_status" field.
func (_u *GenerationModelInvocationUpdate) AddHTTPStatus(v int) *GenerationModelInvocationUpdate {
	_u.mutation.AddHTTPStatus(v)
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *GenerationModelInvocationUpdate) SetLatencyMs(v int) *GenerationModelInvocationUpdate {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillableLatencyMs(v *int) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *GenerationModelInvocationUpdate) AddLatencyMs(v int) *GenerationModelInvocationUpdate {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// SetResponseImageCount sets the "response_image_count" field.
func (_u *GenerationModelInvocationUpdate) SetResponseImageCount(v int) *GenerationModelInvocationUpdate {
	_u.mutation.ResetResponseImageCount()
	_u.mutation.SetResponseImageCount(v)
	return _u
}

// SetNillableResponseImageCount sets the "response_image_count" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillableResponseImageCount(v *int) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetResponseImageCount(*v)
	}
	return _u
}

// AddResponseImageCount adds value to the "response_image_count" field.
func (_u *GenerationModelInvocationUpdate) AddResponseImageCount(v int) *GenerationModelInvocationUpdate {
	_u.mutation.AddResponseImageCount(v)
	return _u
}

// SetError sets the "error" field.
func (_u *GenerationModelInvocationUpdate) SetError(v string) *GenerationModelInvocationUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillableError(v *string) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetRequestedAt sets the "requested_at" field.
func (_u *GenerationModelInvocationUpdate) SetRequestedAt(v time.Time) *GenerationModelInvocationUpdate {
	_u.mutation.SetRequestedAt(v)
	return _u
}

// SetNillableRequestedAt sets the "requested_at" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillableRequestedAt(v *time.Time) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetRequestedAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *GenerationModelInvocationUpdate) SetCompletedAt(v time.Time) *GenerationModelInvocationUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdate) SetNillableCompletedAt(v *time.Time) *GenerationModelInvocationUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *GenerationModelInvocationUpdate) ClearCompletedAt() *GenerationModelInvocationUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the GenerationModelInvocationMutation object of the builder.
func (_u *GenerationModelInvocationUpdate) Mutation() *GenerationModelInvocationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GenerationModelInvocationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GenerationModelInvocationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GenerationModelInvocationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GenerationModelInvocationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *GenerationModelInvocationUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *GenerationModelInvocationUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *GenerationModelInvocationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(generationmodelinvocation.Table, generationmodelinvocation.Columns, sqlgraph.NewFieldSpec(generationmodelinvocation.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(generationmodelinvocation.FieldTaskID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.GenerationImageID(); ok {
		_spec.SetField(generationmodelinvocation.FieldGenerationImageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImageNumber(); ok {
		_spec.SetField(generationmodelinvocation.FieldImageNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedImageNumber(); ok {
		_spec.AddField(generationmodelinvocation.FieldImageNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(generationmodelinvocation.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(generationmodelinvocation.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(generationmodelinvocation.FieldUserEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserRole(); ok {
		_spec.SetField(generationmodelinvocation.FieldUserRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(generationmodelinvocation.FieldChannelID, field.TypeUUID, value)
	}
	if _u.mutation.ChannelIDCleared() {
		_spec.ClearField(generationmodelinvocation.FieldChannelID, field.TypeUUID)
	}
	if value, ok := _u.mutation.ChannelName(); ok {
		_spec.SetField(generationmodelinvocation.FieldChannelName, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIBaseURL(); ok {
		_spec.SetField(generationmodelinvocation.FieldAPIBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(generationmodelinvocation.FieldProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(generationmodelinvocation.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CandidateIndex(); ok {
		_spec.SetField(generationmodelinvocation.FieldCandidateIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCandidateIndex(); ok {
		_spec.AddField(generationmodelinvocation.FieldCandidateIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CandidateCount(); ok {
		_spec.SetField(generationmodelinvocation.FieldCandidateCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCandidateCount(); ok {
		_spec.AddField(generationmodelinvocation.FieldCandidateCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AttemptNumber(); ok {
		_spec.SetField(generationmodelinvocation.FieldAttemptNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptNumber(); ok {
		_spec.AddField(generationmodelinvocation.FieldAttemptNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AttemptBudget(); ok {
		_spec.SetField(generationmodelinvocation.FieldAttemptBudget, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptBudget(); ok {
		_spec.AddField(generationmodelinvocation.FieldAttemptBudget, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(generationmodelinvocation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(generationmodelinvocation.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.PromptHash(); ok {
		_spec.SetField(generationmodelinvocation.FieldPromptHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReferenceImages(); ok {
		_spec.SetField(generationmodelinvocation.FieldReferenceImages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedReferenceImages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, generationmodelinvocation.FieldReferenceImages, value)
		})
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(generationmodelinvocation.FieldSize, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quality(); ok {
		_spec.SetField(generationmodelinvocation.FieldQuality, field.TypeString, value)
	}
	if value, ok := _u.mutation.HTTPStatus(); ok {
		_spec.SetField(generationmodelinvocation.FieldHTTPStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHTTPStatus(); ok {
		_spec.AddField(generationmodelinvocation.FieldHTTPStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(generationmodelinvocation.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(generationmodelinvocation.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResponseImageCount(); ok {
		_spec.SetField(generationmodelinvocation.FieldResponseImageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResponseImageCount(); ok {
		_spec.AddField(generationmodelinvocation.FieldResponseImageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(generationmodelinvocation.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestedAt(); ok {
		_spec.SetField(generationmodelinvocation.FieldRequestedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(generationmodelinvocation.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(generationmodelinvocation.FieldCompletedAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{generationmodelinvocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GenerationModelInvocationUpdateOne is the builder for updating a single GenerationModelInvocation entity.
type GenerationModelInvocationUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *GenerationModelInvocationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetTaskID sets the "task_id" field.
func (_u *GenerationModelInvocationUpdateOne) SetTaskID(v uuid.UUID) *GenerationModelInvocationUpdateOne {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillableTaskID(v *uuid.UUID) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetGenerationImageID sets the "generation_image_id" field.
func (_u *GenerationModelInvocationUpdateOne) SetGenerationImageID(v string) *GenerationModelInvocationUpdateOne {
	_u.mutation.SetGenerationImageID(v)
	return _u
}

// SetNillableGenerationImageID sets the "generation_image_id" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillableGenerationImageID(v *string) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetGenerationImageID(*v)
	}
	return _u
}

// SetImageNumber sets the "image_number" field.
func (_u *GenerationModelInvocationUpdateOne) SetImageNumber(v int) *GenerationModelInvocationUpdateOne {
	_u.mutation.ResetImageNumber()
	_u.mutation.SetImageNumber(v)
	return _u
}

// SetNillableImageNumber sets the "image_number" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillableImageNumber(v *int) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetImageNumber(*v)
	}
	return _u
}

// AddImageNumber adds value to the "image_number" field.
func (_u *GenerationModelInvocationUpdateOne) AddImageNumber(v int) *GenerationModelInvocationUpdateOne {
	_u.mutation.AddImageNumber(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *GenerationModelInvocationUpdateOne) SetUserID(v uuid.UUID) *GenerationModelInvocationUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillableUserID(v *uuid.UUID) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *GenerationModelInvocationUpdateOne) SetUsername(v string) *GenerationModelInvocationUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillableUsername(v *string) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetUserEmail sets the "user_email" field.
func (_u *GenerationModelInvocationUpdateOne) SetUserEmail(v string) *GenerationModelInvocationUpdateOne {
	_u.mutation.SetUserEmail(v)
	return _u
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillableUserEmail(v *string) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetUserEmail(*v)
	}
	return _u
}

// SetUserRole sets the "user_role" field.
func (_u *GenerationModelInvocationUpdateOne) SetUserRole(v string) *GenerationModelInvocationUpdateOne {
	_u.mutation.SetUserRole(v)
	return _u
}

// SetNillableUserRole sets the "user_role" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillableUserRole(v *string) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetUserRole(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *GenerationModelInvocationUpdateOne) SetChannelID(v uuid.UUID) *GenerationModelInvocationUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillableChannelID(v *uuid.UUID) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// ClearChannelID clears the value of the "channel_id" field.
func (_u *GenerationModelInvocationUpdateOne) ClearChannelID() *GenerationModelInvocationUpdateOne {
	_u.mutation.ClearChannelID()
	return _u
}

// SetChannelName sets the "channel_name" field.
func (_u *GenerationModelInvocationUpdateOne) SetChannelName(v string) *GenerationModelInvocationUpdateOne {
	_u.mutation.SetChannelName(v)
	return _u
}

// SetNillableChannelName sets the "channel_name" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillableChannelName(v *string) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetChannelName(*v)
	}
	return _u
}

// SetAPIBaseURL sets the "api_base_url" field.
func (_u *GenerationModelInvocationUpdateOne) SetAPIBaseURL(v string) *GenerationModelInvocationUpdateOne {
	_u.mutation.SetAPIBaseURL(v)
	return _u
}

// SetNillableAPIBaseURL sets the "api_base_url" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillableAPIBaseURL(v *string) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetAPIBaseURL(*v)
	}
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *GenerationModelInvocationUpdateOne) SetProtocol(v string) *GenerationModelInvocationUpdateOne {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillableProtocol(v *string) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *GenerationModelInvocationUpdateOne) SetModelID(v string) *GenerationModelInvocationUpdateOne {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillableModelID(v *string) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetCandidateIndex sets the "candidate_index" field.
func (_u *GenerationModelInvocationUpdateOne) SetCandidateIndex(v int) *GenerationModelInvocationUpdateOne {
	_u.mutation.ResetCandidateIndex()
	_u.mutation.SetCandidateIndex(v)
	return _u
}

// SetNillableCandidateIndex sets the "candidate_index" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillableCandidateIndex(v *int) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetCandidateIndex(*v)
	}
	return _u
}

// AddCandidateIndex adds value to the "candidate_index" field.
func (_u *GenerationModelInvocationUpdateOne) AddCandidateIndex(v int) *GenerationModelInvocationUpdateOne {
	_u.mutation.AddCandidateIndex(v)
	return _u
}

// SetCandidateCount sets the "candidate_count" field.
func (_u *GenerationModelInvocationUpdateOne) SetCandidateCount(v int) *GenerationModelInvocationUpdateOne {
	_u.mutation.ResetCandidateCount()
	_u.mutation.SetCandidateCount(v)
	return _u
}

// SetNillableCandidateCount sets the "candidate_count" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillableCandidateCount(v *int) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetCandidateCount(*v)
	}
	return _u
}

// AddCandidateCount adds value to the "candidate_count" field.
func (_u *GenerationModelInvocationUpdateOne) AddCandidateCount(v int) *GenerationModelInvocationUpdateOne {
	_u.mutation.AddCandidateCount(v)
	return _u
}

// SetAttemptNumber sets the "attempt_number" field.
func (_u *GenerationModelInvocationUpdateOne) SetAttemptNumber(v int) *GenerationModelInvocationUpdateOne {
	_u.mutation.ResetAttemptNumber()
	_u.mutation.SetAttemptNumber(v)
	return _u
}

// SetNillableAttemptNumber sets the "attempt_number" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillableAttemptNumber(v *int) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetAttemptNumber(*v)
	}
	return _u
}

// AddAttemptNumber adds value to the "attempt_number" field.
func (_u *GenerationModelInvocationUpdateOne) AddAttemptNumber(v int) *GenerationModelInvocationUpdateOne {
	_u.mutation.AddAttemptNumber(v)
	return _u
}

// SetAttemptBudget sets the "attempt_budget" field.
func (_u *GenerationModelInvocationUpdateOne) SetAttemptBudget(v int) *GenerationModelInvocationUpdateOne {
	_u.mutation.ResetAttemptBudget()
	_u.mutation.SetAttemptBudget(v)
	return _u
}

// SetNillableAttemptBudget sets the "attempt_budget" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillableAttemptBudget(v *int) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetAttemptBudget(*v)
	}
	return _u
}

// AddAttemptBudget adds value to the "attempt_budget" field.
func (_u *GenerationModelInvocationUpdateOne) AddAttemptBudget(v int) *GenerationModelInvocationUpdateOne {
	_u.mutation.AddAttemptBudget(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *GenerationModelInvocationUpdateOne) SetStatus(v string) *GenerationModelInvocationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillableStatus(v *string) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *GenerationModelInvocationUpdateOne) SetPrompt(v string) *GenerationModelInvocationUpdateOne {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillablePrompt(v *string) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetPromptHash sets the "prompt_hash" field.
func (_u *GenerationModelInvocationUpdateOne) SetPromptHash(v string) *GenerationModelInvocationUpdateOne {
	_u.mutation.SetPromptHash(v)
	return _u
}

// SetNillablePromptHash sets the "prompt_hash" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillablePromptHash(v *string) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetPromptHash(*v)
	}
	return _u
}

// SetReferenceImages sets the "reference_images" field.
func (_u *GenerationModelInvocationUpdateOne) SetReferenceImages(v []types.ModelInvocationReference) *GenerationModelInvocationUpdateOne {
	_u.mutation.SetReferenceImages(v)
	return _u
}

// AppendReferenceImages appends value to the "reference_images" field.
func (_u *GenerationModelInvocationUpdateOne) AppendReferenceImages(v []types.ModelInvocationReference) *GenerationModelInvocationUpdateOne {
	_u.mutation.AppendReferenceImages(v)
	return _u
}

// SetSize sets the "size" field.
func (_u *GenerationModelInvocationUpdateOne) SetSize(v string) *GenerationModelInvocationUpdateOne {
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillableSize(v *string) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// SetQuality sets the "quality" field.
func (_u *GenerationModelInvocationUpdateOne) SetQuality(v string) *GenerationModelInvocationUpdateOne {
	_u.mutation.SetQuality(v)
	return _u
}

// SetNillableQuality sets the "quality" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillableQuality(v *string) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetQuality(*v)
	}
	return _u
}

// SetHTTPStatus sets the "http_status" field.
func (_u *GenerationModelInvocationUpdateOne) SetHTTPStatus(v int) *GenerationModelInvocationUpdateOne {
	_u.mutation.ResetHTTPStatus()
	_u.mutation.SetHTTPStatus(v)
	return _u
}

// SetNillableHTTPStatus sets the "http_status" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillableHTTPStatus(v *int) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetHTTPStatus(*v)
	}
	return _u
}

// AddHTTPStatus adds value to the "http_status" field.
func (_u *GenerationModelInvocationUpdateOne) AddHTTPStatus(v int) *GenerationModelInvocationUpdateOne {
	_u.mutation.AddHTTPStatus(v)
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *GenerationModelInvocationUpdateOne) SetLatencyMs(v int) *GenerationModelInvocationUpdateOne {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillableLatencyMs(v *int) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *GenerationModelInvocationUpdateOne) AddLatencyMs(v int) *GenerationModelInvocationUpdateOne {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// SetResponseImageCount sets the "response_image_count" field.
func (_u *GenerationModelInvocationUpdateOne) SetResponseImageCount(v int) *GenerationModelInvocationUpdateOne {
	_u.mutation.ResetResponseImageCount()
	_u.mutation.SetResponseImageCount(v)
	return _u
}

// SetNillableResponseImageCount sets the "response_image_count" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillableResponseImageCount(v *int) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetResponseImageCount(*v)
	}
	return _u
}

// AddResponseImageCount adds value to the "response_image_count" field.
func (_u *GenerationModelInvocationUpdateOne) AddResponseImageCount(v int) *GenerationModelInvocationUpdateOne {
	_u.mutation.AddResponseImageCount(v)
	return _u
}

// SetError sets the "error" field.
func (_u *GenerationModelInvocationUpdateOne) SetError(v string) *GenerationModelInvocationUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillableError(v *string) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetRequestedAt sets the "requested_at" field.
func (_u *GenerationModelInvocationUpdateOne) SetRequestedAt(v time.Time) *GenerationModelInvocationUpdateOne {
	_u.mutation.SetRequestedAt(v)
	return _u
}

// SetNillableRequestedAt sets the "requested_at" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillableRequestedAt(v *time.Time) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetRequestedAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *GenerationModelInvocationUpdateOne) SetCompletedAt(v time.Time) *GenerationModelInvocationUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *GenerationModelInvocationUpdateOne) SetNillableCompletedAt(v *time.Time) *GenerationModelInvocationUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *GenerationModelInvocationUpdateOne) ClearCompletedAt() *GenerationModelInvocationUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the GenerationModelInvocationMutation object of the builder.
func (_u *GenerationModelInvocationUpdateOne) Mutation() *GenerationModelInvocationMutation {
	return _u.mutation
}

// Where appends a list predicates to the GenerationModelInvocationUpdate builder.
func (_u *GenerationModelInvocationUpdateOne) Where(ps ...predicate.GenerationModelInvocation) *GenerationModelInvocationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GenerationModelInvocationUpdateOne) Select(field string, fields ...string) *GenerationModelInvocationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GenerationModelInvocation entity.
func (_u *GenerationModelInvocationUpdateOne) Save(ctx context.Context) (*GenerationModelInvocation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GenerationModelInvocationUpdateOne) SaveX(ctx context.Context) *GenerationModelInvocation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GenerationModelInvocationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GenerationModelInvocationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *GenerationModelInvocationUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *GenerationModelInvocationUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *GenerationModelInvocationUpdateOne) sqlSave(ctx context.Context) (_node *GenerationModelInvocation, err error) {
	_spec := sqlgraph.NewUpdateSpec(generationmodelinvocation.Table, generationmodelinvocation.Columns, sqlgraph.NewFieldSpec(generationmodelinvocation.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "GenerationModelInvocation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, generationmodelinvocation.FieldID)
		for _, f := range fields {
			if !generationmodelinvocation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != generationmodelinvocation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(generationmodelinvocation.FieldTaskID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.GenerationImageID(); ok {
		_spec.SetField(generationmodelinvocation.FieldGenerationImageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImageNumber(); ok {
		_spec.SetField(generationmodelinvocation.FieldImageNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedImageNumber(); ok {
		_spec.AddField(generationmodelinvocation.FieldImageNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(generationmodelinvocation.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(generationmodelinvocation.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserEmail(); ok {
		_spec.SetField(generationmodelinvocation.FieldUserEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserRole(); ok {
		_spec.SetField(generationmodelinvocation.FieldUserRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(generationmodelinvocation.FieldChannelID, field.TypeUUID, value)
	}
	if _u.mutation.ChannelIDCleared() {
		_spec.ClearField(generationmodelinvocation.FieldChannelID, field.TypeUUID)
	}
	if value, ok := _u.mutation.ChannelName(); ok {
		_spec.SetField(generationmodelinvocation.FieldChannelName, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIBaseURL(); ok {
		_spec.SetField(generationmodelinvocation.FieldAPIBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(generationmodelinvocation.FieldProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(generationmodelinvocation.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CandidateIndex(); ok {
		_spec.SetField(generationmodelinvocation.FieldCandidateIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCandidateIndex(); ok {
		_spec.AddField(generationmodelinvocation.FieldCandidateIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CandidateCount(); ok {
		_spec.SetField(generationmodelinvocation.FieldCandidateCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCandidateCount(); ok {
		_spec.AddField(generationmodelinvocation.FieldCandidateCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AttemptNumber(); ok {
		_spec.SetField(generationmodelinvocation.FieldAttemptNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptNumber(); ok {
		_spec.AddField(generationmodelinvocation.FieldAttemptNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AttemptBudget(); ok {
		_spec.SetField(generationmodelinvocation.FieldAttemptBudget, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptBudget(); ok {
		_spec.AddField(generationmodelinvocation.FieldAttemptBudget, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(generationmodelinvocation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(generationmodelinvocation.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.PromptHash(); ok {
		_spec.SetField(generationmodelinvocation.FieldPromptHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReferenceImages(); ok {
		_spec.SetField(generationmodelinvocation.FieldReferenceImages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedReferenceImages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, generationmodelinvocation.FieldReferenceImages, value)
		})
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(generationmodelinvocation.FieldSize, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quality(); ok {
		_spec.SetField(generationmodelinvocation.FieldQuality, field.TypeString, value)
	}
	if value, ok := _u.mutation.HTTPStatus(); ok {
		_spec.SetField(generationmodelinvocation.FieldHTTPStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHTTPStatus(); ok {
		_spec.AddField(generationmodelinvocation.FieldHTTPStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(generationmodelinvocation.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(generationmodelinvocation.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResponseImageCount(); ok {
		_spec.SetField(generationmodelinvocation.FieldResponseImageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResponseImageCount(); ok {
		_spec.AddField(generationmodelinvocation.FieldResponseImageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(generationmodelinvocation.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestedAt(); ok {
		_spec.SetField(generationmodelinvocation.FieldRequestedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(generationmodelinvocation.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(generationmodelinvocation.FieldCompletedAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &GenerationModelInvocation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{generationmodelinvocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
