// Code generated by ent, DO NOT EDIT.

package db

import (
	"bridal/backend/db/xhsnotesnapshot"
	"bridal/backend/ent/types"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// XHSNoteSnapshotCreate is the builder for creating a XHSNoteSnapshot entity.
type XHSNoteSnapshotCreate struct {
	config
	mutation *XHSNoteSnapshotMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTrackingID sets the "tracking_id" field.
func (_c *XHSNoteSnapshotCreate) SetTrackingID(v uuid.UUID) *XHSNoteSnapshotCreate {
	_c.mutation.SetTrackingID(v)
	return _c
}

// SetSequence sets the "sequence" field.
func (_c *XHSNoteSnapshotCreate) SetSequence(v int) *XHSNoteSnapshotCreate {
	_c.mutation.SetSequence(v)
	return _c
}

// SetTrigger sets the "trigger" field.
func (_c *XHSNoteSnapshotCreate) SetTrigger(v string) *XHSNoteSnapshotCreate {
	_c.mutation.SetTrigger(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *XHSNoteSnapshotCreate) SetStatus(v string) *XHSNoteSnapshotCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *XHSNoteSnapshotCreate) SetNillableStatus(v *string) *XHSNoteSnapshotCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *XHSNoteSnapshotCreate) SetError(v string) *XHSNoteSnapshotCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *XHSNoteSnapshotCreate) SetNillableError(v *string) *XHSNoteSnapshotCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetCapturedAt sets the "captured_at" field.
func (_c *XHSNoteSnapshotCreate) SetCapturedAt(v time.Time) *XHSNoteSnapshotCreate {
	_c.mutation.SetCapturedAt(v)
	return _c
}

// SetNillableCapturedAt sets the "captured_at" field if the given value is not nil.
func (_c *XHSNoteSnapshotCreate) SetNillableCapturedAt(v *time.Time) *XHSNoteSnapshotCreate {
	if v != nil {
		_c.SetCapturedAt(*v)
	}
	return _c
}

// SetWorkUpdatedAt sets the "work_updated_at" field.
func (_c *XHSNoteSnapshotCreate) SetWorkUpdatedAt(v string) *XHSNoteSnapshotCreate {
	_c.mutation.SetWorkUpdatedAt(v)
	return _c
}

// SetNillableWorkUpdatedAt sets the "work_updated_at" field if the given value is not nil.
func (_c *XHSNoteSnapshotCreate) SetNillableWorkUpdatedAt(v *string) *XHSNoteSnapshotCreate {
	if v != nil {
		_c.SetWorkUpdatedAt(*v)
	}
	return _c
}

// SetViews sets the "views" field.
func (_c *XHSNoteSnapshotCreate) SetViews(v int) *XHSNoteSnapshotCreate {
	_c.mutation.SetViews(v)
	return _c
}

// SetNillableViews sets the "views" field if the given value is not nil.
func (_c *XHSNoteSnapshotCreate) SetNillableViews(v *int) *XHSNoteSnapshotCreate {
	if v != nil {
		_c.SetViews(*v)
	}
	return _c
}

// SetLikes sets the "likes" field.
func (_c *XHSNoteSnapshotCreate) SetLikes(v int) *XHSNoteSnapshotCreate {
	_c.mutation.SetLikes(v)
	return _c
}

// SetNillableLikes sets the "likes" field if the given value is not nil.
func (_c *XHSNoteSnapshotCreate) SetNillableLikes(v *int) *XHSNoteSnapshotCreate {
	if v != nil {
		_c.SetLikes(*v)
	}
	return _c
}

// SetCollects sets the "collects" field.
func (_c *XHSNoteSnapshotCreate) SetCollects(v int) *XHSNoteSnapshotCreate {
	_c.mutation.SetCollects(v)
	return _c
}

// SetNillableCollects sets the "collects" field if the given value is not nil.
func (_c *XHSNoteSnapshotCreate) SetNillableCollects(v *int) *XHSNoteSnapshotCreate {
	if v != nil {
		_c.SetCollects(*v)
	}
	return _c
}

// SetComments sets the "comments" field.
func (_c *XHSNoteSnapshotCreate) SetComments(v int) *XHSNoteSnapshotCreate {
	_c.mutation.SetComments(v)
	return _c
}

// SetNillableComments sets the "comments" field if the given value is not nil.
func (_c *XHSNoteSnapshotCreate) SetNillableComments(v *int) *XHSNoteSnapshotCreate {
	if v != nil {
		_c.SetComments(*v)
	}
	return _c
}

// SetShares sets the "shares" field.
func (_c *XHSNoteSnapshotCreate) SetShares(v int) *XHSNoteSnapshotCreate {
	_c.mutation.SetShares(v)
	return _c
}

// SetNillableShares sets the "shares" field if the given value is not nil.
func (_c *XHSNoteSnapshotCreate) SetNillableShares(v *int) *XHSNoteSnapshotCreate {
	if v != nil {
		_c.SetShares(*v)
	}
	return _c
}

// SetAccountName sets the "account_name" field.
func (_c *XHSNoteSnapshotCreate) SetAccountName(v string) *XHSNoteSnapshotCreate {
	_c.mutation.SetAccountName(v)
	return _c
}

// SetNillableAccountName sets the "account_name" field if the given value is not nil.
func (_c *XHSNoteSnapshotCreate) SetNillableAccountName(v *string) *XHSNoteSnapshotCreate {
	if v != nil {
		_c.SetAccountName(*v)
	}
	return _c
}

// SetAccountAvatar sets the "account_avatar" field.
func (_c *XHSNoteSnapshotCreate) SetAccountAvatar(v string) *XHSNoteSnapshotCreate {
	_c.mutation.SetAccountAvatar(v)
	return _c
}

// SetNillableAccountAvatar sets the "account_avatar" field if the given value is not nil.
func (_c *XHSNoteSnapshotCreate) SetNillableAccountAvatar(v *string) *XHSNoteSnapshotCreate {
	if v != nil {
		_c.SetAccountAvatar(*v)
	}
	return _c
}

// SetAccountDisplayID sets the "account_display_id" field.
func (_c *XHSNoteSnapshotCreate) SetAccountDisplayID(v string) *XHSNoteSnapshotCreate {
	_c.mutation.SetAccountDisplayID(v)
	return _c
}

// SetNillableAccountDisplayID sets the "account_display_id" field if the given value is not nil.
func (_c *XHSNoteSnapshotCreate) SetNillableAccountDisplayID(v *string) *XHSNoteSnapshotCreate {
	if v != nil {
		_c.SetAccountDisplayID(*v)
	}
	return _c
}

// SetAccountUserID sets the "account_user_id" field.
func (_c *XHSNoteSnapshotCreate) SetAccountUserID(v string) *XHSNoteSnapshotCreate {
	_c.mutation.SetAccountUserID(v)
	return _c
}

// SetNillableAccountUserID sets the "account_user_id" field if the given value is not nil.
func (_c *XHSNoteSnapshotCreate) SetNillableAccountUserID(v *string) *XHSNoteSnapshotCreate {
	if v != nil {
		_c.SetAccountUserID(*v)
	}
	return _c
}

// SetAccountDescription sets the "account_description" field.
func (_c *XHSNoteSnapshotCreate) SetAccountDescription(v string) *XHSNoteSnapshotCreate {
	_c.mutation.SetAccountDescription(v)
	return _c
}

// SetNillableAccountDescription sets the "account_description" field if the given value is not nil.
func (_c *XHSNoteSnapshotCreate) SetNillableAccountDescription(v *string) *XHSNoteSnapshotCreate {
	if v != nil {
		_c.SetAccountDescription(*v)
	}
	return _c
}

// SetAccountFans sets the "account_fans" field.
func (_c *XHSNoteSnapshotCreate) SetAccountFans(v int) *XHSNoteSnapshotCreate {
	_c.mutation.SetAccountFans(v)
	return _c
}

// SetNillableAccountFans sets the "account_fans" field if the given value is not nil.
func (_c *XHSNoteSnapshotCreate) SetNillableAccountFans(v *int) *XHSNoteSnapshotCreate {
	if v != nil {
		_c.SetAccountFans(*v)
	}
	return _c
}

// SetAccountTotalWorks sets the "account_total_works" field.
func (_c *XHSNoteSnapshotCreate) SetAccountTotalWorks(v int) *XHSNoteSnapshotCreate {
	_c.mutation.SetAccountTotalWorks(v)
	return _c
}

// SetNillableAccountTotalWorks sets the "account_total_works" field if the given value is not nil.
func (_c *XHSNoteSnapshotCreate) SetNillableAccountTotalWorks(v *int) *XHSNoteSnapshotCreate {
	if v != nil {
		_c.SetAccountTotalWorks(*v)
	}
	return _c
}

// SetAccountLikes sets the "account_likes" field.
func (_c *XHSNoteSnapshotCreate) SetAccountLikes(v int) *XHSNoteSnapshotCreate {
	_c.mutation.SetAccountLikes(v)
	return _c
}

// SetNillableAccountLikes sets the "account_likes" field if the given value is not nil.
func (_c *XHSNoteSnapshotCreate) SetNillableAccountLikes(v *int) *XHSNoteSnapshotCreate {
	if v != nil {
		_c.SetAccountLikes(*v)
	}
	return _c
}

// SetAccountCollects sets the "account_collects" field.
func (_c *XHSNoteSnapshotCreate) SetAccountCollects(v int) *XHSNoteSnapshotCreate {
	_c.mutation.SetAccountCollects(v)
	return _c
}

// SetNillableAccountCollects sets the "account_collects" field if the given value is not nil.
func (_c *XHSNoteSnapshotCreate) SetNillableAccountCollects(v *int) *XHSNoteSnapshotCreate {
	if v != nil {
		_c.SetAccountCollects(*v)
	}
	return _c
}

// SetAccountFollows sets the "account_follows" field.
func (_c *XHSNoteSnapshotCreate) SetAccountFollows(v int) *XHSNoteSnapshotCreate {
	_c.mutation.SetAccountFollows(v)
	return _c
}

// SetNillableAccountFollows sets the "account_follows" field if the given value is not nil.
func (_c *XHSNoteSnapshotCreate) SetNillableAccountFollows(v *int) *XHSNoteSnapshotCreate {
	if v != nil {
		_c.SetAccountFollows(*v)
	}
	return _c
}

// SetAccountUpdatedAt sets the "account_updated_at" field.
func (_c *XHSNoteSnapshotCreate) SetAccountUpdatedAt(v string) *XHSNoteSnapshotCreate {
	_c.mutation.SetAccountUpdatedAt(v)
	return _c
}

// SetNillableAccountUpdatedAt sets the "account_updated_at" field if the given value is not nil.
func (_c *XHSNoteSnapshotCreate) SetNillableAccountUpdatedAt(v *string) *XHSNoteSnapshotCreate {
	if v != nil {
		_c.SetAccountUpdatedAt(*v)
	}
	return _c
}

// SetSimilarAccounts sets the "similar_accounts" field.
func (_c *XHSNoteSnapshotCreate) SetSimilarAccounts(v []types.XHSSimilarAccount) *XHSNoteSnapshotCreate {
	_c.mutation.SetSimilarAccounts(v)
	return _c
}

// SetSimilarSummary sets the "similar_summary" field.
func (_c *XHSNoteSnapshotCreate) SetSimilarSummary(v string) *XHSNoteSnapshotCreate {
	_c.mutation.SetSimilarSummary(v)
	return _c
}

// SetNillableSimilarSummary sets the "similar_summary" field if the given value is not nil.
func (_c *XHSNoteSnapshotCreate) SetNillableSimilarSummary(v *string) *XHSNoteSnapshotCreate {
	if v != nil {
		_c.SetSimilarSummary(*v)
	}
	return _c
}

// SetLinkEpoch sets the "link_epoch" field.
func (_c *XHSNoteSnapshotCreate) SetLinkEpoch(v int) *XHSNoteSnapshotCreate {
	_c.mutation.SetLinkEpoch(v)
	return _c
}

// SetNillableLinkEpoch sets the "link_epoch" field if the given value is not nil.
func (_c *XHSNoteSnapshotCreate) SetNillableLinkEpoch(v *int) *XHSNoteSnapshotCreate {
	if v != nil {
		_c.SetLinkEpoch(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *XHSNoteSnapshotCreate) SetCreatedAt(v time.Time) *XHSNoteSnapshotCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *XHSNoteSnapshotCreate) SetNillableCreatedAt(v *time.Time) *XHSNoteSnapshotCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *XHSNoteSnapshotCreate) SetID(v uuid.UUID) *XHSNoteSnapshotCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *XHSNoteSnapshotCreate) SetNillableID(v *uuid.UUID) *XHSNoteSnapshotCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the XHSNoteSnapshotMutation object of the builder.
func (_c *XHSNoteSnapshotCreate) Mutation() *XHSNoteSnapshotMutation {
	return _c.mutation
}

// Save creates the XHSNoteSnapshot in the database.
func (_c *XHSNoteSnapshotCreate) Save(ctx context.Context) (*XHSNoteSnapshot, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *XHSNoteSnapshotCreate) SaveX(ctx context.Context) *XHSNoteSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *XHSNoteSnapshotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *XHSNoteSnapshotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *XHSNoteSnapshotCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := xhsnotesnapshot.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Error(); !ok {
		v := xhsnotesnapshot.DefaultError
		_c.mutation.SetError(v)
	}
	if _, ok := _c.mutation.CapturedAt(); !ok {
		v := xhsnotesnapshot.DefaultCapturedAt()
		_c.mutation.SetCapturedAt(v)
	}
	if _, ok := _c.mutation.WorkUpdatedAt(); !ok {
		v := xhsnotesnapshot.DefaultWorkUpdatedAt
		_c.mutation.SetWorkUpdatedAt(v)
	}
	if _, ok := _c.mutation.Views(); !ok {
		v := xhsnotesnapshot.DefaultViews
		_c.mutation.SetViews(v)
	}
	if _, ok := _c.mutation.Likes(); !ok {
		v := xhsnotesnapshot.DefaultLikes
		_c.mutation.SetLikes(v)
	}
	if _, ok := _c.mutation.Collects(); !ok {
		v := xhsnotesnapshot.DefaultCollects
		_c.mutation.SetCollects(v)
	}
	if _, ok := _c.mutation.Comments(); !ok {
		v := xhsnotesnapshot.DefaultComments
		_c.mutation.SetComments(v)
	}
	if _, ok := _c.mutation.Shares(); !ok {
		v := xhsnotesnapshot.DefaultShares
		_c.mutation.SetShares(v)
	}
	if _, ok := _c.mutation.AccountName(); !ok {
		v := xhsnotesnapshot.DefaultAccountName
		_c.mutation.SetAccountName(v)
	}
	if _, ok := _c.mutation.AccountAvatar(); !ok {
		v := xhsnotesnapshot.DefaultAccountAvatar
		_c.mutation.SetAccountAvatar(v)
	}
	if _, ok := _c.mutation.AccountDisplayID(); !ok {
		v := xhsnotesnapshot.DefaultAccountDisplayID
		_c.mutation.SetAccountDisplayID(v)
	}
	if _, ok := _c.mutation.AccountUserID(); !ok {
		v := xhsnotesnapshot.DefaultAccountUserID
		_c.mutation.SetAccountUserID(v)
	}
	if _, ok := _c.mutation.AccountDescription(); !ok {
		v := xhsnotesnapshot.DefaultAccountDescription
		_c.mutation.SetAccountDescription(v)
	}
	if _, ok := _c.mutation.AccountFans(); !ok {
		v := xhsnotesnapshot.DefaultAccountFans
		_c.mutation.SetAccountFans(v)
	}
	if _, ok := _c.mutation.AccountTotalWorks(); !ok {
		v := xhsnotesnapshot.DefaultAccountTotalWorks
		_c.mutation.SetAccountTotalWorks(v)
	}
	if _, ok := _c.mutation.AccountLikes(); !ok {
		v := xhsnotesnapshot.DefaultAccountLikes
		_c.mutation.SetAccountLikes(v)
	}
	if _, ok := _c.mutation.AccountCollects(); !ok {
		v := xhsnotesnapshot.DefaultAccountCollects
		_c.mutation.SetAccountCollects(v)
	}
	if _, ok := _c.mutation.AccountFollows(); !ok {
		v := xhsnotesnapshot.DefaultAccountFollows
		_c.mutation.SetAccountFollows(v)
	}
	if _, ok := _c.mutation.AccountUpdatedAt(); !ok {
		v := xhsnotesnapshot.DefaultAccountUpdatedAt
		_c.mutation.SetAccountUpdatedAt(v)
	}
	if _, ok := _c.mutation.SimilarAccounts(); !ok {
		v := xhsnotesnapshot.DefaultSimilarAccounts
		_c.mutation.SetSimilarAccounts(v)
	}
	if _, ok := _c.mutation.SimilarSummary(); !ok {
		v := xhsnotesnapshot.DefaultSimilarSummary
		_c.mutation.SetSimilarSummary(v)
	}
	if _, ok := _c.mutation.LinkEpoch(); !ok {
		v := xhsnotesnapshot.DefaultLinkEpoch
		_c.mutation.SetLinkEpoch(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := xhsnotesnapshot.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := xhsnotesnapshot.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *XHSNoteSnapshotCreate) check() error {
	if _, ok := _c.mutation.TrackingID(); !ok {
		return &ValidationError{Name: "tracking_id", err: errors.New(`db: missing required field "XHSNoteSnapshot.tracking_id"`)}
	}
	if _, ok := _c.mutation.Sequence(); !ok {
		return &ValidationError{Name: "sequence", err: errors.New(`db: missing required field "XHSNoteSnapshot.sequence"`)}
	}
	if _, ok := _c.mutation.Trigger(); !ok {
		return &ValidationError{Name: "trigger", err: errors.New(`db: missing required field "XHSNoteSnapshot.trigger"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`db: missing required field "XHSNoteSnapshot.status"`)}
	}
	if _, ok := _c.mutation.Error(); !ok {
		return &ValidationError{Name: "error", err: errors.New(`db: missing required field "XHSNoteSnapshot.error"`)}
	}
	if _, ok := _c.mutation.CapturedAt(); !ok {
		return &ValidationError{Name: "captured_at", err: errors.New(`db: missing required field "XHSNoteSnapshot.captured_at"`)}
	}
	if _, ok := _c.mutation.WorkUpdatedAt(); !ok {
		return &ValidationError{Name: "work_updated_at", err: errors.New(`db: missing required field "XHSNoteSnapshot.work_updated_at"`)}
	}
	if _, ok := _c.mutation.Views(); !ok {
		return &ValidationError{Name: "views", err: errors.New(`db: missing required field "XHSNoteSnapshot.views"`)}
	}
	if _, ok := _c.mutation.Likes(); !ok {
		return &ValidationError{Name: "likes", err: errors.New(`db: missing required field "XHSNoteSnapshot.likes"`)}
	}
	if _, ok := _c.mutation.Collects(); !ok {
		return &ValidationError{Name: "collects", err: errors.New(`db: missing required field "XHSNoteSnapshot.collects"`)}
	}
	if _, ok := _c.mutation.Comments(); !ok {
		return &ValidationError{Name: "comments", err: errors.New(`db: missing required field "XHSNoteSnapshot.comments"`)}
	}
	if _, ok := _c.mutation.Shares(); !ok {
		return &ValidationError{Name: "shares", err: errors.New(`db: missing required field "XHSNoteSnapshot.shares"`)}
	}
	if _, ok := _c.mutation.AccountName(); !ok {
		return &ValidationError{Name: "account_name", err: errors.New(`db: missing required field "XHSNoteSnapshot.account_name"`)}
	}
	if _, ok := _c.mutation.AccountAvatar(); !ok {
		return &ValidationError{Name: "account_avatar", err: errors.New(`db: missing required field "XHSNoteSnapshot.account_avatar"`)}
	}
	if _, ok := _c.mutation.AccountDisplayID(); !ok {
		return &ValidationError{Name: "account_display_id", err: errors.New(`db: missing required field "XHSNoteSnapshot.account_display_id"`)}
	}
	if _, ok := _c.mutation.AccountUserID(); !ok {
		return &ValidationError{Name: "account_user_id", err: errors.New(`db: missing required field "XHSNoteSnapshot.account_user_id"`)}
	}
	if _, ok := _c.mutation.AccountDescription(); !ok {
		return &ValidationError{Name: "account_description", err: errors.New(`db: missing required field "XHSNoteSnapshot.account_description"`)}
	}
	if _, ok := _c.mutation.AccountFans(); !ok {
		return &ValidationError{Name: "account_fans", err: errors.New(`db: missing required field "XHSNoteSnapshot.account_fans"`)}
	}
	if _, ok := _c.mutation.AccountTotalWorks(); !ok {
		return &ValidationError{Name: "account_total_works", err: errors.New(`db: missing required field "XHSNoteSnapshot.account_total_works"`)}
	}
	if _, ok := _c.mutation.AccountLikes(); !ok {
		return &ValidationError{Name: "account_likes", err: errors.New(`db: missing required field "XHSNoteSnapshot.account_likes"`)}
	}
	if _, ok := _c.mutation.AccountCollects(); !ok {
		return &ValidationError{Name: "account_collects", err: errors.New(`db: missing required field "XHSNoteSnapshot.account_collects"`)}
	}
	if _, ok := _c.mutation.AccountFollows(); !ok {
		return &ValidationError{Name: "account_follows", err: errors.New(`db: missing required field "XHSNoteSnapshot.account_follows"`)}
	}
	if _, ok := _c.mutation.AccountUpdatedAt(); !ok {
		return &ValidationError{Name: "account_updated_at", err: errors.New(`db: missing required field "XHSNoteSnapshot.account_updated_at"`)}
	}
	if _, ok := _c.mutation.SimilarAccounts(); !ok {
		return &ValidationError{Name: "similar_accounts", err: errors.New(`db: missing required field "XHSNoteSnapshot.similar_accounts"`)}
	}
	if _, ok := _c.mutation.SimilarSummary(); !ok {
		return &ValidationError{Name: "similar_summary", err: errors.New(`db: missing required field "XHSNoteSnapshot.similar_summary"`)}
	}
	if _, ok := _c.mutation.LinkEpoch(); !ok {
		return &ValidationError{Name: "link_epoch", err: errors.New(`db: missing required field "XHSNoteSnapshot.link_epoch"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`db: missing required field "XHSNoteSnapshot.created_at"`)}
	}
	return nil
}

func (_c *XHSNoteSnapshotCreate) sqlSave(ctx context.Context) (*XHSNoteSnapshot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *XHSNoteSnapshotCreate) createSpec() (*XHSNoteSnapshot, *sqlgraph.CreateSpec) {
	var (
		_node = &XHSNoteSnapshot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(xhsnotesnapshot.Table, sqlgraph.NewFieldSpec(xhsnotesnapshot.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TrackingID(); ok {
		_spec.SetField(xhsnotesnapshot.FieldTrackingID, field.TypeUUID, value)
		_node.TrackingID = value
	}
	if value, ok := _c.mutation.Sequence(); ok {
		_spec.SetField(xhsnotesnapshot.FieldSequence, field.TypeInt, value)
		_node.Sequence = value
	}
	if value, ok := _c.mutation.Trigger(); ok {
		_spec.SetField(xhsnotesnapshot.FieldTrigger, field.TypeString, value)
		_node.Trigger = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(xhsnotesnapshot.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(xhsnotesnapshot.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := _c.mutation.CapturedAt(); ok {
		_spec.SetField(xhsnotesnapshot.FieldCapturedAt, field.TypeTime, value)
		_node.CapturedAt = value
	}
	if value, ok := _c.mutation.WorkUpdatedAt(); ok {
		_spec.SetField(xhsnotesnapshot.FieldWorkUpdatedAt, field.TypeString, value)
		_node.WorkUpdatedAt = value
	}
	if value, ok := _c.mutation.Views(); ok {
		_spec.SetField(xhsnotesnapshot.FieldViews, field.TypeInt, value)
		_node.Views = value
	}
	if value, ok := _c.mutation.Likes(); ok {
		_spec.SetField(xhsnotesnapshot.FieldLikes, field.TypeInt, value)
		_node.Likes = value
	}
	if value, ok := _c.mutation.Collects(); ok {
		_spec.SetField(xhsnotesnapshot.FieldCollects, field.TypeInt, value)
		_node.Collects = value
	}
	if value, ok := _c.mutation.Comments(); ok {
		_spec.SetField(xhsnotesnapshot.FieldComments, field.TypeInt, value)
		_node.Comments = value
	}
	if value, ok := _c.mutation.Shares(); ok {
		_spec.SetField(xhsnotesnapshot.FieldShares, field.TypeInt, value)
		_node.Shares = value
	}
	if value, ok := _c.mutation.AccountName(); ok {
		_spec.SetField(xhsnotesnapshot.FieldAccountName, field.TypeString, value)
		_node.AccountName = value
	}
	if value, ok := _c.mutation.AccountAvatar(); ok {
		_spec.SetField(xhsnotesnapshot.FieldAccountAvatar, field.TypeString, value)
		_node.AccountAvatar = value
	}
	if value, ok := _c.mutation.AccountDisplayID(); ok {
		_spec.SetField(xhsnotesnapshot.FieldAccountDisplayID, field.TypeString, value)
		_node.AccountDisplayID = value
	}
	if value, ok := _c.mutation.AccountUserID(); ok {
		_spec.SetField(xhsnotesnapshot.FieldAccountUserID, field.TypeString, value)
		_node.AccountUserID = value
	}
	if value, ok := _c.mutation.AccountDescription(); ok {
		_spec.SetField(xhsnotesnapshot.FieldAccountDescription, field.TypeString, value)
		_node.AccountDescription = value
	}
	if value, ok := _c.mutation.AccountFans(); ok {
		_spec.SetField(xhsnotesnapshot.FieldAccountFans, field.TypeInt, value)
		_node.AccountFans = value
	}
	if value, ok := _c.mutation.AccountTotalWorks(); ok {
		_spec.SetField(xhsnotesnapshot.FieldAccountTotalWorks, field.TypeInt, value)
		_node.AccountTotalWorks = value
	}
	if value, ok := _c.mutation.AccountLikes(); ok {
		_spec.SetField(xhsnotesnapshot.FieldAccountLikes, field.TypeInt, value)
		_node.AccountLikes = value
	}
	if value, ok := _c.mutation.AccountCollects(); ok {
		_spec.SetField(xhsnotesnapshot.FieldAccountCollects, field.TypeInt, value)
		_node.AccountCollects = value
	}
	if value, ok := _c.mutation.AccountFollows(); ok {
		_spec.SetField(xhsnotesnapshot.FieldAccountFollows, field.TypeInt, value)
		_node.AccountFollows = value
	}
	if value, ok := _c.mutation.AccountUpdatedAt(); ok {
		_spec.SetField(xhsnotesnapshot.FieldAccountUpdatedAt, field.TypeString, value)
		_node.AccountUpdatedAt = value
	}
	if value, ok := _c.mutation.SimilarAccounts(); ok {
		_spec.SetField(xhsnotesnapshot.FieldSimilarAccounts, field.TypeJSON, value)
		_node.SimilarAccounts = value
	}
	if value, ok := _c.mutation.SimilarSummary(); ok {
		_spec.SetField(xhsnotesnapshot.FieldSimilarSummary, field.TypeString, value)
		_node.SimilarSummary = value
	}
	if value, ok := _c.mutation.LinkEpoch(); ok {
		_spec.SetField(xhsnotesnapshot.FieldLinkEpoch, field.TypeInt, value)
		_node.LinkEpoch = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(xhsnotesnapshot.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.XHSNoteSnapshot.Create().
//		SetTrackingID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.XHSNoteSnapshotUpsert) {
//			SetTrackingID(v+v).
//		}).
//		Exec(ctx)
func (_c *XHSNoteSnapshotCreate) OnConflict(opts ...sql.ConflictOption) *XHSNoteSnapshotUpsertOne {
	_c.conflict = opts
	return &XHSNoteSnapshotUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.XHSNoteSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *XHSNoteSnapshotCreate) OnConflictColumns(columns ...string) *XHSNoteSnapshotUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &XHSNoteSnapshotUpsertOne{
		create: _c,
	}
}

type (
	// XHSNoteSnapshotUpsertOne is the builder for "upsert"-ing
	//  one XHSNoteSnapshot node.
	XHSNoteSnapshotUpsertOne struct {
		create *XHSNoteSnapshotCreate
	}

	// XHSNoteSnapshotUpsert is the "OnConflict" setter.
	XHSNoteSnapshotUpsert struct {
		*sql.UpdateSet
	}
)

// SetTrackingID sets the "tracking_id" field.
func (u *XHSNoteSnapshotUpsert) SetTrackingID(v uuid.UUID) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldTrackingID, v)
	return u
}

// UpdateTrackingID sets the "tracking_id" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateTrackingID() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldTrackingID)
	return u
}

// SetSequence sets the "sequence" field.
func (u *XHSNoteSnapshotUpsert) SetSequence(v int) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldSequence, v)
	return u
}

// UpdateSequence sets the "sequence" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateSequence() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldSequence)
	return u
}

// AddSequence adds v to the "sequence" field.
func (u *XHSNoteSnapshotUpsert) AddSequence(v int) *XHSNoteSnapshotUpsert {
	u.Add(xhsnotesnapshot.FieldSequence, v)
	return u
}

// SetTrigger sets the "trigger" field.
func (u *XHSNoteSnapshotUpsert) SetTrigger(v string) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldTrigger, v)
	return u
}

// UpdateTrigger sets the "trigger" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateTrigger() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldTrigger)
	return u
}

// SetStatus sets the "status" field.
func (u *XHSNoteSnapshotUpsert) SetStatus(v string) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateStatus() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldStatus)
	return u
}

// SetError sets the "error" field.
func (u *XHSNoteSnapshotUpsert) SetError(v string) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldError, v)
	return u
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateError() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldError)
	return u
}

// SetCapturedAt sets the "captured_at" field.
func (u *XHSNoteSnapshotUpsert) SetCapturedAt(v time.Time) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldCapturedAt, v)
	return u
}

// UpdateCapturedAt sets the "captured_at" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateCapturedAt() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldCapturedAt)
	return u
}

// SetWorkUpdatedAt sets the "work_updated_at" field.
func (u *XHSNoteSnapshotUpsert) SetWorkUpdatedAt(v string) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldWorkUpdatedAt, v)
	return u
}

// UpdateWorkUpdatedAt sets the "work_updated_at" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateWorkUpdatedAt() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldWorkUpdatedAt)
	return u
}

// SetViews sets the "views" field.
func (u *XHSNoteSnapshotUpsert) SetViews(v int) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldViews, v)
	return u
}

// UpdateViews sets the "views" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateViews() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldViews)
	return u
}

// AddViews adds v to the "views" field.
func (u *XHSNoteSnapshotUpsert) AddViews(v int) *XHSNoteSnapshotUpsert {
	u.Add(xhsnotesnapshot.FieldViews, v)
	return u
}

// SetLikes sets the "likes" field.
func (u *XHSNoteSnapshotUpsert) SetLikes(v int) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldLikes, v)
	return u
}

// UpdateLikes sets the "likes" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateLikes() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldLikes)
	return u
}

// AddLikes adds v to the "likes" field.
func (u *XHSNoteSnapshotUpsert) AddLikes(v int) *XHSNoteSnapshotUpsert {
	u.Add(xhsnotesnapshot.FieldLikes, v)
	return u
}

// SetCollects sets the "collects" field.
func (u *XHSNoteSnapshotUpsert) SetCollects(v int) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldCollects, v)
	return u
}

// UpdateCollects sets the "collects" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateCollects() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldCollects)
	return u
}

// AddCollects adds v to the "collects" field.
func (u *XHSNoteSnapshotUpsert) AddCollects(v int) *XHSNoteSnapshotUpsert {
	u.Add(xhsnotesnapshot.FieldCollects, v)
	return u
}

// SetComments sets the "comments" field.
func (u *XHSNoteSnapshotUpsert) SetComments(v int) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldComments, v)
	return u
}

// UpdateComments sets the "comments" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateComments() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldComments)
	return u
}

// AddComments adds v to the "comments" field.
func (u *XHSNoteSnapshotUpsert) AddComments(v int) *XHSNoteSnapshotUpsert {
	u.Add(xhsnotesnapshot.FieldComments, v)
	return u
}

// SetShares sets the "shares" field.
func (u *XHSNoteSnapshotUpsert) SetShares(v int) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldShares, v)
	return u
}

// UpdateShares sets the "shares" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateShares() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldShares)
	return u
}

// AddShares adds v to the "shares" field.
func (u *XHSNoteSnapshotUpsert) AddShares(v int) *XHSNoteSnapshotUpsert {
	u.Add(xhsnotesnapshot.FieldShares, v)
	return u
}

// SetAccountName sets the "account_name" field.
func (u *XHSNoteSnapshotUpsert) SetAccountName(v string) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldAccountName, v)
	return u
}

// UpdateAccountName sets the "account_name" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateAccountName() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldAccountName)
	return u
}

// SetAccountAvatar sets the "account_avatar" field.
func (u *XHSNoteSnapshotUpsert) SetAccountAvatar(v string) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldAccountAvatar, v)
	return u
}

// UpdateAccountAvatar sets the "account_avatar" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateAccountAvatar() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldAccountAvatar)
	return u
}

// SetAccountDisplayID sets the "account_display_id" field.
func (u *XHSNoteSnapshotUpsert) SetAccountDisplayID(v string) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldAccountDisplayID, v)
	return u
}

// UpdateAccountDisplayID sets the "account_display_id" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateAccountDisplayID() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldAccountDisplayID)
	return u
}

// SetAccountUserID sets the "account_user_id" field.
func (u *XHSNoteSnapshotUpsert) SetAccountUserID(v string) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldAccountUserID, v)
	return u
}

// UpdateAccountUserID sets the "account_user_id" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateAccountUserID() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldAccountUserID)
	return u
}

// SetAccountDescription sets the "account_description" field.
func (u *XHSNoteSnapshotUpsert) SetAccountDescription(v string) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldAccountDescription, v)
	return u
}

// UpdateAccountDescription sets the "account_description" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateAccountDescription() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldAccountDescription)
	return u
}

// SetAccountFans sets the "account_fans" field.
func (u *XHSNoteSnapshotUpsert) SetAccountFans(v int) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldAccountFans, v)
	return u
}

// UpdateAccountFans sets the "account_fans" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateAccountFans() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldAccountFans)
	return u
}

// AddAccountFans adds v to the "account_fans" field.
func (u *XHSNoteSnapshotUpsert) AddAccountFans(v int) *XHSNoteSnapshotUpsert {
	u.Add(xhsnotesnapshot.FieldAccountFans, v)
	return u
}

// SetAccountTotalWorks sets the "account_total_works" field.
func (u *XHSNoteSnapshotUpsert) SetAccountTotalWorks(v int) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldAccountTotalWorks, v)
	return u
}

// UpdateAccountTotalWorks sets the "account_total_works" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateAccountTotalWorks() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldAccountTotalWorks)
	return u
}

// AddAccountTotalWorks adds v to the "account_total_works" field.
func (u *XHSNoteSnapshotUpsert) AddAccountTotalWorks(v int) *XHSNoteSnapshotUpsert {
	u.Add(xhsnotesnapshot.FieldAccountTotalWorks, v)
	return u
}

// SetAccountLikes sets the "account_likes" field.
func (u *XHSNoteSnapshotUpsert) SetAccountLikes(v int) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldAccountLikes, v)
	return u
}

// UpdateAccountLikes sets the "account_likes" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateAccountLikes() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldAccountLikes)
	return u
}

// AddAccountLikes adds v to the "account_likes" field.
func (u *XHSNoteSnapshotUpsert) AddAccountLikes(v int) *XHSNoteSnapshotUpsert {
	u.Add(xhsnotesnapshot.FieldAccountLikes, v)
	return u
}

// SetAccountCollects sets the "account_collects" field.
func (u *XHSNoteSnapshotUpsert) SetAccountCollects(v int) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldAccountCollects, v)
	return u
}

// UpdateAccountCollects sets the "account_collects" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateAccountCollects() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldAccountCollects)
	return u
}

// AddAccountCollects adds v to the "account_collects" field.
func (u *XHSNoteSnapshotUpsert) AddAccountCollects(v int) *XHSNoteSnapshotUpsert {
	u.Add(xhsnotesnapshot.FieldAccountCollects, v)
	return u
}

// SetAccountFollows sets the "account_follows" field.
func (u *XHSNoteSnapshotUpsert) SetAccountFollows(v int) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldAccountFollows, v)
	return u
}

// UpdateAccountFollows sets the "account_follows" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateAccountFollows() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldAccountFollows)
	return u
}

// AddAccountFollows adds v to the "account_follows" field.
func (u *XHSNoteSnapshotUpsert) AddAccountFollows(v int) *XHSNoteSnapshotUpsert {
	u.Add(xhsnotesnapshot.FieldAccountFollows, v)
	return u
}

// SetAccountUpdatedAt sets the "account_updated_at" field.
func (u *XHSNoteSnapshotUpsert) SetAccountUpdatedAt(v string) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldAccountUpdatedAt, v)
	return u
}

// UpdateAccountUpdatedAt sets the "account_updated_at" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateAccountUpdatedAt() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldAccountUpdatedAt)
	return u
}

// SetSimilarAccounts sets the "similar_accounts" field.
func (u *XHSNoteSnapshotUpsert) SetSimilarAccounts(v []types.XHSSimilarAccount) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldSimilarAccounts, v)
	return u
}

// UpdateSimilarAccounts sets the "similar_accounts" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateSimilarAccounts() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldSimilarAccounts)
	return u
}

// SetSimilarSummary sets the "similar_summary" field.
func (u *XHSNoteSnapshotUpsert) SetSimilarSummary(v string) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldSimilarSummary, v)
	return u
}

// UpdateSimilarSummary sets the "similar_summary" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateSimilarSummary() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldSimilarSummary)
	return u
}

// SetLinkEpoch sets the "link_epoch" field.
func (u *XHSNoteSnapshotUpsert) SetLinkEpoch(v int) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldLinkEpoch, v)
	return u
}

// UpdateLinkEpoch sets the "link_epoch" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateLinkEpoch() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldLinkEpoch)
	return u
}

// AddLinkEpoch adds v to the "link_epoch" field.
func (u *XHSNoteSnapshotUpsert) AddLinkEpoch(v int) *XHSNoteSnapshotUpsert {
	u.Add(xhsnotesnapshot.FieldLinkEpoch, v)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *XHSNoteSnapshotUpsert) SetCreatedAt(v time.Time) *XHSNoteSnapshotUpsert {
	u.Set(xhsnotesnapshot.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsert) UpdateCreatedAt() *XHSNoteSnapshotUpsert {
	u.SetExcluded(xhsnotesnapshot.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.XHSNoteSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(xhsnotesnapshot.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *XHSNoteSnapshotUpsertOne) UpdateNewValues() *XHSNoteSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(xhsnotesnapshot.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.XHSNoteSnapshot.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *XHSNoteSnapshotUpsertOne) Ignore() *XHSNoteSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *XHSNoteSnapshotUpsertOne) DoNothing() *XHSNoteSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the XHSNoteSnapshotCreate.OnConflict
// documentation for more info.
func (u *XHSNoteSnapshotUpsertOne) Update(set func(*XHSNoteSnapshotUpsert)) *XHSNoteSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&XHSNoteSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetTrackingID sets the "tracking_id" field.
func (u *XHSNoteSnapshotUpsertOne) SetTrackingID(v uuid.UUID) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetTrackingID(v)
	})
}

// UpdateTrackingID sets the "tracking_id" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateTrackingID() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateTrackingID()
	})
}

// SetSequence sets the "sequence" field.
func (u *XHSNoteSnapshotUpsertOne) SetSequence(v int) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetSequence(v)
	})
}

// AddSequence adds v to the "sequence" field.
func (u *XHSNoteSnapshotUpsertOne) AddSequence(v int) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.AddSequence(v)
	})
}

// UpdateSequence sets the "sequence" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateSequence() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateSequence()
	})
}

// SetTrigger sets the "trigger" field.
func (u *XHSNoteSnapshotUpsertOne) SetTrigger(v string) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetTrigger(v)
	})
}

// UpdateTrigger sets the "trigger" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateTrigger() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateTrigger()
	})
}

// SetStatus sets the "status" field.
func (u *XHSNoteSnapshotUpsertOne) SetStatus(v string) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateStatus() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateStatus()
	})
}

// SetError sets the "error" field.
func (u *XHSNoteSnapshotUpsertOne) SetError(v string) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateError() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateError()
	})
}

// SetCapturedAt sets the "captured_at" field.
func (u *XHSNoteSnapshotUpsertOne) SetCapturedAt(v time.Time) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetCapturedAt(v)
	})
}

// UpdateCapturedAt sets the "captured_at" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateCapturedAt() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateCapturedAt()
	})
}

// SetWorkUpdatedAt sets the "work_updated_at" field.
func (u *XHSNoteSnapshotUpsertOne) SetWorkUpdatedAt(v string) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetWorkUpdatedAt(v)
	})
}

// UpdateWorkUpdatedAt sets the "work_updated_at" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateWorkUpdatedAt() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateWorkUpdatedAt()
	})
}

// SetViews sets the "views" field.
func (u *XHSNoteSnapshotUpsertOne) SetViews(v int) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetViews(v)
	})
}

// AddViews adds v to the "views" field.
func (u *XHSNoteSnapshotUpsertOne) AddViews(v int) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.AddViews(v)
	})
}

// UpdateViews sets the "views" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateViews() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateViews()
	})
}

// SetLikes sets the "likes" field.
func (u *XHSNoteSnapshotUpsertOne) SetLikes(v int) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetLikes(v)
	})
}

// AddLikes adds v to the "likes" field.
func (u *XHSNoteSnapshotUpsertOne) AddLikes(v int) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.AddLikes(v)
	})
}

// UpdateLikes sets the "likes" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateLikes() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateLikes()
	})
}

// SetCollects sets the "collects" field.
func (u *XHSNoteSnapshotUpsertOne) SetCollects(v int) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetCollects(v)
	})
}

// AddCollects adds v to the "collects" field.
func (u *XHSNoteSnapshotUpsertOne) AddCollects(v int) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.AddCollects(v)
	})
}

// UpdateCollects sets the "collects" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateCollects() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateCollects()
	})
}

// SetComments sets the "comments" field.
func (u *XHSNoteSnapshotUpsertOne) SetComments(v int) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetComments(v)
	})
}

// AddComments adds v to the "comments" field.
func (u *XHSNoteSnapshotUpsertOne) AddComments(v int) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.AddComments(v)
	})
}

// UpdateComments sets the "comments" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateComments() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateComments()
	})
}

// SetShares sets the "shares" field.
func (u *XHSNoteSnapshotUpsertOne) SetShares(v int) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetShares(v)
	})
}

// AddShares adds v to the "shares" field.
func (u *XHSNoteSnapshotUpsertOne) AddShares(v int) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.AddShares(v)
	})
}

// UpdateShares sets the "shares" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateShares() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateShares()
	})
}

// SetAccountName sets the "account_name" field.
func (u *XHSNoteSnapshotUpsertOne) SetAccountName(v string) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetAccountName(v)
	})
}

// UpdateAccountName sets the "account_name" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateAccountName() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateAccountName()
	})
}

// SetAccountAvatar sets the "account_avatar" field.
func (u *XHSNoteSnapshotUpsertOne) SetAccountAvatar(v string) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetAccountAvatar(v)
	})
}

// UpdateAccountAvatar sets the "account_avatar" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateAccountAvatar() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateAccountAvatar()
	})
}

// SetAccountDisplayID sets the "account_display_id" field.
func (u *XHSNoteSnapshotUpsertOne) SetAccountDisplayID(v string) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetAccountDisplayID(v)
	})
}

// UpdateAccountDisplayID sets the "account_display_id" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateAccountDisplayID() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateAccountDisplayID()
	})
}

// SetAccountUserID sets the "account_user_id" field.
func (u *XHSNoteSnapshotUpsertOne) SetAccountUserID(v string) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetAccountUserID(v)
	})
}

// UpdateAccountUserID sets the "account_user_id" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateAccountUserID() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateAccountUserID()
	})
}

// SetAccountDescription sets the "account_description" field.
func (u *XHSNoteSnapshotUpsertOne) SetAccountDescription(v string) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetAccountDescription(v)
	})
}

// UpdateAccountDescription sets the "account_description" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateAccountDescription() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateAccountDescription()
	})
}

// SetAccountFans sets the "account_fans" field.
func (u *XHSNoteSnapshotUpsertOne) SetAccountFans(v int) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetAccountFans(v)
	})
}

// AddAccountFans adds v to the "account_fans" field.
func (u *XHSNoteSnapshotUpsertOne) AddAccountFans(v int) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.AddAccountFans(v)
	})
}

// UpdateAccountFans sets the "account_fans" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateAccountFans() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateAccountFans()
	})
}

// SetAccountTotalWorks sets the "account_total_works" field.
func (u *XHSNoteSnapshotUpsertOne) SetAccountTotalWorks(v int) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetAccountTotalWorks(v)
	})
}

// AddAccountTotalWorks adds v to the "account_total_works" field.
func (u *XHSNoteSnapshotUpsertOne) AddAccountTotalWorks(v int) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.AddAccountTotalWorks(v)
	})
}

// UpdateAccountTotalWorks sets the "account_total_works" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateAccountTotalWorks() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateAccountTotalWorks()
	})
}

// SetAccountLikes sets the "account_likes" field.
func (u *XHSNoteSnapshotUpsertOne) SetAccountLikes(v int) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetAccountLikes(v)
	})
}

// AddAccountLikes adds v to the "account_likes" field.
func (u *XHSNoteSnapshotUpsertOne) AddAccountLikes(v int) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.AddAccountLikes(v)
	})
}

// UpdateAccountLikes sets the "account_likes" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateAccountLikes() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateAccountLikes()
	})
}

// SetAccountCollects sets the "account_collects" field.
func (u *XHSNoteSnapshotUpsertOne) SetAccountCollects(v int) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetAccountCollects(v)
	})
}

// AddAccountCollects adds v to the "account_collects" field.
func (u *XHSNoteSnapshotUpsertOne) AddAccountCollects(v int) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.AddAccountCollects(v)
	})
}

// UpdateAccountCollects sets the "account_collects" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateAccountCollects() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateAccountCollects()
	})
}

// SetAccountFollows sets the "account_follows" field.
func (u *XHSNoteSnapshotUpsertOne) SetAccountFollows(v int) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetAccountFollows(v)
	})
}

// AddAccountFollows adds v to the "account_follows" field.
func (u *XHSNoteSnapshotUpsertOne) AddAccountFollows(v int) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.AddAccountFollows(v)
	})
}

// UpdateAccountFollows sets the "account_follows" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateAccountFollows() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateAccountFollows()
	})
}

// SetAccountUpdatedAt sets the "account_updated_at" field.
func (u *XHSNoteSnapshotUpsertOne) SetAccountUpdatedAt(v string) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetAccountUpdatedAt(v)
	})
}

// UpdateAccountUpdatedAt sets the "account_updated_at" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateAccountUpdatedAt() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateAccountUpdatedAt()
	})
}

// SetSimilarAccounts sets the "similar_accounts" field.
func (u *XHSNoteSnapshotUpsertOne) SetSimilarAccounts(v []types.XHSSimilarAccount) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetSimilarAccounts(v)
	})
}

// UpdateSimilarAccounts sets the "similar_accounts" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateSimilarAccounts() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateSimilarAccounts()
	})
}

// SetSimilarSummary sets the "similar_summary" field.
func (u *XHSNoteSnapshotUpsertOne) SetSimilarSummary(v string) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetSimilarSummary(v)
	})
}

// UpdateSimilarSummary sets the "similar_summary" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateSimilarSummary() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateSimilarSummary()
	})
}

// SetLinkEpoch sets the "link_epoch" field.
func (u *XHSNoteSnapshotUpsertOne) SetLinkEpoch(v int) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetLinkEpoch(v)
	})
}

// AddLinkEpoch adds v to the "link_epoch" field.
func (u *XHSNoteSnapshotUpsertOne) AddLinkEpoch(v int) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.AddLinkEpoch(v)
	})
}

// UpdateLinkEpoch sets the "link_epoch" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateLinkEpoch() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateLinkEpoch()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *XHSNoteSnapshotUpsertOne) SetCreatedAt(v time.Time) *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertOne) UpdateCreatedAt() *XHSNoteSnapshotUpsertOne {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *XHSNoteSnapshotUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for XHSNoteSnapshotCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *XHSNoteSnapshotUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *XHSNoteSnapshotUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("db: XHSNoteSnapshotUpsertOne.ID is not supported by MySQL driver. Use XHSNoteSnapshotUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *XHSNoteSnapshotUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// XHSNoteSnapshotCreateBulk is the builder for creating many XHSNoteSnapshot entities in bulk.
type XHSNoteSnapshotCreateBulk struct {
	config
	err      error
	builders []*XHSNoteSnapshotCreate
	conflict []sql.ConflictOption
}

// Save creates the XHSNoteSnapshot entities in the database.
func (_c *XHSNoteSnapshotCreateBulk) Save(ctx context.Context) ([]*XHSNoteSnapshot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*XHSNoteSnapshot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*XHSNoteSnapshotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *XHSNoteSnapshotCreateBulk) SaveX(ctx context.Context) []*XHSNoteSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *XHSNoteSnapshotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *XHSNoteSnapshotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.XHSNoteSnapshot.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.XHSNoteSnapshotUpsert) {
//			SetTrackingID(v+v).
//		}).
//		Exec(ctx)
func (_c *XHSNoteSnapshotCreateBulk) OnConflict(opts ...sql.ConflictOption) *XHSNoteSnapshotUpsertBulk {
	_c.conflict = opts
	return &XHSNoteSnapshotUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.XHSNoteSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *XHSNoteSnapshotCreateBulk) OnConflictColumns(columns ...string) *XHSNoteSnapshotUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &XHSNoteSnapshotUpsertBulk{
		create: _c,
	}
}

// XHSNoteSnapshotUpsertBulk is the builder for "upsert"-ing
// a bulk of XHSNoteSnapshot nodes.
type XHSNoteSnapshotUpsertBulk struct {
	create *XHSNoteSnapshotCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.XHSNoteSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(xhsnotesnapshot.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *XHSNoteSnapshotUpsertBulk) UpdateNewValues() *XHSNoteSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(xhsnotesnapshot.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.XHSNoteSnapshot.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *XHSNoteSnapshotUpsertBulk) Ignore() *XHSNoteSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *XHSNoteSnapshotUpsertBulk) DoNothing() *XHSNoteSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the XHSNoteSnapshotCreateBulk.OnConflict
// documentation for more info.
func (u *XHSNoteSnapshotUpsertBulk) Update(set func(*XHSNoteSnapshotUpsert)) *XHSNoteSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&XHSNoteSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetTrackingID sets the "tracking_id" field.
func (u *XHSNoteSnapshotUpsertBulk) SetTrackingID(v uuid.UUID) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetTrackingID(v)
	})
}

// UpdateTrackingID sets the "tracking_id" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateTrackingID() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateTrackingID()
	})
}

// SetSequence sets the "sequence" field.
func (u *XHSNoteSnapshotUpsertBulk) SetSequence(v int) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetSequence(v)
	})
}

// AddSequence adds v to the "sequence" field.
func (u *XHSNoteSnapshotUpsertBulk) AddSequence(v int) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.AddSequence(v)
	})
}

// UpdateSequence sets the "sequence" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateSequence() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateSequence()
	})
}

// SetTrigger sets the "trigger" field.
func (u *XHSNoteSnapshotUpsertBulk) SetTrigger(v string) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetTrigger(v)
	})
}

// UpdateTrigger sets the "trigger" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateTrigger() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateTrigger()
	})
}

// SetStatus sets the "status" field.
func (u *XHSNoteSnapshotUpsertBulk) SetStatus(v string) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateStatus() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateStatus()
	})
}

// SetError sets the "error" field.
func (u *XHSNoteSnapshotUpsertBulk) SetError(v string) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateError() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateError()
	})
}

// SetCapturedAt sets the "captured_at" field.
func (u *XHSNoteSnapshotUpsertBulk) SetCapturedAt(v time.Time) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetCapturedAt(v)
	})
}

// UpdateCapturedAt sets the "captured_at" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateCapturedAt() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateCapturedAt()
	})
}

// SetWorkUpdatedAt sets the "work_updated_at" field.
func (u *XHSNoteSnapshotUpsertBulk) SetWorkUpdatedAt(v string) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetWorkUpdatedAt(v)
	})
}

// UpdateWorkUpdatedAt sets the "work_updated_at" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateWorkUpdatedAt() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateWorkUpdatedAt()
	})
}

// SetViews sets the "views" field.
func (u *XHSNoteSnapshotUpsertBulk) SetViews(v int) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetViews(v)
	})
}

// AddViews adds v to the "views" field.
func (u *XHSNoteSnapshotUpsertBulk) AddViews(v int) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.AddViews(v)
	})
}

// UpdateViews sets the "views" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateViews() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateViews()
	})
}

// SetLikes sets the "likes" field.
func (u *XHSNoteSnapshotUpsertBulk) SetLikes(v int) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetLikes(v)
	})
}

// AddLikes adds v to the "likes" field.
func (u *XHSNoteSnapshotUpsertBulk) AddLikes(v int) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.AddLikes(v)
	})
}

// UpdateLikes sets the "likes" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateLikes() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateLikes()
	})
}

// SetCollects sets the "collects" field.
func (u *XHSNoteSnapshotUpsertBulk) SetCollects(v int) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetCollects(v)
	})
}

// AddCollects adds v to the "collects" field.
func (u *XHSNoteSnapshotUpsertBulk) AddCollects(v int) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.AddCollects(v)
	})
}

// UpdateCollects sets the "collects" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateCollects() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateCollects()
	})
}

// SetComments sets the "comments" field.
func (u *XHSNoteSnapshotUpsertBulk) SetComments(v int) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetComments(v)
	})
}

// AddComments adds v to the "comments" field.
func (u *XHSNoteSnapshotUpsertBulk) AddComments(v int) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.AddComments(v)
	})
}

// UpdateComments sets the "comments" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateComments() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateComments()
	})
}

// SetShares sets the "shares" field.
func (u *XHSNoteSnapshotUpsertBulk) SetShares(v int) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetShares(v)
	})
}

// AddShares adds v to the "shares" field.
func (u *XHSNoteSnapshotUpsertBulk) AddShares(v int) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.AddShares(v)
	})
}

// UpdateShares sets the "shares" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateShares() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateShares()
	})
}

// SetAccountName sets the "account_name" field.
func (u *XHSNoteSnapshotUpsertBulk) SetAccountName(v string) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetAccountName(v)
	})
}

// UpdateAccountName sets the "account_name" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateAccountName() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateAccountName()
	})
}

// SetAccountAvatar sets the "account_avatar" field.
func (u *XHSNoteSnapshotUpsertBulk) SetAccountAvatar(v string) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetAccountAvatar(v)
	})
}

// UpdateAccountAvatar sets the "account_avatar" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateAccountAvatar() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateAccountAvatar()
	})
}

// SetAccountDisplayID sets the "account_display_id" field.
func (u *XHSNoteSnapshotUpsertBulk) SetAccountDisplayID(v string) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetAccountDisplayID(v)
	})
}

// UpdateAccountDisplayID sets the "account_display_id" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateAccountDisplayID() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateAccountDisplayID()
	})
}

// SetAccountUserID sets the "account_user_id" field.
func (u *XHSNoteSnapshotUpsertBulk) SetAccountUserID(v string) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetAccountUserID(v)
	})
}

// UpdateAccountUserID sets the "account_user_id" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateAccountUserID() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateAccountUserID()
	})
}

// SetAccountDescription sets the "account_description" field.
func (u *XHSNoteSnapshotUpsertBulk) SetAccountDescription(v string) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetAccountDescription(v)
	})
}

// UpdateAccountDescription sets the "account_description" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateAccountDescription() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateAccountDescription()
	})
}

// SetAccountFans sets the "account_fans" field.
func (u *XHSNoteSnapshotUpsertBulk) SetAccountFans(v int) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetAccountFans(v)
	})
}

// AddAccountFans adds v to the "account_fans" field.
func (u *XHSNoteSnapshotUpsertBulk) AddAccountFans(v int) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.AddAccountFans(v)
	})
}

// UpdateAccountFans sets the "account_fans" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateAccountFans() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateAccountFans()
	})
}

// SetAccountTotalWorks sets the "account_total_works" field.
func (u *XHSNoteSnapshotUpsertBulk) SetAccountTotalWorks(v int) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetAccountTotalWorks(v)
	})
}

// AddAccountTotalWorks adds v to the "account_total_works" field.
func (u *XHSNoteSnapshotUpsertBulk) AddAccountTotalWorks(v int) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.AddAccountTotalWorks(v)
	})
}

// UpdateAccountTotalWorks sets the "account_total_works" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateAccountTotalWorks() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateAccountTotalWorks()
	})
}

// SetAccountLikes sets the "account_likes" field.
func (u *XHSNoteSnapshotUpsertBulk) SetAccountLikes(v int) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetAccountLikes(v)
	})
}

// AddAccountLikes adds v to the "account_likes" field.
func (u *XHSNoteSnapshotUpsertBulk) AddAccountLikes(v int) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.AddAccountLikes(v)
	})
}

// UpdateAccountLikes sets the "account_likes" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateAccountLikes() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateAccountLikes()
	})
}

// SetAccountCollects sets the "account_collects" field.
func (u *XHSNoteSnapshotUpsertBulk) SetAccountCollects(v int) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetAccountCollects(v)
	})
}

// AddAccountCollects adds v to the "account_collects" field.
func (u *XHSNoteSnapshotUpsertBulk) AddAccountCollects(v int) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.AddAccountCollects(v)
	})
}

// UpdateAccountCollects sets the "account_collects" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateAccountCollects() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateAccountCollects()
	})
}

// SetAccountFollows sets the "account_follows" field.
func (u *XHSNoteSnapshotUpsertBulk) SetAccountFollows(v int) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetAccountFollows(v)
	})
}

// AddAccountFollows adds v to the "account_follows" field.
func (u *XHSNoteSnapshotUpsertBulk) AddAccountFollows(v int) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.AddAccountFollows(v)
	})
}

// UpdateAccountFollows sets the "account_follows" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateAccountFollows() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateAccountFollows()
	})
}

// SetAccountUpdatedAt sets the "account_updated_at" field.
func (u *XHSNoteSnapshotUpsertBulk) SetAccountUpdatedAt(v string) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetAccountUpdatedAt(v)
	})
}

// UpdateAccountUpdatedAt sets the "account_updated_at" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateAccountUpdatedAt() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateAccountUpdatedAt()
	})
}

// SetSimilarAccounts sets the "similar_accounts" field.
func (u *XHSNoteSnapshotUpsertBulk) SetSimilarAccounts(v []types.XHSSimilarAccount) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetSimilarAccounts(v)
	})
}

// UpdateSimilarAccounts sets the "similar_accounts" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateSimilarAccounts() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateSimilarAccounts()
	})
}

// SetSimilarSummary sets the "similar_summary" field.
func (u *XHSNoteSnapshotUpsertBulk) SetSimilarSummary(v string) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetSimilarSummary(v)
	})
}

// UpdateSimilarSummary sets the "similar_summary" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateSimilarSummary() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateSimilarSummary()
	})
}

// SetLinkEpoch sets the "link_epoch" field.
func (u *XHSNoteSnapshotUpsertBulk) SetLinkEpoch(v int) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetLinkEpoch(v)
	})
}

// AddLinkEpoch adds v to the "link_epoch" field.
func (u *XHSNoteSnapshotUpsertBulk) AddLinkEpoch(v int) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.AddLinkEpoch(v)
	})
}

// UpdateLinkEpoch sets the "link_epoch" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateLinkEpoch() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateLinkEpoch()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *XHSNoteSnapshotUpsertBulk) SetCreatedAt(v time.Time) *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *XHSNoteSnapshotUpsertBulk) UpdateCreatedAt() *XHSNoteSnapshotUpsertBulk {
	return u.Update(func(s *XHSNoteSnapshotUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *XHSNoteSnapshotUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("db: OnConflict was set for builder %d. Set it on the XHSNoteSnapshotCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for XHSNoteSnapshotCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *XHSNoteSnapshotUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
