// Code generated by ent, DO NOT EDIT.

package db

import (
	"bridal/backend/db/xhsnotetracking"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// XHSNoteTracking is the model entity for the XHSNoteTracking schema.
type XHSNoteTracking struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID uuid.UUID `json:"task_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// NoteURL holds the value of the "note_url" field.
	NoteURL string `json:"note_url,omitempty"`
	// CanonicalURL holds the value of the "canonical_url" field.
	CanonicalURL string `json:"canonical_url,omitempty"`
	// WorkID holds the value of the "work_id" field.
	WorkID string `json:"work_id,omitempty"`
	// AccountUserID holds the value of the "account_user_id" field.
	AccountUserID string `json:"account_user_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID string `json:"account_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Body holds the value of the "body" field.
	Body string `json:"body,omitempty"`
	// CoverURL holds the value of the "cover_url" field.
	CoverURL string `json:"cover_url,omitempty"`
	// WorkType holds the value of the "work_type" field.
	WorkType string `json:"work_type,omitempty"`
	// PublishedAt holds the value of the "published_at" field.
	PublishedAt string `json:"published_at,omitempty"`
	// UserRefreshCount holds the value of the "user_refresh_count" field.
	UserRefreshCount int `json:"user_refresh_count,omitempty"`
	// UserLinkEditCount holds the value of the "user_link_edit_count" field.
	UserLinkEditCount int `json:"user_link_edit_count,omitempty"`
	// NextRefreshAt holds the value of the "next_refresh_at" field.
	NextRefreshAt *time.Time `json:"next_refresh_at,omitempty"`
	// LinkEpoch holds the value of the "link_epoch" field.
	LinkEpoch int `json:"link_epoch,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*XHSNoteTracking) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case xhsnotetracking.FieldUserRefreshCount, xhsnotetracking.FieldUserLinkEditCount, xhsnotetracking.FieldLinkEpoch:
			values[i] = new(sql.NullInt64)
		case xhsnotetracking.FieldNoteURL, xhsnotetracking.FieldCanonicalURL, xhsnotetracking.FieldWorkID, xhsnotetracking.FieldAccountUserID, xhsnotetracking.FieldAccountID, xhsnotetracking.FieldTitle, xhsnotetracking.FieldBody, xhsnotetracking.FieldCoverURL, xhsnotetracking.FieldWorkType, xhsnotetracking.FieldPublishedAt:
			values[i] = new(sql.NullString)
		case xhsnotetracking.FieldNextRefreshAt, xhsnotetracking.FieldCreatedAt, xhsnotetracking.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case xhsnotetracking.FieldID, xhsnotetracking.FieldTaskID, xhsnotetracking.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the XHSNoteTracking fields.
func (_m *XHSNoteTracking) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case xhsnotetracking.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case xhsnotetracking.FieldTaskID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value != nil {
				_m.TaskID = *value
			}
		case xhsnotetracking.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case xhsnotetracking.FieldNoteURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note_url", values[i])
			} else if value.Valid {
				_m.NoteURL = value.String
			}
		case xhsnotetracking.FieldCanonicalURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field canonical_url", values[i])
			} else if value.Valid {
				_m.CanonicalURL = value.String
			}
		case xhsnotetracking.FieldWorkID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field work_id", values[i])
			} else if value.Valid {
				_m.WorkID = value.String
			}
		case xhsnotetracking.FieldAccountUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_user_id", values[i])
			} else if value.Valid {
				_m.AccountUserID = value.String
			}
		case xhsnotetracking.FieldAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.String
			}
		case xhsnotetracking.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case xhsnotetracking.FieldBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value.Valid {
				_m.Body = value.String
			}
		case xhsnotetracking.FieldCoverURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover_url", values[i])
			} else if value.Valid {
				_m.CoverURL = value.String
			}
		case xhsnotetracking.FieldWorkType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field work_type", values[i])
			} else if value.Valid {
				_m.WorkType = value.String
			}
		case xhsnotetracking.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = value.String
			}
		case xhsnotetracking.FieldUserRefreshCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_refresh_count", values[i])
			} else if value.Valid {
				_m.UserRefreshCount = int(value.Int64)
			}
		case xhsnotetracking.FieldUserLinkEditCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_link_edit_count", values[i])
			} else if value.Valid {
				_m.UserLinkEditCount = int(value.Int64)
			}
		case xhsnotetracking.FieldNextRefreshAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_refresh_at", values[i])
			} else if value.Valid {
				_m.NextRefreshAt = new(time.Time)
				*_m.NextRefreshAt = value.Time
			}
		case xhsnotetracking.FieldLinkEpoch:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field link_epoch", values[i])
			} else if value.Valid {
				_m.LinkEpoch = int(value.Int64)
			}
		case xhsnotetracking.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case xhsnotetracking.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the XHSNoteTracking.
// This includes values selected through modifiers, order, etc.
func (_m *XHSNoteTracking) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this XHSNoteTracking.
// Note that you need to call XHSNoteTracking.Unwrap() before calling this method if this XHSNoteTracking
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *XHSNoteTracking) Update() *XHSNoteTrackingUpdateOne {
	return NewXHSNoteTrackingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the XHSNoteTracking entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *XHSNoteTracking) Unwrap() *XHSNoteTracking {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("db: XHSNoteTracking is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *XHSNoteTracking) String() string {
	var builder strings.Builder
	builder.WriteString("XHSNoteTracking(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("task_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaskID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("note_url=")
	builder.WriteString(_m.NoteURL)
	builder.WriteString(", ")
	builder.WriteString("canonical_url=")
	builder.WriteString(_m.CanonicalURL)
	builder.WriteString(", ")
	builder.WriteString("work_id=")
	builder.WriteString(_m.WorkID)
	builder.WriteString(", ")
	builder.WriteString("account_user_id=")
	builder.WriteString(_m.AccountUserID)
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(_m.AccountID)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("body=")
	builder.WriteString(_m.Body)
	builder.WriteString(", ")
	builder.WriteString("cover_url=")
	builder.WriteString(_m.CoverURL)
	builder.WriteString(", ")
	builder.WriteString("work_type=")
	builder.WriteString(_m.WorkType)
	builder.WriteString(", ")
	builder.WriteString("published_at=")
	builder.WriteString(_m.PublishedAt)
	builder.WriteString(", ")
	builder.WriteString("user_refresh_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserRefreshCount))
	builder.WriteString(", ")
	builder.WriteString("user_link_edit_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserLinkEditCount))
	builder.WriteString(", ")
	if v := _m.NextRefreshAt; v != nil {
		builder.WriteString("next_refresh_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("link_epoch=")
	builder.WriteString(fmt.Sprintf("%v", _m.LinkEpoch))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// XHSNoteTrackings is a parsable slice of XHSNoteTracking.
type XHSNoteTrackings []*XHSNoteTracking
