// Code generated by ent, DO NOT EDIT.

package db

import (
	"bridal/backend/db/predicate"
	"bridal/backend/db/xhsnotetracking"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// XHSNoteTrackingDelete is the builder for deleting a XHSNoteTracking entity.
type XHSNoteTrackingDelete struct {
	config
	hooks    []Hook
	mutation *XHSNoteTrackingMutation
}

// Where appends a list predicates to the XHSNoteTrackingDelete builder.
func (_d *XHSNoteTrackingDelete) Where(ps ...predicate.XHSNoteTracking) *XHSNoteTrackingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *XHSNoteTrackingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *XHSNoteTrackingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *XHSNoteTrackingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(xhsnotetracking.Table, sqlgraph.NewFieldSpec(xhsnotetracking.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// XHSNoteTrackingDeleteOne is the builder for deleting a single XHSNoteTracking entity.
type XHSNoteTrackingDeleteOne struct {
	_d *XHSNoteTrackingDelete
}

// Where appends a list predicates to the XHSNoteTrackingDelete builder.
func (_d *XHSNoteTrackingDeleteOne) Where(ps ...predicate.XHSNoteTracking) *XHSNoteTrackingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *XHSNoteTrackingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{xhsnotetracking.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *XHSNoteTrackingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
