// Code generated by ent, DO NOT EDIT.

package xhsnotetracking

import (
	"bridal/backend/db/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLTE(FieldID, id))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldTaskID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldUserID, v))
}

// NoteURL applies equality check predicate on the "note_url" field. It's identical to NoteURLEQ.
func NoteURL(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldNoteURL, v))
}

// CanonicalURL applies equality check predicate on the "canonical_url" field. It's identical to CanonicalURLEQ.
func CanonicalURL(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldCanonicalURL, v))
}

// WorkID applies equality check predicate on the "work_id" field. It's identical to WorkIDEQ.
func WorkID(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldWorkID, v))
}

// AccountUserID applies equality check predicate on the "account_user_id" field. It's identical to AccountUserIDEQ.
func AccountUserID(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldAccountUserID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldAccountID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldTitle, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldBody, v))
}

// CoverURL applies equality check predicate on the "cover_url" field. It's identical to CoverURLEQ.
func CoverURL(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldCoverURL, v))
}

// WorkType applies equality check predicate on the "work_type" field. It's identical to WorkTypeEQ.
func WorkType(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldWorkType, v))
}

// PublishedAt applies equality check predicate on the "published_at" field. It's identical to PublishedAtEQ.
func PublishedAt(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldPublishedAt, v))
}

// UserRefreshCount applies equality check predicate on the "user_refresh_count" field. It's identical to UserRefreshCountEQ.
func UserRefreshCount(v int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldUserRefreshCount, v))
}

// UserLinkEditCount applies equality check predicate on the "user_link_edit_count" field. It's identical to UserLinkEditCountEQ.
func UserLinkEditCount(v int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldUserLinkEditCount, v))
}

// NextRefreshAt applies equality check predicate on the "next_refresh_at" field. It's identical to NextRefreshAtEQ.
func NextRefreshAt(v time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldNextRefreshAt, v))
}

// LinkEpoch applies equality check predicate on the "link_epoch" field. It's identical to LinkEpochEQ.
func LinkEpoch(v int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldLinkEpoch, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldUpdatedAt, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNotIn(FieldTaskID, vs...))
}

// TaskIDGT applies the GT predicate on the "task_id" field.
func TaskIDGT(v uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGT(FieldTaskID, v))
}

// TaskIDGTE applies the GTE predicate on the "task_id" field.
func TaskIDGTE(v uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGTE(FieldTaskID, v))
}

// TaskIDLT applies the LT predicate on the "task_id" field.
func TaskIDLT(v uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLT(FieldTaskID, v))
}

// TaskIDLTE applies the LTE predicate on the "task_id" field.
func TaskIDLTE(v uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLTE(FieldTaskID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLTE(FieldUserID, v))
}

// NoteURLEQ applies the EQ predicate on the "note_url" field.
func NoteURLEQ(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldNoteURL, v))
}

// NoteURLNEQ applies the NEQ predicate on the "note_url" field.
func NoteURLNEQ(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNEQ(FieldNoteURL, v))
}

// NoteURLIn applies the In predicate on the "note_url" field.
func NoteURLIn(vs ...string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldIn(FieldNoteURL, vs...))
}

// NoteURLNotIn applies the NotIn predicate on the "note_url" field.
func NoteURLNotIn(vs ...string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNotIn(FieldNoteURL, vs...))
}

// NoteURLGT applies the GT predicate on the "note_url" field.
func NoteURLGT(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGT(FieldNoteURL, v))
}

// NoteURLGTE applies the GTE predicate on the "note_url" field.
func NoteURLGTE(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGTE(FieldNoteURL, v))
}

// NoteURLLT applies the LT predicate on the "note_url" field.
func NoteURLLT(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLT(FieldNoteURL, v))
}

// NoteURLLTE applies the LTE predicate on the "note_url" field.
func NoteURLLTE(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLTE(FieldNoteURL, v))
}

// NoteURLContains applies the Contains predicate on the "note_url" field.
func NoteURLContains(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldContains(FieldNoteURL, v))
}

// NoteURLHasPrefix applies the HasPrefix predicate on the "note_url" field.
func NoteURLHasPrefix(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldHasPrefix(FieldNoteURL, v))
}

// NoteURLHasSuffix applies the HasSuffix predicate on the "note_url" field.
func NoteURLHasSuffix(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldHasSuffix(FieldNoteURL, v))
}

// NoteURLEqualFold applies the EqualFold predicate on the "note_url" field.
func NoteURLEqualFold(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEqualFold(FieldNoteURL, v))
}

// NoteURLContainsFold applies the ContainsFold predicate on the "note_url" field.
func NoteURLContainsFold(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldContainsFold(FieldNoteURL, v))
}

// CanonicalURLEQ applies the EQ predicate on the "canonical_url" field.
func CanonicalURLEQ(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldCanonicalURL, v))
}

// CanonicalURLNEQ applies the NEQ predicate on the "canonical_url" field.
func CanonicalURLNEQ(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNEQ(FieldCanonicalURL, v))
}

// CanonicalURLIn applies the In predicate on the "canonical_url" field.
func CanonicalURLIn(vs ...string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldIn(FieldCanonicalURL, vs...))
}

// CanonicalURLNotIn applies the NotIn predicate on the "canonical_url" field.
func CanonicalURLNotIn(vs ...string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNotIn(FieldCanonicalURL, vs...))
}

// CanonicalURLGT applies the GT predicate on the "canonical_url" field.
func CanonicalURLGT(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGT(FieldCanonicalURL, v))
}

// CanonicalURLGTE applies the GTE predicate on the "canonical_url" field.
func CanonicalURLGTE(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGTE(FieldCanonicalURL, v))
}

// CanonicalURLLT applies the LT predicate on the "canonical_url" field.
func CanonicalURLLT(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLT(FieldCanonicalURL, v))
}

// CanonicalURLLTE applies the LTE predicate on the "canonical_url" field.
func CanonicalURLLTE(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLTE(FieldCanonicalURL, v))
}

// CanonicalURLContains applies the Contains predicate on the "canonical_url" field.
func CanonicalURLContains(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldContains(FieldCanonicalURL, v))
}

// CanonicalURLHasPrefix applies the HasPrefix predicate on the "canonical_url" field.
func CanonicalURLHasPrefix(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldHasPrefix(FieldCanonicalURL, v))
}

// CanonicalURLHasSuffix applies the HasSuffix predicate on the "canonical_url" field.
func CanonicalURLHasSuffix(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldHasSuffix(FieldCanonicalURL, v))
}

// CanonicalURLEqualFold applies the EqualFold predicate on the "canonical_url" field.
func CanonicalURLEqualFold(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEqualFold(FieldCanonicalURL, v))
}

// CanonicalURLContainsFold applies the ContainsFold predicate on the "canonical_url" field.
func CanonicalURLContainsFold(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldContainsFold(FieldCanonicalURL, v))
}

// WorkIDEQ applies the EQ predicate on the "work_id" field.
func WorkIDEQ(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldWorkID, v))
}

// WorkIDNEQ applies the NEQ predicate on the "work_id" field.
func WorkIDNEQ(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNEQ(FieldWorkID, v))
}

// WorkIDIn applies the In predicate on the "work_id" field.
func WorkIDIn(vs ...string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldIn(FieldWorkID, vs...))
}

// WorkIDNotIn applies the NotIn predicate on the "work_id" field.
func WorkIDNotIn(vs ...string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNotIn(FieldWorkID, vs...))
}

// WorkIDGT applies the GT predicate on the "work_id" field.
func WorkIDGT(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGT(FieldWorkID, v))
}

// WorkIDGTE applies the GTE predicate on the "work_id" field.
func WorkIDGTE(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGTE(FieldWorkID, v))
}

// WorkIDLT applies the LT predicate on the "work_id" field.
func WorkIDLT(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLT(FieldWorkID, v))
}

// WorkIDLTE applies the LTE predicate on the "work_id" field.
func WorkIDLTE(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLTE(FieldWorkID, v))
}

// WorkIDContains applies the Contains predicate on the "work_id" field.
func WorkIDContains(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldContains(FieldWorkID, v))
}

// WorkIDHasPrefix applies the HasPrefix predicate on the "work_id" field.
func WorkIDHasPrefix(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldHasPrefix(FieldWorkID, v))
}

// WorkIDHasSuffix applies the HasSuffix predicate on the "work_id" field.
func WorkIDHasSuffix(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldHasSuffix(FieldWorkID, v))
}

// WorkIDEqualFold applies the EqualFold predicate on the "work_id" field.
func WorkIDEqualFold(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEqualFold(FieldWorkID, v))
}

// WorkIDContainsFold applies the ContainsFold predicate on the "work_id" field.
func WorkIDContainsFold(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldContainsFold(FieldWorkID, v))
}

// AccountUserIDEQ applies the EQ predicate on the "account_user_id" field.
func AccountUserIDEQ(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldAccountUserID, v))
}

// AccountUserIDNEQ applies the NEQ predicate on the "account_user_id" field.
func AccountUserIDNEQ(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNEQ(FieldAccountUserID, v))
}

// AccountUserIDIn applies the In predicate on the "account_user_id" field.
func AccountUserIDIn(vs ...string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldIn(FieldAccountUserID, vs...))
}

// AccountUserIDNotIn applies the NotIn predicate on the "account_user_id" field.
func AccountUserIDNotIn(vs ...string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNotIn(FieldAccountUserID, vs...))
}

// AccountUserIDGT applies the GT predicate on the "account_user_id" field.
func AccountUserIDGT(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGT(FieldAccountUserID, v))
}

// AccountUserIDGTE applies the GTE predicate on the "account_user_id" field.
func AccountUserIDGTE(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGTE(FieldAccountUserID, v))
}

// AccountUserIDLT applies the LT predicate on the "account_user_id" field.
func AccountUserIDLT(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLT(FieldAccountUserID, v))
}

// AccountUserIDLTE applies the LTE predicate on the "account_user_id" field.
func AccountUserIDLTE(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLTE(FieldAccountUserID, v))
}

// AccountUserIDContains applies the Contains predicate on the "account_user_id" field.
func AccountUserIDContains(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldContains(FieldAccountUserID, v))
}

// AccountUserIDHasPrefix applies the HasPrefix predicate on the "account_user_id" field.
func AccountUserIDHasPrefix(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldHasPrefix(FieldAccountUserID, v))
}

// AccountUserIDHasSuffix applies the HasSuffix predicate on the "account_user_id" field.
func AccountUserIDHasSuffix(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldHasSuffix(FieldAccountUserID, v))
}

// AccountUserIDEqualFold applies the EqualFold predicate on the "account_user_id" field.
func AccountUserIDEqualFold(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEqualFold(FieldAccountUserID, v))
}

// AccountUserIDContainsFold applies the ContainsFold predicate on the "account_user_id" field.
func AccountUserIDContainsFold(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldContainsFold(FieldAccountUserID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDContains applies the Contains predicate on the "account_id" field.
func AccountIDContains(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldContains(FieldAccountID, v))
}

// AccountIDHasPrefix applies the HasPrefix predicate on the "account_id" field.
func AccountIDHasPrefix(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldHasPrefix(FieldAccountID, v))
}

// AccountIDHasSuffix applies the HasSuffix predicate on the "account_id" field.
func AccountIDHasSuffix(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldHasSuffix(FieldAccountID, v))
}

// AccountIDEqualFold applies the EqualFold predicate on the "account_id" field.
func AccountIDEqualFold(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEqualFold(FieldAccountID, v))
}

// AccountIDContainsFold applies the ContainsFold predicate on the "account_id" field.
func AccountIDContainsFold(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldContainsFold(FieldAccountID, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldContainsFold(FieldTitle, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldHasSuffix(FieldBody, v))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldContainsFold(FieldBody, v))
}

// CoverURLEQ applies the EQ predicate on the "cover_url" field.
func CoverURLEQ(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldCoverURL, v))
}

// CoverURLNEQ applies the NEQ predicate on the "cover_url" field.
func CoverURLNEQ(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNEQ(FieldCoverURL, v))
}

// CoverURLIn applies the In predicate on the "cover_url" field.
func CoverURLIn(vs ...string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldIn(FieldCoverURL, vs...))
}

// CoverURLNotIn applies the NotIn predicate on the "cover_url" field.
func CoverURLNotIn(vs ...string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNotIn(FieldCoverURL, vs...))
}

// CoverURLGT applies the GT predicate on the "cover_url" field.
func CoverURLGT(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGT(FieldCoverURL, v))
}

// CoverURLGTE applies the GTE predicate on the "cover_url" field.
func CoverURLGTE(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGTE(FieldCoverURL, v))
}

// CoverURLLT applies the LT predicate on the "cover_url" field.
func CoverURLLT(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLT(FieldCoverURL, v))
}

// CoverURLLTE applies the LTE predicate on the "cover_url" field.
func CoverURLLTE(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLTE(FieldCoverURL, v))
}

// CoverURLContains applies the Contains predicate on the "cover_url" field.
func CoverURLContains(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldContains(FieldCoverURL, v))
}

// CoverURLHasPrefix applies the HasPrefix predicate on the "cover_url" field.
func CoverURLHasPrefix(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldHasPrefix(FieldCoverURL, v))
}

// CoverURLHasSuffix applies the HasSuffix predicate on the "cover_url" field.
func CoverURLHasSuffix(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldHasSuffix(FieldCoverURL, v))
}

// CoverURLEqualFold applies the EqualFold predicate on the "cover_url" field.
func CoverURLEqualFold(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEqualFold(FieldCoverURL, v))
}

// CoverURLContainsFold applies the ContainsFold predicate on the "cover_url" field.
func CoverURLContainsFold(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldContainsFold(FieldCoverURL, v))
}

// WorkTypeEQ applies the EQ predicate on the "work_type" field.
func WorkTypeEQ(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldWorkType, v))
}

// WorkTypeNEQ applies the NEQ predicate on the "work_type" field.
func WorkTypeNEQ(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNEQ(FieldWorkType, v))
}

// WorkTypeIn applies the In predicate on the "work_type" field.
func WorkTypeIn(vs ...string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldIn(FieldWorkType, vs...))
}

// WorkTypeNotIn applies the NotIn predicate on the "work_type" field.
func WorkTypeNotIn(vs ...string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNotIn(FieldWorkType, vs...))
}

// WorkTypeGT applies the GT predicate on the "work_type" field.
func WorkTypeGT(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGT(FieldWorkType, v))
}

// WorkTypeGTE applies the GTE predicate on the "work_type" field.
func WorkTypeGTE(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGTE(FieldWorkType, v))
}

// WorkTypeLT applies the LT predicate on the "work_type" field.
func WorkTypeLT(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLT(FieldWorkType, v))
}

// WorkTypeLTE applies the LTE predicate on the "work_type" field.
func WorkTypeLTE(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLTE(FieldWorkType, v))
}

// WorkTypeContains applies the Contains predicate on the "work_type" field.
func WorkTypeContains(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldContains(FieldWorkType, v))
}

// WorkTypeHasPrefix applies the HasPrefix predicate on the "work_type" field.
func WorkTypeHasPrefix(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldHasPrefix(FieldWorkType, v))
}

// WorkTypeHasSuffix applies the HasSuffix predicate on the "work_type" field.
func WorkTypeHasSuffix(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldHasSuffix(FieldWorkType, v))
}

// WorkTypeEqualFold applies the EqualFold predicate on the "work_type" field.
func WorkTypeEqualFold(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEqualFold(FieldWorkType, v))
}

// WorkTypeContainsFold applies the ContainsFold predicate on the "work_type" field.
func WorkTypeContainsFold(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldContainsFold(FieldWorkType, v))
}

// PublishedAtEQ applies the EQ predicate on the "published_at" field.
func PublishedAtEQ(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedAtNEQ applies the NEQ predicate on the "published_at" field.
func PublishedAtNEQ(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNEQ(FieldPublishedAt, v))
}

// PublishedAtIn applies the In predicate on the "published_at" field.
func PublishedAtIn(vs ...string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldIn(FieldPublishedAt, vs...))
}

// PublishedAtNotIn applies the NotIn predicate on the "published_at" field.
func PublishedAtNotIn(vs ...string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNotIn(FieldPublishedAt, vs...))
}

// PublishedAtGT applies the GT predicate on the "published_at" field.
func PublishedAtGT(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGT(FieldPublishedAt, v))
}

// PublishedAtGTE applies the GTE predicate on the "published_at" field.
func PublishedAtGTE(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGTE(FieldPublishedAt, v))
}

// PublishedAtLT applies the LT predicate on the "published_at" field.
func PublishedAtLT(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLT(FieldPublishedAt, v))
}

// PublishedAtLTE applies the LTE predicate on the "published_at" field.
func PublishedAtLTE(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLTE(FieldPublishedAt, v))
}

// PublishedAtContains applies the Contains predicate on the "published_at" field.
func PublishedAtContains(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldContains(FieldPublishedAt, v))
}

// PublishedAtHasPrefix applies the HasPrefix predicate on the "published_at" field.
func PublishedAtHasPrefix(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldHasPrefix(FieldPublishedAt, v))
}

// PublishedAtHasSuffix applies the HasSuffix predicate on the "published_at" field.
func PublishedAtHasSuffix(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldHasSuffix(FieldPublishedAt, v))
}

// PublishedAtEqualFold applies the EqualFold predicate on the "published_at" field.
func PublishedAtEqualFold(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEqualFold(FieldPublishedAt, v))
}

// PublishedAtContainsFold applies the ContainsFold predicate on the "published_at" field.
func PublishedAtContainsFold(v string) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldContainsFold(FieldPublishedAt, v))
}

// UserRefreshCountEQ applies the EQ predicate on the "user_refresh_count" field.
func UserRefreshCountEQ(v int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldUserRefreshCount, v))
}

// UserRefreshCountNEQ applies the NEQ predicate on the "user_refresh_count" field.
func UserRefreshCountNEQ(v int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNEQ(FieldUserRefreshCount, v))
}

// UserRefreshCountIn applies the In predicate on the "user_refresh_count" field.
func UserRefreshCountIn(vs ...int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldIn(FieldUserRefreshCount, vs...))
}

// UserRefreshCountNotIn applies the NotIn predicate on the "user_refresh_count" field.
func UserRefreshCountNotIn(vs ...int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNotIn(FieldUserRefreshCount, vs...))
}

// UserRefreshCountGT applies the GT predicate on the "user_refresh_count" field.
func UserRefreshCountGT(v int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGT(FieldUserRefreshCount, v))
}

// UserRefreshCountGTE applies the GTE predicate on the "user_refresh_count" field.
func UserRefreshCountGTE(v int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGTE(FieldUserRefreshCount, v))
}

// UserRefreshCountLT applies the LT predicate on the "user_refresh_count" field.
func UserRefreshCountLT(v int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLT(FieldUserRefreshCount, v))
}

// UserRefreshCountLTE applies the LTE predicate on the "user_refresh_count" field.
func UserRefreshCountLTE(v int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLTE(FieldUserRefreshCount, v))
}

// UserLinkEditCountEQ applies the EQ predicate on the "user_link_edit_count" field.
func UserLinkEditCountEQ(v int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldUserLinkEditCount, v))
}

// UserLinkEditCountNEQ applies the NEQ predicate on the "user_link_edit_count" field.
func UserLinkEditCountNEQ(v int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNEQ(FieldUserLinkEditCount, v))
}

// UserLinkEditCountIn applies the In predicate on the "user_link_edit_count" field.
func UserLinkEditCountIn(vs ...int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldIn(FieldUserLinkEditCount, vs...))
}

// UserLinkEditCountNotIn applies the NotIn predicate on the "user_link_edit_count" field.
func UserLinkEditCountNotIn(vs ...int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNotIn(FieldUserLinkEditCount, vs...))
}

// UserLinkEditCountGT applies the GT predicate on the "user_link_edit_count" field.
func UserLinkEditCountGT(v int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGT(FieldUserLinkEditCount, v))
}

// UserLinkEditCountGTE applies the GTE predicate on the "user_link_edit_count" field.
func UserLinkEditCountGTE(v int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGTE(FieldUserLinkEditCount, v))
}

// UserLinkEditCountLT applies the LT predicate on the "user_link_edit_count" field.
func UserLinkEditCountLT(v int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLT(FieldUserLinkEditCount, v))
}

// UserLinkEditCountLTE applies the LTE predicate on the "user_link_edit_count" field.
func UserLinkEditCountLTE(v int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLTE(FieldUserLinkEditCount, v))
}

// NextRefreshAtEQ applies the EQ predicate on the "next_refresh_at" field.
func NextRefreshAtEQ(v time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldNextRefreshAt, v))
}

// NextRefreshAtNEQ applies the NEQ predicate on the "next_refresh_at" field.
func NextRefreshAtNEQ(v time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNEQ(FieldNextRefreshAt, v))
}

// NextRefreshAtIn applies the In predicate on the "next_refresh_at" field.
func NextRefreshAtIn(vs ...time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldIn(FieldNextRefreshAt, vs...))
}

// NextRefreshAtNotIn applies the NotIn predicate on the "next_refresh_at" field.
func NextRefreshAtNotIn(vs ...time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNotIn(FieldNextRefreshAt, vs...))
}

// NextRefreshAtGT applies the GT predicate on the "next_refresh_at" field.
func NextRefreshAtGT(v time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGT(FieldNextRefreshAt, v))
}

// NextRefreshAtGTE applies the GTE predicate on the "next_refresh_at" field.
func NextRefreshAtGTE(v time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGTE(FieldNextRefreshAt, v))
}

// NextRefreshAtLT applies the LT predicate on the "next_refresh_at" field.
func NextRefreshAtLT(v time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLT(FieldNextRefreshAt, v))
}

// NextRefreshAtLTE applies the LTE predicate on the "next_refresh_at" field.
func NextRefreshAtLTE(v time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLTE(FieldNextRefreshAt, v))
}

// NextRefreshAtIsNil applies the IsNil predicate on the "next_refresh_at" field.
func NextRefreshAtIsNil() predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldIsNull(FieldNextRefreshAt))
}

// NextRefreshAtNotNil applies the NotNil predicate on the "next_refresh_at" field.
func NextRefreshAtNotNil() predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNotNull(FieldNextRefreshAt))
}

// LinkEpochEQ applies the EQ predicate on the "link_epoch" field.
func LinkEpochEQ(v int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldLinkEpoch, v))
}

// LinkEpochNEQ applies the NEQ predicate on the "link_epoch" field.
func LinkEpochNEQ(v int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNEQ(FieldLinkEpoch, v))
}

// LinkEpochIn applies the In predicate on the "link_epoch" field.
func LinkEpochIn(vs ...int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldIn(FieldLinkEpoch, vs...))
}

// LinkEpochNotIn applies the NotIn predicate on the "link_epoch" field.
func LinkEpochNotIn(vs ...int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNotIn(FieldLinkEpoch, vs...))
}

// LinkEpochGT applies the GT predicate on the "link_epoch" field.
func LinkEpochGT(v int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGT(FieldLinkEpoch, v))
}

// LinkEpochGTE applies the GTE predicate on the "link_epoch" field.
func LinkEpochGTE(v int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGTE(FieldLinkEpoch, v))
}

// LinkEpochLT applies the LT predicate on the "link_epoch" field.
func LinkEpochLT(v int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLT(FieldLinkEpoch, v))
}

// LinkEpochLTE applies the LTE predicate on the "link_epoch" field.
func LinkEpochLTE(v int) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLTE(FieldLinkEpoch, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.XHSNoteTracking) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.XHSNoteTracking) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.XHSNoteTracking) predicate.XHSNoteTracking {
	return predicate.XHSNoteTracking(sql.NotPredicates(p))
}
