// Code generated by ent, DO NOT EDIT.

package xhsnotetracking

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the xhsnotetracking type in the database.
	Label = "xhs_note_tracking"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTaskID holds the string denoting the task_id field in the database.
	FieldTaskID = "task_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldNoteURL holds the string denoting the note_url field in the database.
	FieldNoteURL = "note_url"
	// FieldCanonicalURL holds the string denoting the canonical_url field in the database.
	FieldCanonicalURL = "canonical_url"
	// FieldWorkID holds the string denoting the work_id field in the database.
	FieldWorkID = "work_id"
	// FieldAccountUserID holds the string denoting the account_user_id field in the database.
	FieldAccountUserID = "account_user_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// FieldCoverURL holds the string denoting the cover_url field in the database.
	FieldCoverURL = "cover_url"
	// FieldWorkType holds the string denoting the work_type field in the database.
	FieldWorkType = "work_type"
	// FieldPublishedAt holds the string denoting the published_at field in the database.
	FieldPublishedAt = "published_at"
	// FieldUserRefreshCount holds the string denoting the user_refresh_count field in the database.
	FieldUserRefreshCount = "user_refresh_count"
	// FieldUserLinkEditCount holds the string denoting the user_link_edit_count field in the database.
	FieldUserLinkEditCount = "user_link_edit_count"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the xhsnotetracking in the database.
	Table = "generation_task_xhs_notes"
)

// Columns holds all SQL columns for xhsnotetracking fields.
var Columns = []string{
	FieldID,
	FieldTaskID,
	FieldUserID,
	FieldNoteURL,
	FieldCanonicalURL,
	FieldWorkID,
	FieldAccountUserID,
	FieldAccountID,
	FieldTitle,
	FieldBody,
	FieldCoverURL,
	FieldWorkType,
	FieldPublishedAt,
	FieldUserRefreshCount,
	FieldUserLinkEditCount,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCanonicalURL holds the default value on creation for the "canonical_url" field.
	DefaultCanonicalURL string
	// DefaultWorkID holds the default value on creation for the "work_id" field.
	DefaultWorkID string
	// DefaultAccountUserID holds the default value on creation for the "account_user_id" field.
	DefaultAccountUserID string
	// DefaultAccountID holds the default value on creation for the "account_id" field.
	DefaultAccountID string
	// DefaultTitle holds the default value on creation for the "title" field.
	DefaultTitle string
	// DefaultBody holds the default value on creation for the "body" field.
	DefaultBody string
	// DefaultCoverURL holds the default value on creation for the "cover_url" field.
	DefaultCoverURL string
	// DefaultWorkType holds the default value on creation for the "work_type" field.
	DefaultWorkType string
	// DefaultPublishedAt holds the default value on creation for the "published_at" field.
	DefaultPublishedAt string
	// DefaultUserRefreshCount holds the default value on creation for the "user_refresh_count" field.
	DefaultUserRefreshCount int
	// DefaultUserLinkEditCount holds the default value on creation for the "user_link_edit_count" field.
	DefaultUserLinkEditCount int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the XHSNoteTracking queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTaskID orders the results by the task_id field.
func ByTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByNoteURL orders the results by the note_url field.
func ByNoteURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNoteURL, opts...).ToFunc()
}

// ByCanonicalURL orders the results by the canonical_url field.
func ByCanonicalURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanonicalURL, opts...).ToFunc()
}

// ByWorkID orders the results by the work_id field.
func ByWorkID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkID, opts...).ToFunc()
}

// ByAccountUserID orders the results by the account_user_id field.
func ByAccountUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountUserID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByBody orders the results by the body field.
func ByBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBody, opts...).ToFunc()
}

// ByCoverURL orders the results by the cover_url field.
func ByCoverURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoverURL, opts...).ToFunc()
}

// ByWorkType orders the results by the work_type field.
func ByWorkType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkType, opts...).ToFunc()
}

// ByPublishedAt orders the results by the published_at field.
func ByPublishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedAt, opts...).ToFunc()
}

// ByUserRefreshCount orders the results by the user_refresh_count field.
func ByUserRefreshCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserRefreshCount, opts...).ToFunc()
}

// ByUserLinkEditCount orders the results by the user_link_edit_count field.
func ByUserLinkEditCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserLinkEditCount, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
